-- Amateur (1-10)
local bonecraft = {
    by_name = {
        ['longbow'] = {
            name = 'Longbow',
            skill = 'Bonecraft',
            level = 1,
            subcraft = { 'Woodworking (17)' },
            crystal = 'Wind Crystal',
            ingredients = { 'Coeurl Whisker', 'Linen Cloth', 'Ram Horn', 'Yew Lumber x2' },
            hq1 = 'Longbow +1',
        },
        ['shell powder'] = {
            name = 'Shell Powder',
            skill = 'Bonecraft',
            level = 1,
            crystal = 'Wind Crystal',
            ingredients = { 'Seashell x3' },
            hq1 = 'Shell Powder x2',
            hq2 = 'Shell Powder x3',
            hq3 = 'Shell Powder x4',
        },
        ['wailing bone chip'] = {
            name = 'Wailing Bone Chip',
            skill = 'Bonecraft',
            level = 1,
            crystal = 'Wind Crystal',
            ingredients = { 'Bone Chip', 'Dark Anima', 'Earth Anima', 'Ice Anima' },
            keyitem = 'Bone Ensorcellment',
        },
        ['harpoon'] = {
            name = 'Harpoon',
            skill = 'Bonecraft',
            level = 2,
            subcraft = { 'Woodworking (10)' },
            crystal = 'Wind Crystal',
            ingredients = { 'Ash Lumber', 'Grass Thread', 'Sheep Tooth' },
            hq1 = 'Harpoon +1',
        },
        ['xiphos'] = {
            name = 'Xiphos',
            skill = 'Bonecraft',
            level = 2,
            subcraft = { 'Smithing (8)' },
            crystal = 'Fire Crystal',
            ingredients = { 'Bronze Ingot x2', 'Giant Femur' },
            hq1 = 'Xiphos +1',
        },
        ['shell earring'] = {
            name = 'Shell Earring',
            skill = 'Bonecraft',
            level = 3,
            crystal = 'Wind Crystal',
            ingredients = { 'Seashell x2' },
            hq1 = 'Shell Earring +1',
        },
        ['bone hairpin'] = {
            name = 'Bone Hairpin',
            skill = 'Bonecraft',
            level = 4,
            crystal = 'Wind Crystal',
            ingredients = { 'Bone Chip' },
            hq1 = 'Bone Hairpin +1',
        },
        ['self bow'] = {
            name = 'Self Bow',
            skill = 'Bonecraft',
            level = 5,
            subcraft = { 'Woodworking (16)' },
            crystal = 'Wind Crystal',
            ingredients = { 'Cotton Cloth', 'Giant Femur', 'Grass Thread', 'Willow Lumber' },
            hq1 = 'Self Bow +1',
        },
        ['shell powder 2'] = {
            name = 'Shell Powder',
            skill = 'Bonecraft',
            level = 5,
            crystal = 'Wind Crystal',
            ingredients = { 'Vongola Clam x2' },
            hq1 = 'Shell Powder x2',
            hq2 = 'Shell Powder x3',
            hq3 = 'Shell Powder x4',
        },
        ['fish scales'] = {
            name = 'Fish Scales x12',
            skill = 'Bonecraft',
            level = 6,
            crystal = 'Lightning Crystal',
            ingredients = { 'Gavial Fish' },
            hq1 = 'High-Quality Pugil Scales',
            hq2 = 'High-Quality Pugil Scales x2',
            hq3 = 'High-Quality Pugil Scales x4',
        },
        ['eldritch bone hairpin'] = {
            name = 'Eldritch Bone Hairpin',
            skill = 'Bonecraft',
            level = 7,
            crystal = 'Wind Crystal',
            ingredients = { 'Bone Hairpin', 'Wailing Bone Chip' },
        },
        ['power bow'] = {
            name = 'Power Bow',
            skill = 'Bonecraft',
            level = 7,
            subcraft = { 'Woodworking (28)' },
            crystal = 'Wind Crystal',
            ingredients = { 'Coeurl Whisker', 'Elm Lumber x2', 'Scorpion Claw', 'Wool Cloth' },
            hq1 = 'Power Bow +1',
        },
        ['shell ring'] = {
            name = 'Shell Ring',
            skill = 'Bonecraft',
            level = 7,
            crystal = 'Wind Crystal',
            ingredients = { 'Fish Scales', 'Seashell' },
            hq1 = 'Shell Ring +1',
        },
        ['claws'] = {
            name = 'Claws',
            skill = 'Bonecraft',
            level = 8,
            subcraft = { 'Smithing (32)' },
            crystal = 'Fire Crystal',
            ingredients = { 'Beetle Jaw', 'Steel Ingot' },
            hq1 = 'Claws +1',
        },
        ['fly lure'] = {
            name = 'Fly Lure',
            skill = 'Bonecraft',
            level = 8,
            subcraft = { 'Clothcraft (30)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Animal Glue', 'Bat Fang', 'Chocobo Feather' },
        },
        ['wailing shell'] = {
            name = 'Wailing Shell',
            skill = 'Bonecraft',
            level = 8,
            crystal = 'Wind Crystal',
            ingredients = { 'Dark Anima', 'Earth Anima', 'Ice Anima', 'Seashell' },
            keyitem = 'Bone Ensorcellment',
        },
        ['bone arrowheads'] = {
            name = 'Bone Arrowheads x6',
            skill = 'Bonecraft',
            level = 9,
            crystal = 'Wind Crystal',
            ingredients = { 'Bone Chip x2' },
            hq1 = 'Bone Arrowheads x8',
            hq2 = 'Bone Arrowheads x10',
            hq3 = 'Bone Arrowheads x12',
        },
        ['bone arrowheads (filing)'] = {
            name = 'Bone Arrowheads x18',
            skill = 'Bonecraft',
            level = 9,
            crystal = 'Wind Crystal',
            ingredients = { 'Bone Chip x6', 'Shagreen File' },
            keyitem = 'Filing',
            hq1 = 'Bone Arrowheads x24',
            hq2 = 'Bone Arrowheads x30',
            hq3 = 'Bone Arrowheads x36',
        },
        ['cat baghnakhs'] = {
            name = 'Cat Baghnakhs',
            skill = 'Bonecraft',
            level = 9,
            subcraft = { 'Smithing (3)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Bone Chip x3', 'Bronze Sheet', 'Rabbit Hide' },
            hq1 = 'Cat Baghnakhs +1',
        },
        ['bone arrow'] = {
            name = 'Bone Arrow x33',
            skill = 'Bonecraft',
            level = 10,
            subcraft = { 'Woodworking (2)' },
            crystal = 'Wind Crystal',
            ingredients = { 'Arrowwood Lumber', 'Bone Chip x3', 'Yagudo Feather x2' },
            hq1 = 'Bone Arrow x66',
            hq2 = 'Bone Arrow x99',
        },
        ['manashell ring'] = {
            name = 'Manashell Ring',
            skill = 'Bonecraft',
            level = 10,
            crystal = 'Wind Crystal',
            ingredients = { 'Shell Ring', 'Wailing Shell' },
        },
        -- Recruit (11-20)
        ['bone earring'] = {
            name = 'Bone Earring',
            skill = 'Bonecraft',
            level = 12,
            subcraft = { 'Goldsmithing (3)' },
            crystal = 'Wind Crystal',
            ingredients = { 'Bone Chip x2', 'Brass Ingot' },
            hq1 = 'Bone Earring +1',
        },
        ['gelatin'] = {
            name = 'Gelatin',
            skill = 'Bonecraft',
            level = 13,
            crystal = 'Fire Crystal',
            ingredients = { 'Chicken Bone x2', 'Distilled Water' },
            hq1 = 'Gelatin x2',
            hq2 = 'Gelatin x3',
            hq3 = 'Gelatin x4',
        },
        ['mythril claws'] = {
            name = 'Mythril Claws',
            skill = 'Bonecraft',
            level = 13,
            subcraft = { 'Smithing (48)' },
            crystal = 'Fire Crystal',
            ingredients = { 'Beetle Jaw', 'Mythril Ingot' },
            hq1 = 'Mythril Claws +1',
        },
        ['aht urhgan dart'] = {
            name = 'Aht Urhgan Dart x8',
            skill = 'Bonecraft',
            level = 14,
            subcraft = { 'Clothcraft (33)' },
            crystal = 'Wind Crystal',
            ingredients = { 'Animal Glue', 'Colibri Beak', 'Colibri Feather x2' },
            hq1 = 'Aht Urhgan Dart x16',
            hq2 = 'Aht Urhgan Dart x20',
            hq3 = 'Aht Urhgan Dart x24',
        },
        ['cornette'] = {
            name = 'Cornette',
            skill = 'Bonecraft',
            level = 14,
            subcraft = { 'Goldsmithing (14)' },
            crystal = 'Wind Crystal',
            ingredients = { 'Bone Chip', 'Brass Ingot' },
            hq1 = 'Cornette +1',
            hq2 = 'Cornette +2',
        },
        ['darksteel claws'] = {
            name = 'Darksteel Claws',
            skill = 'Bonecraft',
            level = 14,
            subcraft = { 'Smithing (56)' },
            crystal = 'Fire Crystal',
            ingredients = { 'Beetle Jaw', 'Darksteel Ingot' },
            hq1 = 'Darksteel Claws +1',
        },
        ['windurstian baghnakhs'] = {
            name = 'Windurstian Baghnakhs',
            skill = 'Bonecraft',
            level = 14,
            crystal = 'Earth Crystal',
            ingredients = { 'Bone Chip', 'Freesword\'s Baghnakhs' },
            hq1 = 'Federation Baghnakhs',
        },
        ['battle bow'] = {
            name = 'Battle Bow',
            skill = 'Bonecraft',
            level = 15,
            subcraft = { 'Woodworking (48)' },
            crystal = 'Wind Crystal',
            ingredients = { 'Chestnut Lumber x2', 'Coeurl Whisker', 'Scorpion Claw', 'Silk Cloth' },
            hq1 = 'Battle Bow +1',
        },
        ['fang necklace'] = {
            name = 'Fang Necklace',
            skill = 'Bonecraft',
            level = 15,
            crystal = 'Earth Crystal',
            ingredients = { 'Bat Fang x4', 'Black Tiger Fang', 'Bone Chip x2', 'Grass Thread' },
            hq1 = 'Spike Necklace',
        },
        ['great bow'] = {
            name = 'Great Bow',
            skill = 'Bonecraft',
            level = 15,
            subcraft = { 'Woodworking (38)' },
            crystal = 'Wind Crystal',
            ingredients = { 'Chestnut Lumber x2', 'Coeurl Whisker', 'Scorpion Claw', 'Velvet Cloth' },
            hq1 = 'Great Bow +1',
        },
        ['vivio femur'] = {
            name = 'Vivio Femur',
            skill = 'Bonecraft',
            level = 15,
            crystal = 'Wind Crystal',
            ingredients = { 'Giant Femur', 'Light Anima', 'Water Anima', 'Wind Anima' },
            keyitem = 'Bone Purification',
        },
        ['cermet claws'] = {
            name = 'Cermet Claws',
            skill = 'Bonecraft',
            level = 16,
            subcraft = { 'Alchemy (63)' },
            crystal = 'Fire Crystal',
            ingredients = { 'Beetle Jaw', 'Cermet Chunk' },
            hq1 = 'Cermet Claws +1',
        },
        ['gelatin 2'] = {
            name = 'Gelatin',
            skill = 'Bonecraft',
            level = 16,
            crystal = 'Fire Crystal',
            ingredients = { 'Bone Chip x4', 'Distilled Water' },
            hq1 = 'Gelatin x2',
            hq2 = 'Gelatin x3',
            hq3 = 'Gelatin x4',
        },
        ['bone ring'] = {
            name = 'Bone Ring',
            skill = 'Bonecraft',
            level = 17,
            crystal = 'Wind Crystal',
            ingredients = { 'Bone Chip', 'Sheep Tooth' },
            hq1 = 'Bone Ring +1',
        },
        ['bone mask'] = {
            name = 'Bone Mask',
            skill = 'Bonecraft',
            level = 18,
            crystal = 'Earth Crystal',
            ingredients = { 'Bone Chip', 'Giant Femur', 'Sheep Leather' },
            hq1 = 'Bone Mask +1',
        },
        ['pebble'] = {
            name = 'Pebble',
            skill = 'Bonecraft',
            level = 19,
            crystal = 'Wind Crystal',
            ingredients = { 'Istiridye' },
            hq1 = 'Pearl',
            hq2 = 'Black Pearl',
        },
        ['pebble 2'] = {
            name = 'Pebble',
            skill = 'Bonecraft',
            level = 19,
            crystal = 'Wind Crystal',
            ingredients = { 'Shall Shell' },
            hq1 = 'Pearl',
            hq2 = 'Black Pearl',
        },
        ['bone mittens'] = {
            name = 'Bone Mittens',
            skill = 'Bonecraft',
            level = 20,
            subcraft = { 'Leathercraft (5)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Bone Chip x2', 'Sheep Leather x2' },
            hq1 = 'Bone Mittens +1',
        },
        -- Initiate (21-30)
        ['bone axe'] = {
            name = 'Bone Axe',
            skill = 'Bonecraft',
            level = 21,
            crystal = 'Wind Crystal',
            ingredients = { 'Giant Femur', 'Ram Horn x2' },
            hq1 = 'Bone Axe +1',
        },
        ['carapace powder'] = {
            name = 'Carapace Powder',
            skill = 'Bonecraft',
            level = 21,
            crystal = 'Wind Crystal',
            ingredients = { 'Beetle Shell x2' },
        },
        ['bone leggings'] = {
            name = 'Bone Leggings',
            skill = 'Bonecraft',
            level = 22,
            subcraft = { 'Leathercraft (5)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Bone Chip', 'Giant Femur', 'Sheep Leather x2' },
            hq1 = 'Bone Leggings +1',
        },
        ['bone pick'] = {
            name = 'Bone Pick',
            skill = 'Bonecraft',
            level = 23,
            subcraft = { 'Woodworking (6)' },
            crystal = 'Wind Crystal',
            ingredients = { 'Ash Lumber', 'Giant Femur' },
            hq1 = 'Bone Pick +1',
        },
        ['bone subligar'] = {
            name = 'Bone Subligar',
            skill = 'Bonecraft',
            level = 24,
            subcraft = { 'Leathercraft (6)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Bone Chip', 'Grass Cloth', 'Sheep Leather x2' },
            hq1 = 'Bone Subligar +1',
        },
        ['gemshorn'] = {
            name = 'Gemshorn',
            skill = 'Bonecraft',
            level = 24,
            crystal = 'Wind Crystal',
            ingredients = { 'Beetle Jaw', 'Giant Femur' },
            hq1 = 'Gemshorn +1',
        },
        ['jolt axe'] = {
            name = 'Jolt Axe',
            skill = 'Bonecraft',
            level = 24,
            crystal = 'Wind Crystal',
            ingredients = { 'Bone Axe', 'Lambent Fire Cell', 'Lambent Wind Cell' },
            keyitem = 'Bone Ensorcellment',
        },
        ['beetle ring'] = {
            name = 'Beetle Ring',
            skill = 'Bonecraft',
            level = 25,
            crystal = 'Wind Crystal',
            ingredients = { 'Beetle Jaw' },
            hq1 = 'Beetle Ring +1',
        },
        ['smooth beetle jaw'] = {
            name = 'Smooth Beetle Jaw',
            skill = 'Bonecraft',
            level = 25,
            crystal = 'Wind Crystal',
            ingredients = { 'Beetle Jaw', 'Light Anima', 'Wind Anima x2' },
            keyitem = 'Bone Purification',
        },
        ['bone harness'] = {
            name = 'Bone Harness',
            skill = 'Bonecraft',
            level = 26,
            subcraft = { 'Leathercraft (7)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Bone Chip', 'Giant Femur', 'Pugil Scales', 'Sheep Leather x2' },
            hq1 = 'Bone Harness +1',
        },
        ['beetle earring'] = {
            name = 'Beetle Earring',
            skill = 'Bonecraft',
            level = 27,
            crystal = 'Earth Crystal',
            ingredients = { 'Beetle Jaw', 'Silver Earring' },
            hq1 = 'Beetle Earring +1',
        },
        ['wailing ram horn'] = {
            name = 'Wailing Ram Horn',
            skill = 'Bonecraft',
            level = 27,
            crystal = 'Wind Crystal',
            ingredients = { 'Dark Anima', 'Earth Anima', 'Ice Anima', 'Ram Horn' },
            keyitem = 'Bone Ensorcellment',
        },
        ['beetle mask'] = {
            name = 'Beetle Mask',
            skill = 'Bonecraft',
            level = 28,
            crystal = 'Earth Crystal',
            ingredients = { 'Beetle Jaw', 'Lizard Skin' },
            hq1 = 'Beetle Mask +1',
        },
        ['gelatin 3'] = {
            name = 'Gelatin x4',
            skill = 'Bonecraft',
            level = 28,
            crystal = 'Fire Crystal',
            ingredients = { 'Distilled Water', 'Giant Femur' },
            hq1 = 'Gelatin x6',
            hq2 = 'Gelatin x8',
            hq3 = 'Gelatin x10',
        },
        ['healing harness'] = {
            name = 'Healing Harness',
            skill = 'Bonecraft',
            level = 29,
            crystal = 'Earth Crystal',
            ingredients = { 'Bone Harness', 'Vivio Femur' },
        },
        ['horn hairpin'] = {
            name = 'Horn Hairpin',
            skill = 'Bonecraft',
            level = 29,
            crystal = 'Wind Crystal',
            ingredients = { 'Ram Horn' },
            hq1 = 'Horn Hairpin +1',
        },
        ['seer\'s crown'] = {
            name = 'Seer\'s Crown',
            skill = 'Bonecraft',
            level = 29,
            subcraft = { 'Leathercraft (20)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Bone Chip', 'Coeurl Whisker', 'Linen Thread', 'Lizard Molt' },
            hq1 = 'Seer\'s Crown +1',
        },
        ['beetle mittens'] = {
            name = 'Beetle Mittens',
            skill = 'Bonecraft',
            level = 30,
            subcraft = { 'Leathercraft (8)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Beetle Shell', 'Lizard Skin x2' },
            hq1 = 'Beetle Mittens +1',
        },
        ['san d\'orian horn'] = {
            name = 'San d\'Orian Horn',
            skill = 'Bonecraft',
            level = 30,
            crystal = 'Wind Crystal',
            ingredients = { 'Giant Femur', 'Royal Spearman\'s Horn' },
            hq1 = 'Kingdom Horn',
        },
        -- Novice (31-40)
        ['beetle gorget'] = {
            name = 'Beetle Gorget',
            skill = 'Bonecraft',
            level = 31,
            crystal = 'Earth Crystal',
            ingredients = { 'Beetle Jaw x2', 'Beetle Shell' },
            hq1 = 'Green Gorget',
        },
        ['beetle leggings'] = {
            name = 'Beetle Leggings',
            skill = 'Bonecraft',
            level = 32,
            subcraft = { 'Leathercraft (8)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Beetle Jaw', 'Beetle Shell', 'Lizard Skin x2' },
            hq1 = 'Beetle Leggings +1',
        },
        ['eldritch horn hairpin'] = {
            name = 'Eldritch Horn Hairpin',
            skill = 'Bonecraft',
            level = 32,
            crystal = 'Wind Crystal',
            ingredients = { 'Horn Hairpin', 'Wailing Ram Horn' },
        },
        ['beetle arrowheads'] = {
            name = 'Beetle Arrowheads x6',
            skill = 'Bonecraft',
            level = 33,
            crystal = 'Wind Crystal',
            ingredients = { 'Beetle Jaw', 'Bone Chip' },
            hq1 = 'Beetle Arrowheads x8',
            hq2 = 'Beetle Arrowheads x10',
            hq3 = 'Beetle Arrowheads x12',
        },
        ['beetle arrowheads (filing)'] = {
            name = 'Beetle Arrowheads x18',
            skill = 'Bonecraft',
            level = 33,
            crystal = 'Wind Crystal',
            ingredients = { 'Beetle Jaw x3', 'Bone Chip x3', 'Shagreen File' },
            keyitem = 'Filing',
            hq1 = 'Beetle Arrowheads x24',
            hq2 = 'Beetle Arrowheads x30',
            hq3 = 'Beetle Arrowheads x36',
        },
        ['beetle subligar'] = {
            name = 'Beetle Subligar',
            skill = 'Bonecraft',
            level = 34,
            subcraft = { 'Leathercraft (9)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Beetle Jaw', 'Cotton Cloth', 'Lizard Skin' },
            hq1 = 'Beetle Subligar +1',
        },
        ['turtle shield'] = {
            name = 'Turtle Shield',
            skill = 'Bonecraft',
            level = 35,
            crystal = 'Earth Crystal',
            ingredients = { 'Beetle Shell', 'Turtle Shell' },
            hq1 = 'Turtle Shield +1',
        },
        ['wind arrowheads'] = {
            name = 'Wind Arrowheads x6',
            skill = 'Bonecraft',
            level = 35,
            subcraft = { 'Alchemy (57)' },
            crystal = 'Wind Crystal',
            ingredients = { 'Colibri Beak', 'Copper Ingot' },
            hq1 = 'Wind Arrowheads x8',
            hq2 = 'Wind Arrowheads x10',
            hq3 = 'Wind Arrowheads x12',
        },
        ['beetle harness'] = {
            name = 'Beetle Harness',
            skill = 'Bonecraft',
            level = 36,
            subcraft = { 'Leathercraft (9)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Beetle Shell x2', 'Lizard Skin x3' },
            hq1 = 'Beetle Harness +1',
        },
        ['horn ring'] = {
            name = 'Horn Ring',
            skill = 'Bonecraft',
            level = 37,
            crystal = 'Wind Crystal',
            ingredients = { 'Fish Scales', 'Ram Horn' },
            hq1 = 'Horn Ring +1',
        },
        ['fang arrowheads'] = {
            name = 'Fang Arrowheads x6',
            skill = 'Bonecraft',
            level = 38,
            crystal = 'Wind Crystal',
            ingredients = { 'Black Tiger Fang', 'Bone Chip' },
            hq1 = 'Fang Arrowheads x8',
            hq2 = 'Fang Arrowheads x10',
            hq3 = 'Fang Arrowheads x12',
        },
        ['fang arrowheads (filing)'] = {
            name = 'Fang Arrowheads x18',
            skill = 'Bonecraft',
            level = 38,
            crystal = 'Wind Crystal',
            ingredients = { 'Black Tiger Fang x3', 'Bone Chip x3', 'Shagreen File' },
            keyitem = 'Filing',
            hq1 = 'Fang Arrowheads x24',
            hq2 = 'Fang Arrowheads x30',
            hq3 = 'Fang Arrowheads x36',
        },
        ['shade mittens'] = {
            name = 'Shade Mittens',
            skill = 'Bonecraft',
            level = 38,
            subcraft = { 'Clothcraft (21)', 'Leathercraft (21)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Eft Skin', 'Luminicloth', 'Photoanima', 'Sheep Leather', 'Tiger Leather', 'Uragnite Shell' },
            hq1 = 'Shade Mittens +1',
        },
        ['shade tiara'] = {
            name = 'Shade Tiara',
            skill = 'Bonecraft',
            level = 38,
            subcraft = { 'Leathercraft (24)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Eft Skin', 'Photoanima', 'Uragnite Shell' },
            hq1 = 'Shade Tiara +1',
        },
        ['bone cudgel'] = {
            name = 'Bone Cudgel',
            skill = 'Bonecraft',
            level = 39,
            crystal = 'Wind Crystal',
            ingredients = { 'Bone Chip x6', 'Giant Femur', 'Grass Cloth' },
            hq1 = 'Bone Cudgel +1',
        },
        ['shade tights'] = {
            name = 'Shade Tights',
            skill = 'Bonecraft',
            level = 39,
            subcraft = { 'Clothcraft (23)', 'Leathercraft (21)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Eft Skin', 'Luminicloth', 'Photoanima', 'Tiger Leather', 'Uragnite Shell', 'Velvet Cloth' },
            hq1 = 'Shade Tights +1',
        },
        ['shade leggings'] = {
            name = 'Shade Leggings',
            skill = 'Bonecraft',
            level = 40,
            subcraft = { 'Clothcraft (22)', 'Leathercraft (21)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Eft Skin', 'Lizard Skin', 'Luminicloth', 'Photoanima', 'Tiger Leather x2', 'Uragnite Shell' },
            hq1 = 'Shade Leggings +1',
        },
        ['titanictus shell'] = {
            name = 'Titanictus Shell',
            skill = 'Bonecraft',
            level = 40,
            crystal = 'Lightning Crystal',
            ingredients = { 'Armored Pisces' },
        },
        ['titanictus shell 2'] = {
            name = 'Titanictus Shell',
            skill = 'Bonecraft',
            level = 40,
            crystal = 'Lightning Crystal',
            ingredients = { 'Titanictus' },
            hq1 = 'Titanictus Shell x2',
            hq2 = 'Titanictus Shell x3',
            hq3 = 'Titanictus Shell x4',
        },
        -- Apprentice (41-50)
        ['bone knife'] = {
            name = 'Bone Knife',
            skill = 'Bonecraft',
            level = 41,
            crystal = 'Wind Crystal',
            ingredients = { 'Giant Femur', 'Walnut Lumber' },
            hq1 = 'Bone Knife +1',
        },
        ['garish crown'] = {
            name = 'Garish Crown',
            skill = 'Bonecraft',
            level = 41,
            subcraft = { 'Leathercraft (11)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Beetle Jaw', 'Bloodthread', 'Coeurl Whisker', 'Lizard Molt' },
            hq1 = 'Rubious Crown',
        },
        ['gendawa'] = {
            name = 'Gendawa',
            skill = 'Bonecraft',
            level = 41,
            subcraft = { 'Woodworking (93)' },
            crystal = 'Wind Crystal',
            ingredients = { 'Ancient Lumber x2', 'Coeurl Whisker', 'Rainbow Cloth', 'Taurus Horn' },
            hq1 = 'Gendawa +1',
        },
        ['luminous shell'] = {
            name = 'Luminous Shell',
            skill = 'Bonecraft',
            level = 41,
            crystal = 'Wind Crystal',
            ingredients = { 'Crab Shell', 'Dark Anima', 'Lightning Anima x2' },
            keyitem = 'Bone Ensorcellment',
        },
        ['vivio crab shell'] = {
            name = 'Vivio Crab Shell',
            skill = 'Bonecraft',
            level = 41,
            crystal = 'Wind Crystal',
            ingredients = { 'Crab Shell', 'Light Anima', 'Water Anima', 'Wind Anima' },
            keyitem = 'Bone Purification',
        },
        ['carapace ring'] = {
            name = 'Carapace Ring',
            skill = 'Bonecraft',
            level = 42,
            subcraft = { 'Goldsmithing (11)' },
            crystal = 'Wind Crystal',
            ingredients = { 'Crab Shell', 'Mythril Ingot' },
            hq1 = 'Carapace Ring +1',
        },
        ['shade harness'] = {
            name = 'Shade Harness',
            skill = 'Bonecraft',
            level = 42,
            subcraft = { 'Leathercraft (25)', 'Clothcraft (24)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Eft Skin x2', 'Luminicloth', 'Photoanima', 'Tiger Leather', 'Uragnite Shell x2', 'Velvet Cloth' },
            hq1 = 'Shade Harness +1',
        },
        ['horn arrowheads'] = {
            name = 'Horn Arrowheads x6',
            skill = 'Bonecraft',
            level = 43,
            crystal = 'Wind Crystal',
            ingredients = { 'Bone Chip', 'Ram Horn' },
            hq1 = 'Horn Arrowheads x8',
            hq2 = 'Horn Arrowheads x10',
            hq3 = 'Horn Arrowheads x12',
        },
        ['horn arrowheads (filing)'] = {
            name = 'Horn Arrowheads x18',
            skill = 'Bonecraft',
            level = 43,
            crystal = 'Wind Crystal',
            ingredients = { 'Bone Chip x3', 'Ram Horn x3', 'Shagreen File' },
            keyitem = 'Filing',
            hq1 = 'Horn Arrowheads x24',
            hq2 = 'Horn Arrowheads x30',
            hq3 = 'Horn Arrowheads x36',
        },
        ['skeleton key'] = {
            name = 'Skeleton Key x2',
            skill = 'Bonecraft',
            level = 43,
            subcraft = { 'Alchemy (34)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Animal Glue', 'Bat Fang x2', 'Carbon Fiber', 'Chicken Bone', 'Glass Fiber', 'Hecteyes Eye', 'Sheep Tooth' },
            hq1 = 'Skeleton Key x4',
            hq2 = 'Skeleton Key x6',
            hq3 = 'Skeleton Key x8',
        },
        ['sleep arrowheads'] = {
            name = 'Sleep Arrowheads x6',
            skill = 'Bonecraft',
            level = 43,
            subcraft = { 'Alchemy (64)' },
            crystal = 'Wind Crystal',
            ingredients = { 'Animal Glue', 'Bone Chip', 'Ram Horn', 'Sleeping Potion' },
            hq1 = 'Sleep Arrowheads x8',
            hq2 = 'Sleep Arrowheads x10',
            hq3 = 'Sleep Arrowheads x12',
        },
        ['carapace mittens'] = {
            name = 'Carapace Mittens',
            skill = 'Bonecraft',
            level = 44,
            subcraft = { 'Leathercraft (11)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Crab Shell', 'Dhalmel Leather', 'Fish Scales' },
            hq1 = 'Carapace Mittens +1',
        },
        ['earth arrowheads'] = {
            name = 'Earth Arrowheads x6',
            skill = 'Bonecraft',
            level = 44,
            subcraft = { 'Alchemy (57)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Copper Ingot', 'Marid Tusk' },
            hq1 = 'Earth Arrowheads x8',
            hq2 = 'Earth Arrowheads x10',
            hq3 = 'Earth Arrowheads x12',
        },
        ['mist crown'] = {
            name = 'Mist Crown',
            skill = 'Bonecraft',
            level = 44,
            crystal = 'Earth Crystal',
            ingredients = { 'Garish Crown', 'Smooth Beetle Jaw' },
        },
        ['carapace mask'] = {
            name = 'Carapace Mask',
            skill = 'Bonecraft',
            level = 45,
            crystal = 'Earth Crystal',
            ingredients = { 'Crab Shell', 'Dhalmel Leather' },
            hq1 = 'Carapace Mask +1',
        },
        ['carapace leggings'] = {
            name = 'Carapace Leggings',
            skill = 'Bonecraft',
            level = 46,
            subcraft = { 'Leathercraft (12)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Crab Shell', 'Dhalmel Leather x2', 'Fish Scales' },
            hq1 = 'Carapace Leggings +1',
        },
        ['repeating crossbow'] = {
            name = 'Repeating Crossbow',
            skill = 'Bonecraft',
            level = 46,
            subcraft = { 'Woodworking (88)', 'Smithing (59)' },
            crystal = 'Wind Crystal',
            ingredients = { 'Carbon Fiber', 'Coeurl Whisker', 'Darksteel Ingot', 'Mahogany Lumber', 'Rosewood Lumber', 'Scorpion Claw' },
            hq1 = 'Machine Crossbow',
        },
        ['horn'] = {
            name = 'Horn',
            skill = 'Bonecraft',
            level = 47,
            crystal = 'Wind Crystal',
            ingredients = { 'Beetle Jaw', 'Ram Horn' },
            hq1 = 'Horn +1',
        },
        ['mandibular sickle'] = {
            name = 'Mandibular Sickle',
            skill = 'Bonecraft',
            level = 47,
            subcraft = { 'Smithing (45)', 'Woodworking (33)' },
            crystal = 'Wind Crystal',
            ingredients = { 'Antlion Jaw', 'Darksteel Ingot', 'Ebony Lumber', 'Ram Leather' },
            hq1 = 'Antlion Sickle',
        },
        ['thunder mittens'] = {
            name = 'Thunder Mittens',
            skill = 'Bonecraft',
            level = 47,
            crystal = 'Earth Crystal',
            ingredients = { 'Carapace Mittens', 'Luminous Shell' },
        },
        ['carapace subligar'] = {
            name = 'Carapace Subligar',
            skill = 'Bonecraft',
            level = 48,
            subcraft = { 'Leathercraft (12)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Crab Shell', 'Dhalmel Leather', 'Linen Cloth' },
            hq1 = 'Carapace Subligar +1',
        },
        ['carapace gorget'] = {
            name = 'Carapace Gorget',
            skill = 'Bonecraft',
            level = 49,
            crystal = 'Earth Crystal',
            ingredients = { 'Crab Shell x2', 'Iron Chain' },
            hq1 = 'Blue Gorget',
        },
        ['carapace harness'] = {
            name = 'Carapace Harness',
            skill = 'Bonecraft',
            level = 50,
            subcraft = { 'Leathercraft (13)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Crab Shell x2', 'Dhalmel Leather x2' },
            hq1 = 'Carapace Harness +1',
        },
        ['shotel'] = {
            name = 'Shotel',
            skill = 'Bonecraft',
            level = 50,
            subcraft = { 'Goldsmithing (69)', 'Smithing (33)' },
            crystal = 'Fire Crystal',
            ingredients = { 'Bugard Tusk', 'Silver Ingot', 'Steel Ingot', 'Tiger Eye' },
            hq1 = 'Shotel +1',
        },
        ['vivio scorpion claw'] = {
            name = 'Vivio Scorpion Claw',
            skill = 'Bonecraft',
            level = 50,
            crystal = 'Wind Crystal',
            ingredients = { 'Light Anima', 'Scorpion Claw', 'Water Anima', 'Wind Anima' },
            keyitem = 'Bone Purification',
        },
        -- Journeyman (51-60)
        ['bone rod'] = {
            name = 'Bone Rod',
            skill = 'Bonecraft',
            level = 51,
            crystal = 'Fire Crystal',
            ingredients = { 'Giant Femur', 'Ram Horn x2' },
            hq1 = 'Bone Rod +1',
        },
        ['shock subligar'] = {
            name = 'Shock Subligar',
            skill = 'Bonecraft',
            level = 51,
            crystal = 'Earth Crystal',
            ingredients = { 'Carapace Subligar', 'Luminous Shell' },
        },
        ['bandit\'s gun'] = {
            name = 'Bandit\'s Gun',
            skill = 'Bonecraft',
            level = 52,
            subcraft = { 'Smithing (47)' },
            crystal = 'Fire Crystal',
            ingredients = { 'Giant Femur', 'Steel Ingot x2' },
            hq1 = 'Bandit\'s Gun +1',
        },
        ['spirit shell'] = {
            name = 'Spirit Shell',
            skill = 'Bonecraft',
            level = 52,
            crystal = 'Wind Crystal',
            ingredients = { 'Dark Anima', 'Earth Anima x2', 'Turtle Shell' },
            keyitem = 'Bone Ensorcellment',
        },
        ['high healing harness'] = {
            name = 'High Healing Harness',
            skill = 'Bonecraft',
            level = 53,
            crystal = 'Earth Crystal',
            ingredients = { 'Carapace Harness', 'Vivio Crab Shell' },
        },
        ['kabura arrow'] = {
            name = 'Kabura Arrow x33',
            skill = 'Bonecraft',
            level = 53,
            subcraft = { 'Woodworking (91)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Bamboo Stick', 'Giant Bird Fletchings', 'Karimata Arrowheads', 'Ram Horn' },
            hq1 = 'Kabura Arrow x66',
            hq2 = 'Kabura Arrow x99',
        },
        ['scorpion arrowheads'] = {
            name = 'Scorpion Arrowheads x6',
            skill = 'Bonecraft',
            level = 53,
            crystal = 'Wind Crystal',
            ingredients = { 'Bone Chip', 'Scorpion Claw' },
            hq1 = 'Scorpion Arrowheads x8',
            hq2 = 'Scorpion Arrowheads x10',
            hq3 = 'Scorpion Arrowheads x12',
        },
        ['scorpion arrowheads (filing)'] = {
            name = 'Scorpion Arrowheads x18',
            skill = 'Bonecraft',
            level = 53,
            crystal = 'Wind Crystal',
            ingredients = { 'Bone Chip x3', 'Scorpion Claw x3', 'Shagreen File' },
            keyitem = 'Filing',
            hq1 = 'Scorpion Arrowheads x24',
            hq2 = 'Scorpion Arrowheads x30',
            hq3 = 'Scorpion Arrowheads x36',
        },
        ['shell hairpin'] = {
            name = 'Shell Hairpin',
            skill = 'Bonecraft',
            level = 53,
            crystal = 'Wind Crystal',
            ingredients = { 'Turtle Shell' },
            hq1 = 'Shell Hairpin +1',
        },
        ['turtle bangles'] = {
            name = 'Turtle Bangles',
            skill = 'Bonecraft',
            level = 54,
            crystal = 'Wind Crystal',
            ingredients = { 'Giant Femur', 'Turtle Shell x2' },
            hq1 = 'Turtle Bangles +1',
        },
        ['tortoise earring'] = {
            name = 'Tortoise Earring',
            skill = 'Bonecraft',
            level = 55,
            crystal = 'Wind Crystal',
            ingredients = { 'Gold Chain', 'Turtle Shell' },
            hq1 = 'Tortoise Earring +1',
        },
        ['yagudo headgear'] = {
            name = 'Yagudo Headgear',
            skill = 'Bonecraft',
            level = 55,
            subcraft = { 'Clothcraft (80)', 'Leathercraft (50)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Black Pearl x2', 'Bugard Tusk', 'Cockatrice Skin', 'Wool Thread', 'Yagudo Cutting', 'Yagudo Feather x2' },
        },
        ['justaucorps'] = {
            name = 'Justaucorps',
            skill = 'Bonecraft',
            level = 56,
            subcraft = { 'Clothcraft (26)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Beetle Shell', 'Gold Thread', 'Scorpion Claw x2', 'Wool Robe' },
            hq1 = 'Justaucorps +1',
        },
        ['blood stone'] = {
            name = 'Blood Stone',
            skill = 'Bonecraft',
            level = 57,
            crystal = 'Wind Crystal',
            ingredients = { 'Fiend Blood', 'Giant Femur', 'Grass Thread' },
            hq1 = 'Blood Stone +1',
        },
        ['bone scythe'] = {
            name = 'Bone Scythe',
            skill = 'Bonecraft',
            level = 57,
            subcraft = { 'Woodworking (19)' },
            crystal = 'Wind Crystal',
            ingredients = { 'Giant Femur x2', 'Grass Cloth', 'Sheep Tooth', 'Yew Lumber' },
            hq1 = 'Bone Scythe +1',
        },
        ['stone bangles'] = {
            name = 'Stone Bangles',
            skill = 'Bonecraft',
            level = 57,
            crystal = 'Earth Crystal',
            ingredients = { 'Spirit Shell', 'Turtle Bangles' },
        },
        ['armored arrowheads'] = {
            name = 'Armored Arrowheads x6',
            skill = 'Bonecraft',
            level = 58,
            subcraft = { 'Smithing (55)' },
            crystal = 'Wind Crystal',
            ingredients = { 'Steel Ingot', 'Taurus Horn' },
            hq1 = 'Armored Arrowheads x8',
            hq2 = 'Armored Arrowheads x10',
            hq3 = 'Armored Arrowheads x12',
        },
        ['armored arrowheads (filing)'] = {
            name = 'Armored Arrowheads x18',
            skill = 'Bonecraft',
            level = 58,
            subcraft = { 'Smithing (55)' },
            crystal = 'Wind Crystal',
            ingredients = { 'Shagreen File', 'Steel Ingot x3', 'Taurus Horn x3' },
            keyitem = 'Filing',
            hq1 = 'Armored Arrowheads x24',
            hq2 = 'Armored Arrowheads x30',
            hq3 = 'Armored Arrowheads x36',
        },
        ['astragalos'] = {
            name = 'Astragalos x8',
            skill = 'Bonecraft',
            level = 58,
            crystal = 'Wind Crystal',
            ingredients = { 'Beastman Blood', 'Black Ink', 'Giant Femur' },
            hq1 = 'Astragalos x12',
            hq2 = 'Astragalos x16',
            hq3 = 'Astragalos x20',
        },
        ['jagdplaute'] = {
            name = 'Jagdplaute',
            skill = 'Bonecraft',
            level = 58,
            subcraft = { 'Goldsmithing (81)' },
            crystal = 'Fire Crystal',
            ingredients = { 'Darksteel Sword', 'Emerald', 'Gold Ingot', 'Manticore Fang', 'Mercury', 'Platinum Ingot', 'Ruby', 'Topaz' },
            hq1 = 'Jagdplaute +1',
        },
        ['beetle knife'] = {
            name = 'Beetle Knife',
            skill = 'Bonecraft',
            level = 59,
            crystal = 'Wind Crystal',
            ingredients = { 'Beetle Jaw', 'Oak Lumber' },
            hq1 = 'Beetle Knife +1',
        },
        ['healing justaucorps'] = {
            name = 'Healing Justaucorps',
            skill = 'Bonecraft',
            level = 59,
            crystal = 'Earth Crystal',
            ingredients = { 'Justaucorps', 'Vivio Scorpion Claw' },
        },
        ['macuahuitl'] = {
            name = 'Macuahuitl',
            skill = 'Bonecraft',
            level = 59,
            crystal = 'Wind Crystal',
            ingredients = { 'Bugard Tusk', 'Macuahuitl -1', 'Rhinochimera' },
            hq1 = 'Macuahuitl +1',
        },
        ['staurobow'] = {
            name = 'Staurobow',
            skill = 'Bonecraft',
            level = 59,
            subcraft = { 'Woodworking (100)', 'Smithing (51)' },
            crystal = 'Wind Crystal',
            ingredients = { 'Carbon Fiber', 'Darksteel Ingot', 'Ebony Lumber', 'Flauros Whisker', 'Mahogany Lumber', 'Rattan Lumber', 'Unicorn Horn' },
            hq1 = 'Staurobow +1',
        },
        ['beak necklace'] = {
            name = 'Beak Necklace',
            skill = 'Bonecraft',
            level = 60,
            crystal = 'Earth Crystal',
            ingredients = { 'Colibri Beak x4', 'High-Quality Crab Shell', 'Mohbwa Thread', 'Oxblood', 'Wivre Maul' },
            hq1 = 'Beak Necklace +1',
        },
        ['bison jacket'] = {
            name = 'Bison Jacket',
            skill = 'Bonecraft',
            level = 60,
            subcraft = { 'Leathercraft (99)', 'Clothcraft (51)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Buffalo Horn', 'Buffalo Leather x2', 'Eft Skin', 'Manticore Hair x2', 'Manticore Leather x2' },
            hq1 = 'Brave\'s Jacket',
        },
        ['scorpion ring'] = {
            name = 'Scorpion Ring',
            skill = 'Bonecraft',
            level = 60,
            crystal = 'Wind Crystal',
            ingredients = { 'Scorpion Shell' },
            hq1 = 'Scorpion Ring +1',
        },
        -- Craftsman (61-70)
        ['coral horn'] = {
            name = 'Coral Horn',
            skill = 'Bonecraft',
            level = 61,
            crystal = 'Wind Crystal',
            ingredients = { 'Oxblood' },
        },
        ['fang earring'] = {
            name = 'Fang Earring',
            skill = 'Bonecraft',
            level = 61,
            crystal = 'Wind Crystal',
            ingredients = { 'Black Tiger Fang x2', 'Silver Chain' },
            hq1 = 'Spike Earring',
        },
        ['wind fan'] = {
            name = 'Wind Fan x66',
            skill = 'Bonecraft',
            level = 61,
            crystal = 'Earth Crystal',
            ingredients = { 'Bat Wing', 'Beeswax', 'Beetle Shell', 'Giant Femur', 'Wind Cluster' },
            hq1 = 'Wind Fan x99',
        },
        ['pirate\'s gun'] = {
            name = 'Pirate\'s Gun',
            skill = 'Bonecraft',
            level = 62,
            subcraft = { 'Smithing (49)' },
            crystal = 'Fire Crystal',
            ingredients = { 'Darksteel Ingot', 'Steel Ingot', 'Turtle Shell' },
            hq1 = 'Pirate\'s Gun +1',
        },
        ['darksteel jambiya'] = {
            name = 'Darksteel Jambiya',
            skill = 'Bonecraft',
            level = 62,
            subcraft = { 'Smithing (50)', 'Goldsmithing (33)' },
            crystal = 'Fire Crystal',
            ingredients = { 'Darksteel Ingot', 'Silver Ingot', 'Sunstone', 'Mercury', 'Ladybug Wing' },
            hq1 = 'Darksteel Jambiya +1',
        },
        ['ogre jambiya'] = {
            name = 'Ogre Jambiya',
            skill = 'Bonecraft',
            level = 62,
            subcraft = { 'Smithing (50)', 'Goldsmithing (33)' },
            crystal = 'Fire Crystal',
            ingredients = { 'Darksteel Ingot', 'Silver Ingot', 'Sunstone', 'Mercury', 'Buggane Horn' },
        },
        ['demon arrowheads'] = {
            name = 'Demon Arrowheads x6',
            skill = 'Bonecraft',
            level = 63,
            crystal = 'Wind Crystal',
            ingredients = { 'Bone Chip', 'Demon Horn' },
            hq1 = 'Demon Arrowheads x8',
            hq2 = 'Demon Arrowheads x10',
            hq3 = 'Demon Arrowheads x12',
        },
        ['demon arrowheads (filing)'] = {
            name = 'Demon Arrowheads x18',
            skill = 'Bonecraft',
            level = 63,
            crystal = 'Wind Crystal',
            ingredients = { 'Bone Chip x3', 'Demon Horn x3', 'Shagreen File' },
            keyitem = 'Filing',
            hq1 = 'Demon Arrowheads x24',
            hq2 = 'Demon Arrowheads x30',
            hq3 = 'Demon Arrowheads x36',
        },
        ['scorpion mittens'] = {
            name = 'Scorpion Mittens',
            skill = 'Bonecraft',
            level = 63,
            subcraft = { 'Leathercraft (31)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Pugil Scales', 'Ram Leather', 'Scorpion Shell' },
            hq1 = 'Scorpion Mittens +1',
        },
        ['marid mittens'] = {
            name = 'Marid Mittens',
            skill = 'Bonecraft',
            level = 64,
            subcraft = { 'Leathercraft (21)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Karakul Leather', 'Marid Tusk', 'Merrow Scale' },
            hq1 = 'Marid Mittens +1',
        },
        ['scorpion mask'] = {
            name = 'Scorpion Mask',
            skill = 'Bonecraft',
            level = 64,
            crystal = 'Earth Crystal',
            ingredients = { 'Ram Leather', 'Scorpion Shell' },
            hq1 = 'Scorpion Mask +1',
        },
        ['scapegoat'] = {
            name = 'Scapegoat',
            skill = 'Bonecraft',
            level = 65,
            crystal = 'Wind Crystal',
            ingredients = { 'Marid Tusk', 'Phoenix Feather' },
        },
        ['scorpion leggings'] = {
            name = 'Scorpion Leggings',
            skill = 'Bonecraft',
            level = 65,
            subcraft = { 'Leathercraft (32)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Pugil Scales', 'Ram Leather x2', 'Scorpion Shell' },
            hq1 = 'Scorpion Leggings +1',
        },
        ['crumhorn'] = {
            name = 'Crumhorn',
            skill = 'Bonecraft',
            level = 66,
            crystal = 'Wind Crystal',
            ingredients = { 'Beetle Jaw', 'Demon Horn' },
            hq1 = 'Crumhorn +1',
            hq2 = 'Crumhorn +2',
        },
        ['ladybug ring'] = {
            name = 'Ladybug Ring',
            skill = 'Bonecraft',
            level = 66,
            crystal = 'Wind Crystal',
            ingredients = { 'Ladybug Wing x2' },
            hq1 = 'Ladybug Ring +1',
        },
        ['marid leggings'] = {
            name = 'Marid Leggings',
            skill = 'Bonecraft',
            level = 66,
            subcraft = { 'Leathercraft (22)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Karakul Leather x2', 'Marid Tusk', 'Merrow Scale' },
            hq1 = 'Marid Leggings +1',
        },
        ['ivory sickle'] = {
            name = 'Ivory Sickle',
            skill = 'Bonecraft',
            level = 67,
            subcraft = { 'Goldsmithing (53)', 'Woodworking (31)' },
            crystal = 'Wind Crystal',
            ingredients = { 'Mahogany Lumber', 'Oversized Fang', 'Platinum Ingot', 'Ram Leather' },
            hq1 = 'Ivory Sickle +1',
        },
        ['scorpion subligar'] = {
            name = 'Scorpion Subligar',
            skill = 'Bonecraft',
            level = 67,
            subcraft = { 'Leathercraft (32)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Linen Cloth', 'Ram Leather', 'Scorpion Shell' },
            hq1 = 'Scorpion Subligar +1',
        },
        ['bone patas'] = {
            name = 'Bone Patas',
            skill = 'Bonecraft',
            level = 68,
            crystal = 'Fire Crystal',
            ingredients = { 'Carbon Fiber', 'Crab Shell', 'Giant Femur x2' },
            hq1 = 'Bone Patas +1',
        },
        ['seadog gun'] = {
            name = 'Seadog Gun',
            skill = 'Bonecraft',
            level = 68,
            subcraft = { 'Smithing (43)' },
            crystal = 'Fire Crystal',
            ingredients = { 'Coral Fragment x2', 'Steel Ingot x2' },
            hq1 = 'Seadog Gun +1',
        },
        ['beast horn'] = {
            name = 'Beast Horn',
            skill = 'Bonecraft',
            level = 69,
            crystal = 'Wind Crystal',
            ingredients = { 'Ram Horn x2' },
        },
        ['scorpion harness'] = {
            name = 'Scorpion Harness',
            skill = 'Bonecraft',
            level = 69,
            subcraft = { 'Leathercraft (33)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Ram Leather x2', 'Scorpion Shell x2', 'Venomous Claw' },
            hq1 = 'Scorpion Harness +1',
        },
        ['antlion trap'] = {
            name = 'Antlion Trap',
            skill = 'Bonecraft',
            level = 70,
            crystal = 'Earth Crystal',
            ingredients = { 'Animal Glue', 'Antican Pauldron', 'Antican Robe', 'Coeurl Whisker', 'High-Quality Antlion Jaw x2' },
        },
        ['demon\'s ring'] = {
            name = 'Demon\'s Ring',
            skill = 'Bonecraft',
            level = 70,
            crystal = 'Wind Crystal',
            ingredients = { 'Demon Horn', 'Fish Scales' },
            hq1 = 'Demon\'s Ring +1',
        },
        -- Artisan (71-80)
        ['hornet fleuret'] = {
            name = 'Hornet Fleuret',
            skill = 'Bonecraft',
            level = 71,
            subcraft = { 'Goldsmithing (52)' },
            crystal = 'Fire Crystal',
            ingredients = { 'Brass Ingot', 'Giant Femur', 'Giant Stinger', 'Moonstone', 'Pearl' },
            hq1 = 'Wasp Fleuret',
        },
        ['kilo fan'] = {
            name = 'Kilo Fan x66',
            skill = 'Bonecraft',
            level = 71,
            crystal = 'Earth Crystal',
            ingredients = { 'Bat Wing', 'Beeswax', 'Crab Shell', 'Giant Femur', 'Wind Cluster' },
            hq1 = 'Kilo Fan x99',
        },
        ['vivified coral'] = {
            name = 'Vivified Coral',
            skill = 'Bonecraft',
            level = 71,
            crystal = 'Wind Crystal',
            ingredients = { 'Coral Fragment', 'Light Anima', 'Lightning Anima', 'Water Anima' },
            keyitem = 'Bone Purification',
        },
        ['coral cuisses'] = {
            name = 'Coral Cuisses',
            skill = 'Bonecraft',
            level = 72,
            subcraft = { 'Leathercraft (1)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Coral Fragment x2', 'Leather Trousers', 'Rainbow Thread' },
            hq1 = 'Coral Cuisses +1',
        },
        ['coral subligar'] = {
            name = 'Coral Subligar',
            skill = 'Bonecraft',
            level = 72,
            subcraft = { 'Leathercraft (46)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Coeurl Leather', 'Coral Fragment', 'Linen Cloth' },
            hq1 = 'Merman\'s Subligar',
        },
        ['demon\'s knife'] = {
            name = 'Demon\'s Knife',
            skill = 'Bonecraft',
            level = 73,
            crystal = 'Wind Crystal',
            ingredients = { 'Demon Horn', 'Ebony Lumber' },
            hq1 = 'Demon\'s Knife +1',
        },
        ['lithic wyvern scale'] = {
            name = 'Lithic Wyvern Scale',
            skill = 'Bonecraft',
            level = 73,
            crystal = 'Wind Crystal',
            ingredients = { 'Earth Anima x2', 'Light Anima', 'Wyvern Scales' },
            keyitem = 'Bone Purification',
        },
        ['tactician magician\'s hooks +1'] = {
            name = 'Tactician Magician\'s Hooks +1',
            skill = 'Bonecraft',
            level = 73,
            crystal = 'Earth Crystal',
            ingredients = { 'Demon Horn', 'Tactician Magician\'s Hooks' },
            hq1 = 'Tactician Magician\'s Hooks +2',
        },
        ['vivio wyvern scale'] = {
            name = 'Vivio Wyvern Scale',
            skill = 'Bonecraft',
            level = 73,
            crystal = 'Wind Crystal',
            ingredients = { 'Light Anima', 'Water Anima', 'Wind Anima', 'Wyvern Scales' },
            keyitem = 'Bone Purification',
        },
        ['clown\'s subligar'] = {
            name = 'Clown\'s Subligar',
            skill = 'Bonecraft',
            level = 74,
            subcraft = { 'Leathercraft (31)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Coral Fragment', 'Lindwurm Skin', 'Linen Cloth' },
            hq1 = 'Clown\'s Subligar +1',
        },
        ['coral finger gauntlets'] = {
            name = 'Coral Finger Gauntlets',
            skill = 'Bonecraft',
            level = 74,
            crystal = 'Earth Crystal',
            ingredients = { 'Coral Fragment x2', 'Leather Gloves', 'Rainbow Thread' },
            hq1 = 'Coral Finger Gauntlets +1',
        },
        ['coral mittens'] = {
            name = 'Coral Mittens',
            skill = 'Bonecraft',
            level = 74,
            subcraft = { 'Leathercraft (48)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Coeurl Leather', 'Coral Fragment', 'Wyvern Scales' },
            hq1 = 'Merman\'s Mittens',
        },
        ['corsair\'s gun'] = {
            name = 'Corsair\'s Gun',
            skill = 'Bonecraft',
            level = 75,
            subcraft = { 'Smithing (53)' },
            crystal = 'Fire Crystal',
            ingredients = { 'Darksteel Ingot x2', 'Demon Horn' },
            hq1 = 'Corsair\'s Gun +1',
        },
        ['coral greaves'] = {
            name = 'Coral Greaves',
            skill = 'Bonecraft',
            level = 76,
            crystal = 'Earth Crystal',
            ingredients = { 'Coral Fragment x2', 'Leather Highboots', 'Rainbow Thread' },
            hq1 = 'Coral Greaves +1',
        },
        ['coral leggings'] = {
            name = 'Coral Leggings',
            skill = 'Bonecraft',
            level = 76,
            subcraft = { 'Leathercraft (41)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Coeurl Leather x2', 'Coral Fragment', 'Wyvern Scales' },
            hq1 = 'Merman\'s Leggings',
        },
        ['coral hairpin'] = {
            name = 'Coral Hairpin',
            skill = 'Bonecraft',
            level = 77,
            crystal = 'Wind Crystal',
            ingredients = { 'Black Pearl', 'Coral Fragment', 'Pearl' },
            hq1 = 'Merman\'s Hairpin',
        },
        ['coral visor'] = {
            name = 'Coral Visor',
            skill = 'Bonecraft',
            level = 77,
            crystal = 'Wind Crystal',
            ingredients = { 'Coral Fragment x2', 'Sheep Leather' },
            hq1 = 'Coral Visor +1',
        },
        ['coral cap'] = {
            name = 'Coral Cap',
            skill = 'Bonecraft',
            level = 78,
            crystal = 'Earth Crystal',
            ingredients = { 'Coral Fragment', 'Darksteel Cap' },
            hq1 = 'Merman\'s Cap',
        },
        ['marid tusk arrowheads'] = {
            name = 'Marid Tusk Arrowheads x6',
            skill = 'Bonecraft',
            level = 78,
            crystal = 'Wind Crystal',
            ingredients = { 'Bone Chip', 'Marid Tusk' },
            hq1 = 'Marid Tusk Arrowheads x8',
            hq2 = 'Marid Tusk Arrowheads x10',
            hq3 = 'Marid Tusk Arrowheads x12',
        },
        ['marid tusk arrowheads (filing)'] = {
            name = 'Marid Tusk Arrowheads x18',
            skill = 'Bonecraft',
            level = 78,
            crystal = 'Wind Crystal',
            ingredients = { 'Bone Chip x3', 'Marid Tusk x3', 'Shagreen File' },
            keyitem = 'Filing',
            hq1 = 'Marid Tusk Arrowheads x24',
            hq2 = 'Marid Tusk Arrowheads x30',
            hq3 = 'Marid Tusk Arrowheads x36',
        },
        ['quadav barbut'] = {
            name = 'Quadav Barbut',
            skill = 'Bonecraft',
            level = 78,
            subcraft = { 'Clothcraft (43)', 'Leathercraft (33)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Black Pearl x2', 'Bugard Tusk', 'Lizard Molt', 'Quadav Parts', 'Red Grass Cloth', 'Tiger Leather', 'Wool Thread' },
        },
        ['coral gorget'] = {
            name = 'Coral Gorget',
            skill = 'Bonecraft',
            level = 79,
            crystal = 'Wind Crystal',
            ingredients = { 'Coral Fragment', 'Sheep Leather' },
            hq1 = 'Merman\'s Gorget',
        },
        ['tigerfangs'] = {
            name = 'Tigerfangs',
            skill = 'Bonecraft',
            level = 79,
            crystal = 'Fire Crystal',
            ingredients = { 'Black Tiger Fang x2', 'Carbon Fiber', 'Scorpion Shell' },
            hq1 = 'Feral Fangs',
        },
        ['coral harness'] = {
            name = 'Coral Harness',
            skill = 'Bonecraft',
            level = 80,
            subcraft = { 'Leathercraft (50)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Coeurl Leather x2', 'Coral Fragment x2' },
            hq1 = 'Merman\'s Harness',
        },
        ['coral ring'] = {
            name = 'Coral Ring',
            skill = 'Bonecraft',
            level = 80,
            crystal = 'Wind Crystal',
            ingredients = { 'Coral Fragment x2' },
            hq1 = 'Merman\'s Ring',
        },
        ['coral scale mail'] = {
            name = 'Coral Scale Mail',
            skill = 'Bonecraft',
            level = 80,
            crystal = 'Earth Crystal',
            ingredients = { 'Coral Fragment x4', 'Leather Vest', 'Rainbow Thread', 'Sheep Leather' },
            hq1 = 'Coral Scale Mail +1',
        },
        ['reraise hairpin'] = {
            name = 'Reraise Hairpin',
            skill = 'Bonecraft',
            level = 80,
            crystal = 'Wind Crystal',
            ingredients = { 'Coral Hairpin', 'Vivified Coral' },
        },
        -- Adept (81-90)
        ['darksteel shield'] = {
            name = 'Darksteel Shield',
            skill = 'Bonecraft',
            level = 81,
            subcraft = { 'Smithing (58)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Ash Lumber', 'Darksteel Sheet x3', 'Wyvern Scales x4' },
            hq1 = 'Darksteel Shield +1',
        },
        ['marid ring'] = {
            name = 'Marid Ring',
            skill = 'Bonecraft',
            level = 81,
            crystal = 'Wind Crystal',
            ingredients = { 'Marid Tusk x2' },
            hq1 = 'Marid Ring +1',
        },
        ['saintly ring'] = {
            name = 'Saintly Ring',
            skill = 'Bonecraft',
            level = 81,
            crystal = 'Earth Crystal',
            ingredients = { 'Ascetic\'s Ring', 'Fish Scales' },
            hq1 = 'Saintly Ring +1',
        },
        ['dragon cuisses'] = {
            name = 'Dragon Cuisses',
            skill = 'Bonecraft',
            level = 82,
            subcraft = { 'Leathercraft (5)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Leather Trousers', 'Silver Thread', 'Wyvern Scales x2' },
            hq1 = 'Dragon Cuisses +1',
        },
        ['eremite\'s ring'] = {
            name = 'Eremite\'s Ring',
            skill = 'Bonecraft',
            level = 82,
            crystal = 'Earth Crystal',
            ingredients = { 'Hermit\'s Ring', 'Sheep Tooth' },
            hq1 = 'Eremite\'s Ring +1',
        },
        ['reraise gorget'] = {
            name = 'Reraise Gorget',
            skill = 'Bonecraft',
            level = 82,
            crystal = 'Wind Crystal',
            ingredients = { 'Coral Gorget', 'Vivified Coral' },
        },
        ['coral earring'] = {
            name = 'Coral Earring',
            skill = 'Bonecraft',
            level = 83,
            crystal = 'Wind Crystal',
            ingredients = { 'Coral Fragment x2', 'Silver Chain' },
            hq1 = 'Merman\'s Earring',
        },
        ['mega fan'] = {
            name = 'Mega Fan x66',
            skill = 'Bonecraft',
            level = 83,
            crystal = 'Earth Crystal',
            ingredients = { 'Bat Wing', 'Beeswax', 'Giant Femur', 'Scorpion Shell', 'Wind Cluster' },
            hq1 = 'Mega Fan x99',
        },
        ['behemoth knife'] = {
            name = 'Behemoth Knife',
            skill = 'Bonecraft',
            level = 84,
            crystal = 'Wind Crystal',
            ingredients = { 'Behemoth Horn', 'Mahogany Lumber' },
            hq1 = 'Behemoth Knife +1',
        },
        ['dragon finger gauntlets'] = {
            name = 'Dragon Finger Gauntlets',
            skill = 'Bonecraft',
            level = 84,
            crystal = 'Earth Crystal',
            ingredients = { 'Leather Gloves', 'Silver Thread', 'Wyvern Scales x2' },
            hq1 = 'Dragon Finger Gauntlets +1',
        },
        ['eris\' earring'] = {
            name = 'Eris\' Earring',
            skill = 'Bonecraft',
            level = 85,
            crystal = 'Earth Crystal',
            ingredients = { 'Nemesis Earring', 'Seashell' },
            hq1 = 'Eris\' Earring +1',
        },
        ['hellish bugle'] = {
            name = 'Hellish Bugle',
            skill = 'Bonecraft',
            level = 85,
            crystal = 'Earth Crystal',
            ingredients = { 'Colibri Beak', 'Imp Horn' },
            hq1 = 'Hellish Bugle +1',
        },
        ['dragon greaves'] = {
            name = 'Dragon Greaves',
            skill = 'Bonecraft',
            level = 86,
            crystal = 'Earth Crystal',
            ingredients = { 'Leather Highboots', 'Silver Thread', 'Wyvern Scales x2' },
            hq1 = 'Dragon Greaves +1',
        },
        ['shofar'] = {
            name = 'Shofar',
            skill = 'Bonecraft',
            level = 86,
            crystal = 'Wind Crystal',
            ingredients = { 'Beetle Jaw', 'Behemoth Horn' },
            hq1 = 'Shofar +1',
        },
        ['wivre gorget'] = {
            name = 'Wivre Gorget',
            skill = 'Bonecraft',
            level = 86,
            crystal = 'Wind Crystal',
            ingredients = { 'Karakul Leather', 'Wivre Horn' },
            hq1 = 'Wivre Gorget +1',
        },
        ['coral bangles'] = {
            name = 'Coral Bangles',
            skill = 'Bonecraft',
            level = 87,
            crystal = 'Wind Crystal',
            ingredients = { 'Coral Fragment x2', 'Giant Femur' },
            hq1 = 'Merman\'s Bangles',
        },
        ['dragon mask'] = {
            name = 'Dragon Mask',
            skill = 'Bonecraft',
            level = 87,
            crystal = 'Wind Crystal',
            ingredients = { 'Sheep Leather', 'Wyvern Scales x2' },
            hq1 = 'Dragon Mask +1',
        },
        ['snakeeye'] = {
            name = 'Snakeeye',
            skill = 'Bonecraft',
            level = 87,
            crystal = 'Wind Crystal',
            ingredients = { 'Hydra Fang x2', 'Wamoura Silk' },
            hq1 = 'Snakeeye +1',
        },
        ['coral sword'] = {
            name = 'Coral Sword',
            skill = 'Bonecraft',
            level = 88,
            crystal = 'Earth Crystal',
            ingredients = { 'Coral Fragment x4', 'Katzbalger' },
            hq1 = 'Merman\'s Sword',
        },
        ['lamian kaman'] = {
            name = 'Lamian Kaman',
            skill = 'Bonecraft',
            level = 88,
            crystal = 'Earth Crystal',
            ingredients = { 'Lamian Kaman -1', 'Marid Tusk', 'Scorpion Claw' },
            hq1 = 'Lamian Kaman +1',
        },
        ['naigama'] = {
            name = 'Naigama',
            skill = 'Bonecraft',
            level = 88,
            subcraft = { 'Goldsmithing (51)', 'Smithing (51)' },
            crystal = 'Wind Crystal',
            ingredients = { 'Bloodwood Lumber', 'Karakul Leather', 'Marid Tusk', 'Relic Steel', 'Scintillant Ingot' },
            hq1 = 'Naigama +1',
        },
        ['behemoth ring'] = {
            name = 'Behemoth Ring',
            skill = 'Bonecraft',
            level = 89,
            crystal = 'Wind Crystal',
            ingredients = { 'Behemoth Horn x2' },
            hq1 = 'Behemoth Ring +1',
        },
        ['earth greaves'] = {
            name = 'Earth Greaves',
            skill = 'Bonecraft',
            level = 89,
            crystal = 'Earth Crystal',
            ingredients = { 'Dragon Greaves', 'Lithic Wyvern Scale' },
        },
        ['inferno sabots'] = {
            name = 'Inferno Sabots',
            skill = 'Bonecraft',
            level = 89,
            crystal = 'Earth Crystal',
            ingredients = { 'Ebony Sabots', 'Namtar Bone' },
            hq1 = 'Inferno Sabots +1',
        },
        ['demon\'s harness'] = {
            name = 'Demon\'s Harness',
            skill = 'Bonecraft',
            level = 90,
            subcraft = { 'Leathercraft (59)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Behemoth Leather x2', 'Demon Skull x2' },
            hq1 = 'Demon\'s Harness +1',
        },
        ['dragon claws'] = {
            name = 'Dragon Claws',
            skill = 'Bonecraft',
            level = 90,
            crystal = 'Earth Crystal',
            ingredients = { 'Beetle Jaw', 'Dragon Talon x2' },
            hq1 = 'Dragon Claws +1',
        },
        ['dragon mail'] = {
            name = 'Dragon Mail',
            skill = 'Bonecraft',
            level = 90,
            subcraft = { 'Smithing (42)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Darksteel Chain', 'Darksteel Sheet', 'Dragon Scales', 'Leather Vest', 'Silver Thread', 'Wyvern Scales x3' },
            hq1 = 'Dragon Mail +1',
        },
        ['dragon mail +1'] = {
            name = 'Dragon Mail +1',
            skill = 'Bonecraft',
            level = 90,
            subcraft = { 'Smithing (42)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Darksteel Chain', 'Darksteel Sheet', 'Leather Vest', 'Nidhogg\'s Scales', 'Silver Thread', 'Wyvern Scales x3' },
        },
        -- Veteran (91-103)
        ['cursed subligar'] = {
            name = 'Cursed Subligar',
            skill = 'Bonecraft',
            level = 91,
            subcraft = { 'Leathercraft (41)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Angel Skin', 'Silk Cloth', 'Tiger Leather' },
            hq1 = 'Cursed Subligar -1',
        },
        ['demon helm'] = {
            name = 'Demon Helm',
            skill = 'Bonecraft',
            level = 91,
            crystal = 'Dark Crystal',
            ingredients = { 'Demon Horn x2', 'Demon Skull', 'Sheep Leather' },
            hq1 = 'Demon Helm +1',
        },
        ['igqira tiara'] = {
            name = 'Igqira Tiara',
            skill = 'Bonecraft',
            level = 91,
            subcraft = { 'Leathercraft (38)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Coeurl Leather', 'Coral Fragment x3', 'Garnet', 'Manticore Hair' },
            hq1 = 'Genie Tiara',
        },
        ['jambiya'] = {
            name = 'Jambiya',
            skill = 'Bonecraft',
            level = 91,
            subcraft = { 'Goldsmithing (60)', 'Smithing (39)' },
            crystal = 'Fire Crystal',
            ingredients = { 'Marid Tusk', 'Mercury', 'Pigeon\'s Blood Ruby', 'Scintillant Ingot', 'Steel Ingot' },
            hq1 = 'Jambiya +1',
        },
        ['carapace gauntlets'] = {
            name = 'Carapace Gauntlets',
            skill = 'Bonecraft',
            level = 92,
            crystal = 'Earth Crystal',
            ingredients = { 'High-Quality Crab Shell x2', 'Leather Gloves x2' },
            hq1 = 'Carapace Gauntlets +1',
        },
        ['cursed gloves'] = {
            name = 'Cursed Gloves',
            skill = 'Bonecraft',
            level = 92,
            subcraft = { 'Leathercraft (41)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Angel Skin', 'Tiger Leather', 'Wyvern Scales' },
            hq1 = 'Cursed Gloves -1',
        },
        ['dragon subligar'] = {
            name = 'Dragon Subligar',
            skill = 'Bonecraft',
            level = 92,
            subcraft = { 'Leathercraft (53)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Buffalo Leather', 'Dragon Bone', 'Sarcenet Cloth' },
            hq1 = 'Dragon Subligar +1',
        },
        ['healing mail'] = {
            name = 'Healing Mail',
            skill = 'Bonecraft',
            level = 92,
            crystal = 'Earth Crystal',
            ingredients = { 'Dragon Mail', 'Vivio Wyvern Scale' },
        },
        ['unicorn subligar'] = {
            name = 'Unicorn Subligar',
            skill = 'Bonecraft',
            level = 92,
            subcraft = { 'Leathercraft (58)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Behemoth Leather', 'Taffeta Cloth', 'Unicorn Horn' },
            hq1 = 'Unicorn Subligar +1',
        },
        ['carapace helm'] = {
            name = 'Carapace Helm',
            skill = 'Bonecraft',
            level = 93,
            crystal = 'Earth Crystal',
            ingredients = { 'Copper Ingot', 'High-Quality Crab Shell x2', 'Ram Leather', 'Sheep Leather' },
            hq1 = 'Carapace Helm +1',
        },
        ['igqira manillas'] = {
            name = 'Igqira Manillas',
            skill = 'Bonecraft',
            level = 93,
            subcraft = { 'Alchemy (41)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Avatar Blood', 'Bugard Tusk', 'Garnet', 'Manticore Hair', 'Uragnite Shell' },
            hq1 = 'Genie Manillas',
        },
        ['cursed leggings'] = {
            name = 'Cursed Leggings',
            skill = 'Bonecraft',
            level = 94,
            subcraft = { 'Leathercraft (44)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Angel Skin', 'Tiger Leather x2', 'Wyvern Scales' },
            hq1 = 'Cursed Leggings -1',
        },
        ['dragon mittens'] = {
            name = 'Dragon Mittens',
            skill = 'Bonecraft',
            level = 94,
            subcraft = { 'Leathercraft (51)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Buffalo Leather', 'Dragon Bone', 'Wyvern Scales' },
            hq1 = 'Dragon Mittens +1',
        },
        ['mammoth tusk'] = {
            name = 'Mammoth Tusk',
            skill = 'Bonecraft',
            level = 94,
            crystal = 'Wind Crystal',
            ingredients = { 'Giant Frozen Head' },
        },
        ['shell lamp'] = {
            name = 'Shell Lamp',
            skill = 'Bonecraft',
            level = 94,
            subcraft = { 'Alchemy (42)' },
            crystal = 'Wind Crystal',
            ingredients = { 'Uragnite Shell', 'Flint Glass Sheet', 'Kaolin x2', 'Bomb Ash' },
        },
        ['carapace breastplate'] = {
            name = 'Carapace Breastplate',
            skill = 'Bonecraft',
            level = 95,
            crystal = 'Earth Crystal',
            ingredients = { 'High-Quality Crab Shell x4', 'Ram Leather x2', 'Sheep Leather' },
            hq1 = 'Carapace Breastplate +1',
        },
        ['gavial cuisses'] = {
            name = 'Gavial Cuisses',
            skill = 'Bonecraft',
            level = 95,
            subcraft = { 'Leathercraft (15)' },
            crystal = 'Earth Crystal',
            ingredients = { 'High-Quality Pugil Scales', 'Leather Trousers', 'Rainbow Thread', 'Titanictus Shell' },
            hq1 = 'Gavial Cuisses +1',
        },
        ['igqira huaraches'] = {
            name = 'Igqira Huaraches',
            skill = 'Bonecraft',
            level = 95,
            crystal = 'Earth Crystal',
            ingredients = { 'Bugard Tusk', 'Coeurl Leather', 'Coeurl Whisker', 'Harajnite Shell', 'High-Quality Bugard Skin' },
            hq1 = 'Genie Huaraches',
        },
        ['unicorn mittens'] = {
            name = 'Unicorn Mittens',
            skill = 'Bonecraft',
            level = 95,
            subcraft = { 'Leathercraft (54)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Behemoth Leather', 'Gold Thread', 'Unicorn Horn', 'Wyvern Scales' },
            hq1 = 'Unicorn Mittens +1',
        },
        ['acheron shield'] = {
            name = 'Acheron Shield',
            skill = 'Bonecraft',
            level = 96,
            crystal = 'Earth Crystal',
            ingredients = { 'Adamantoise Shell x2', 'Ram Leather' },
            hq1 = 'Acheron Shield +1',
        },
        ['dragon leggings'] = {
            name = 'Dragon Leggings',
            skill = 'Bonecraft',
            level = 96,
            subcraft = { 'Leathercraft (45)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Buffalo Leather x2', 'Dragon Bone', 'Wyvern Scales' },
            hq1 = 'Dragon Leggings +1',
        },
        ['hydra cuisses'] = {
            name = 'Hydra Cuisses',
            skill = 'Bonecraft',
            level = 96,
            subcraft = { 'Leathercraft (15)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Hydra Scale', 'Leather Trousers', 'Rainbow Thread', 'Titanictus Shell' },
            hq1 = 'Hydra Cuisses +1',
        },
        ['scorpion gauntlets'] = {
            name = 'Scorpion Gauntlets',
            skill = 'Bonecraft',
            level = 96,
            crystal = 'Earth Crystal',
            ingredients = { 'High-Quality Scorpion Shell x2', 'Leather Gloves x2' },
            hq1 = 'Scorpion Gauntlets +1',
        },
        ['trumpet ring'] = {
            name = 'Trumpet Ring',
            skill = 'Bonecraft',
            level = 96,
            crystal = 'Wind Crystal',
            ingredients = { 'Trumpet Shell x2' },
            hq1 = 'Nereid Ring',
        },
        ['cursed cap'] = {
            name = 'Cursed Cap',
            skill = 'Bonecraft',
            level = 97,
            crystal = 'Earth Crystal',
            ingredients = { 'Angel Skin', 'Darksteel Cap' },
            hq1 = 'Cursed Cap -1',
        },
        ['gavial finger gauntlets'] = {
            name = 'Gavial Finger Gauntlets',
            skill = 'Bonecraft',
            level = 97,
            crystal = 'Earth Crystal',
            ingredients = { 'High-Quality Pugil Scales', 'Leather Gloves', 'Rainbow Thread', 'Titanictus Shell' },
            hq1 = 'Gavial Finger Gauntlets +1',
        },
        ['igqira lappas'] = {
            name = 'Igqira Lappas',
            skill = 'Bonecraft',
            level = 97,
            subcraft = { 'Leathercraft (46)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Coeurl Leather', 'Coeurl Whisker', 'High-Quality Bugard Skin', 'Manticore Leather', 'Megalobugard Tusk', 'Uragnite Shell' },
            hq1 = 'Genie Lappas',
        },
        ['scorpion helm'] = {
            name = 'Scorpion Helm',
            skill = 'Bonecraft',
            level = 97,
            crystal = 'Earth Crystal',
            ingredients = { 'Copper Ingot', 'High-Quality Scorpion Shell x2', 'Ram Leather', 'Sheep Leather' },
            hq1 = 'Scorpion Helm +1',
        },
        ['unicorn leggings'] = {
            name = 'Unicorn Leggings',
            skill = 'Bonecraft',
            level = 97,
            subcraft = { 'Leathercraft (55)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Behemoth Leather x2', 'Gold Thread', 'Unicorn Horn', 'Wyvern Scales' },
            hq1 = 'Unicorn Leggings +1',
        },
        ['cerberus ring'] = {
            name = 'Cerberus Ring',
            skill = 'Bonecraft',
            level = 98,
            crystal = 'Wind Crystal',
            ingredients = { 'Cerberus Claw x2' },
            hq1 = 'Cerberus Ring +1',
        },
        ['dragon cap'] = {
            name = 'Dragon Cap',
            skill = 'Bonecraft',
            level = 98,
            crystal = 'Earth Crystal',
            ingredients = { 'Darksteel Cap', 'Dragon Bone' },
            hq1 = 'Dragon Cap +1',
        },
        ['hydra finger gauntlets'] = {
            name = 'Hydra Finger Gauntlets',
            skill = 'Bonecraft',
            level = 98,
            crystal = 'Earth Crystal',
            ingredients = { 'Hydra Scale', 'Leather Gloves', 'Rainbow Thread', 'Titanictus Shell' },
            hq1 = 'Hydra Finger Gauntlets +1',
        },
        ['orochi nodowa'] = {
            name = 'Orochi Nodowa',
            skill = 'Bonecraft',
            level = 98,
            crystal = 'Earth Crystal',
            ingredients = { 'Hydra Scale', 'Wamoura Silk' },
            hq1 = 'Orochi Nodowa +1',
        },
        ['wyvern helm'] = {
            name = 'Wyvern Helm',
            skill = 'Bonecraft',
            level = 98,
            subcraft = { 'Leathercraft (41)' },
            crystal = 'Dark Crystal',
            ingredients = { 'Beeswax', 'Guivre\'s Skull', 'Sheep Leather', 'Tiger Leather' },
            hq1 = 'Wyvern Helm +1',
        },
        ['gavial greaves'] = {
            name = 'Gavial Greaves',
            skill = 'Bonecraft',
            level = 99,
            crystal = 'Earth Crystal',
            ingredients = { 'High-Quality Pugil Scales', 'Leather Highboots', 'Rainbow Thread', 'Titanictus Shell' },
            hq1 = 'Gavial Greaves +1',
        },
        ['hydra greaves'] = {
            name = 'Hydra Greaves',
            skill = 'Bonecraft',
            level = 99,
            crystal = 'Earth Crystal',
            ingredients = { 'Hydra Scale', 'Leather Highboots', 'Rainbow Thread', 'Titanictus Shell' },
            hq1 = 'Hydra Greaves +1',
        },
        ['igqira weskit'] = {
            name = 'Igqira Weskit',
            skill = 'Bonecraft',
            level = 99,
            subcraft = { 'Alchemy (44)', 'Leathercraft (55)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Avatar Blood', 'Bugard Tusk', 'Coeurl Leather', 'Dhalmel Leather', 'Dragon Talon', 'High-Quality Bugard Skin', 'Lapis Lazuli', 'Manticore Hair' },
            hq1 = 'Genie Weskit',
        },
        ['scorpion breastplate'] = {
            name = 'Scorpion Breastplate',
            skill = 'Bonecraft',
            level = 99,
            crystal = 'Earth Crystal',
            ingredients = { 'High-Quality Scorpion Shell x4', 'Ram Leather x2', 'Sheep Leather' },
            hq1 = 'Scorpion Breastplate +1',
        },
        ['unicorn cap'] = {
            name = 'Unicorn Cap',
            skill = 'Bonecraft',
            level = 99,
            subcraft = { 'Leathercraft (52)', 'Smithing (47)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Behemoth Leather', 'Darksteel Sheet', 'Gold Thread', 'Tiger Leather', 'Unicorn Horn' },
            hq1 = 'Unicorn Cap +1',
        },
        ['wyvern helm 2'] = {
            name = 'Wyvern Helm',
            skill = 'Bonecraft',
            level = 99,
            subcraft = { 'Leathercraft (41)' },
            crystal = 'Dark Crystal',
            ingredients = { 'Beeswax', 'Sheep Leather', 'Tiger Leather', 'Wyvern Skull' },
            hq1 = 'Wyvern Helm +1',
        },
        ['chronos tooth'] = {
            name = 'Chronos Tooth',
            skill = 'Bonecraft',
            level = 100,
            crystal = 'Wind Crystal',
            ingredients = { 'Colossal Skull' },
        },
        ['cursed harness'] = {
            name = 'Cursed Harness',
            skill = 'Bonecraft',
            level = 100,
            subcraft = { 'Leathercraft (41)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Angel Skin', 'Coral Fragment', 'Oxblood', 'Tiger Leather x2' },
            hq1 = 'Cursed Harness -1',
        },
        ['dragon ring'] = {
            name = 'Dragon Ring',
            skill = 'Bonecraft',
            level = 100,
            crystal = 'Wind Crystal',
            ingredients = { 'Dragon Talon x2' },
            hq1 = 'Dragon Ring +1',
        },
        ['gavial mask'] = {
            name = 'Gavial Mask',
            skill = 'Bonecraft',
            level = 100,
            crystal = 'Wind Crystal',
            ingredients = { 'High-Quality Pugil Scales', 'Sheep Leather', 'Titanictus Shell' },
            hq1 = 'Gavial Mask +1',
        },
        ['khimaira jambiya'] = {
            name = 'Khimaira Jambiya',
            skill = 'Bonecraft',
            level = 100,
            subcraft = { 'Goldsmithing (40)', 'Smithing (39)' },
            crystal = 'Fire Crystal',
            ingredients = { 'Gold Ingot', 'Khimaira Horn', 'Mercury', 'Star Sapphire', 'Steel Ingot' },
            hq1 = 'Amir Jambiya',
        },
        ['dragon harness'] = {
            name = 'Dragon Harness',
            skill = 'Bonecraft',
            level = 101,
            subcraft = { 'Leathercraft (51)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Buffalo Leather x2', 'Dragon Bone', 'Wyrm Horn' },
            hq1 = 'Dragon Harness +1',
        },
        ['hades sainti'] = {
            name = 'Hades Sainti',
            skill = 'Bonecraft',
            level = 101,
            subcraft = { 'Smithing (37)', 'Woodworking (49)' },
            crystal = 'Wind Crystal',
            ingredients = { 'Bloodwood Lumber', 'Cerberus Claw x2', 'Iron Ingot x2' },
            hq1 = 'Hades Sainti +1',
        },
        ['unicorn harness'] = {
            name = 'Unicorn Harness',
            skill = 'Bonecraft',
            level = 102,
            subcraft = { 'Leathercraft (60)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Behemoth Leather', 'Gold Thread', 'Tiger Leather', 'Unicorn Horn x2' },
            hq1 = 'Unicorn Harness +1',
        },
        ['gavial mail'] = {
            name = 'Gavial Mail',
            skill = 'Bonecraft',
            level = 103,
            subcraft = { 'Leathercraft (27)' },
            crystal = 'Earth Crystal',
            ingredients = { 'High-Quality Pugil Scales x2', 'Leather Vest', 'Rainbow Thread', 'Sheep Leather', 'Titanictus Shell x2' },
            hq1 = 'Gavial Mail +1',
        },

    }
}

return bonecraft