local cooking = {
    by_name = {
        -- Amateur (1-10)
        ['roasted corn'] = {
            name = 'Roasted Corn',
            skill = 'Cooking',
            level = 2,
            crystal = 'Fire Crystal',
            ingredients = { 'Millioncorn' },
            hq1 = 'Grilled Corn',
        },
        ['carrot broth'] = {
            name = 'Carrot Broth',
            skill = 'Cooking',
            level = 3,
            crystal = 'Water Crystal',
            ingredients = { 'San d\'Orian Carrot x4' },
            hq1 = 'Famous Carrot Broth',
        },
        ['honeyed egg'] = {
            name = 'Honeyed Egg',
            skill = 'Cooking',
            level = 3,
            crystal = 'Water Crystal',
            ingredients = { 'Bird Egg', 'Honey' },
        },
        ['peeled crayfish'] = {
            name = 'Peeled Crayfish',
            skill = 'Cooking',
            level = 3,
            crystal = 'Wind Crystal',
            ingredients = { 'Crayfish' },
        },
        ['salted hare'] = {
            name = 'Salted Hare',
            skill = 'Cooking',
            level = 3,
            crystal = 'Fire Crystal',
            ingredients = { 'Hare Meat', 'Rock Salt' },
        },
        ['sweet lizard'] = {
            name = 'Sweet Lizard',
            skill = 'Cooking',
            level = 3,
            crystal = 'Fire Crystal',
            ingredients = { 'Honey', 'Lizard Tail' },
        },
        ['pebble soup'] = {
            name = 'Pebble Soup',
            skill = 'Cooking',
            level = 5,
            crystal = 'Fire Crystal',
            ingredients = { 'Distilled Water', 'Flint Stone x3' },
            hq1 = 'Wisdom Soup',
        },
        ['grilled hare'] = {
            name = 'Grilled Hare',
            skill = 'Cooking',
            level = 6,
            crystal = 'Fire Crystal',
            ingredients = { 'Dried Marjoram', 'Hare Meat' },
            hq1 = 'Grilled Black Hare',
        },
        ['hard-boiled egg'] = {
            name = 'Hard-Boiled Egg',
            skill = 'Cooking',
            level = 6,
            crystal = 'Fire Crystal',
            ingredients = { 'Bird Egg', 'Distilled Water' },
            hq1 = 'Soft-Boiled Egg',
        },
        ['herbal broth'] = {
            name = 'Herbal Broth',
            skill = 'Cooking',
            level = 7,
            crystal = 'Water Crystal',
            ingredients = { 'Beaugreens x2', 'Frost Turnip x2' },
            hq1 = 'Singing Herbal Broth',
        },
        ['peeled lobster'] = {
            name = 'Peeled Lobster',
            skill = 'Cooking',
            level = 7,
            crystal = 'Wind Crystal',
            ingredients = { 'Gold Lobster' },
        },
        ['salmon sub'] = {
            name = 'Salmon Sub',
            skill = 'Cooking',
            level = 8,
            crystal = 'Earth Crystal',
            ingredients = { 'Black Bread', 'La Theine Cabbage', 'Smoked Salmon', 'Mithran Tomato', 'Crying Mustard', 'Apple Vinegar' },
            hq1 = 'Fulm-long Salmon Sub',
        },
        ['boiled crayfish'] = {
            name = 'Boiled Crayfish',
            skill = 'Cooking',
            level = 9,
            crystal = 'Fire Crystal',
            ingredients = { 'Crayfish', 'Rock Salt', 'Distilled Water' },
            hq1 = 'Steamed Crayfish',
        },
        ['ayran'] = {
            name = 'Ayran',
            skill = 'Cooking',
            level = 10,
            crystal = 'Ice Crystal',
            ingredients = { 'Distilled Water', 'Kazham Peppers', 'Rock Salt', 'Yogurt' },
        },
        ['orange juice'] = {
            name = 'Orange Juice',
            skill = 'Cooking',
            level = 10,
            crystal = 'Water Crystal',
            ingredients = { 'Saruta Orange x4' },
        },

        -- Recruit (11-20)
        ['carrion broth'] = {
            name = 'Carrion Broth',
            skill = 'Cooking',
            level = 11,
            crystal = 'Water Crystal',
            ingredients = { 'Gelatin', 'Hare Meat x2', 'Rotten Meat' },
            hq1 = 'Cold Carrion Broth',
        },
        ['dried date'] = {
            name = 'Dried Date',
            skill = 'Cooking',
            level = 11,
            crystal = 'Ice Crystal',
            ingredients = { 'Date' },
            hq1 = 'Dried Date +1',
        },
        ['sliced sardine'] = {
            name = 'Sliced Sardine',
            skill = 'Cooking',
            level = 11,
            crystal = 'Wind Crystal',
            ingredients = { 'Bastore Sardine' },
        },
        ['honey'] = {
            name = 'Honey',
            skill = 'Cooking',
            level = 12,
            crystal = 'Wind Crystal',
            ingredients = { 'Beehive Chip x4' },
        },
        ['dried marjoram'] = {
            name = 'Dried Marjoram',
            skill = 'Cooking',
            level = 13,
            subcraft = { 'Alchemy (5)' },
            crystal = 'Ice Crystal',
            ingredients = { 'Fresh Marjoram x8' },
        },
        ['sliced cod'] = {
            name = 'Sliced Cod',
            skill = 'Cooking',
            level = 13,
            crystal = 'Wind Crystal',
            ingredients = { 'Tiger Cod' },
        },
        ['bug broth'] = {
            name = 'Bug Broth',
            skill = 'Cooking',
            level = 15,
            crystal = 'Water Crystal',
            ingredients = { 'Lugworm x2', 'Shell Bug x2' },
            hq1 = 'Quadav Bug Broth',
        },
        ['slice of bluetail'] = {
            name = 'Slice of Bluetail',
            skill = 'Cooking',
            level = 15,
            crystal = 'Wind Crystal',
            ingredients = { 'Bluetail' },
        },
        ['roast mushroom'] = {
            name = 'Roast Mushroom',
            skill = 'Cooking',
            level = 16,
            crystal = 'Fire Crystal',
            ingredients = { 'Sleepshroom x2', 'Rock Salt' },
            hq1 = 'Witch Kabob',
        },
        ['roast mutton'] = {
            name = 'Roast Mutton',
            skill = 'Cooking',
            level = 17,
            crystal = 'Fire Crystal',
            ingredients = { 'Dried Marjoram', 'Giant Sheep Meat', 'Mhaura Garlic' },
            hq1 = 'Juicy Mutton',
        },
        ['slice of carp'] = {
            name = 'Slice of Carp',
            skill = 'Cooking',
            level = 17,
            crystal = 'Wind Crystal',
            ingredients = { 'Moat Carp' },
        },
        ['pea soup'] = {
            name = 'Pea Soup',
            skill = 'Cooking',
            level = 18,
            crystal = 'Fire Crystal',
            ingredients = { 'Wild Onion', 'Distilled Water', 'Blue Peas x3', 'Dried Marjoram' },
            hq1 = 'Emerald Soup',
        },
        ['roast carp'] = {
            name = 'Roast Carp',
            skill = 'Cooking',
            level = 19,
            crystal = 'Fire Crystal',
            ingredients = { 'Moat Carp', 'Rock Salt' },
            hq1 = 'Broiled Carp',
        },
        ['apple juice'] = {
            name = 'Apple Juice',
            skill = 'Cooking',
            level = 20,
            crystal = 'Water Crystal',
            ingredients = { 'Faerie Apple x4' },
        },
        ['selbina butter'] = {
            name = 'Selbina Butter',
            skill = 'Cooking',
            level = 20,
            crystal = 'Ice Crystal',
            ingredients = { 'Selbina Milk', 'Rock Salt' },
        },

        -- Initiate (21-30)
        ['roast pipira'] = {
            name = 'Roast Pipira',
            skill = 'Cooking',
            level = 21,
            crystal = 'Fire Crystal',
            ingredients = { 'Pipira', 'Rock Salt' },
            hq1 = 'Broiled Pipira',
        },
        ['soy milk'] = {
            name = 'Soy Milk',
            skill = 'Cooking',
            level = 21,
            crystal = 'Fire Crystal',
            ingredients = { 'Blue Peas x2', 'Distilled Water' },
        },
        ['baked popoto'] = {
            name = 'Baked Popoto',
            skill = 'Cooking',
            level = 22,
            crystal = 'Fire Crystal',
            ingredients = { 'Popoto', 'Selbina Butter' },
            hq1 = 'Pipin\' Hot Popoto',
        },
        ['baked apple'] = {
            name = 'Baked Apple',
            skill = 'Cooking',
            level = 23,
            crystal = 'Fire Crystal',
            ingredients = { 'Faerie Apple', 'Selbina Butter', 'Maple Sugar', 'Cinnamon' },
            hq1 = 'Sweet Baked Apple',
        },
        ['goblin chocolate'] = {
            name = 'Goblin Chocolate',
            skill = 'Cooking',
            level = 23,
            crystal = 'Dark Crystal',
            ingredients = { 'Cobalt Jellyfish', 'Honey', 'Kukuru Bean x3', 'Selbina Milk', 'Sunflower Seeds', 'Wijnruit' },
            hq1 = 'Hobgoblin Chocolate',
        },
        ['peperoncino'] = {
            name = 'Peperoncino',
            skill = 'Cooking',
            level = 23,
            crystal = 'Fire Crystal',
            ingredients = { 'Kazham Peppers', 'Mhaura Garlic', 'Olive Oil', 'Rock Salt', 'Spaghetti', 'Misareaux Parsley' },
            hq2 = 'Peperoncino +1',
        },
        ['puls'] = {
            name = 'Puls',
            skill = 'Cooking',
            level = 24,
            crystal = 'Fire Crystal',
            ingredients = { 'Honey', 'Rye Flour', 'Horo Flour', 'Distilled Water' },
            hq1 = 'Delicious Puls',
        },
        ['salsa'] = {
            name = 'Salsa',
            skill = 'Cooking',
            level = 24,
            crystal = 'Water Crystal',
            ingredients = { 'Gysahl Greens', 'Kazham Peppers', 'Mithran Tomato', 'Rock Salt', 'Wild Onion' },
        },
        ['vegetable soup'] = {
            name = 'Vegetable Soup',
            skill = 'Cooking',
            level = 25,
            crystal = 'Fire Crystal',
            ingredients = { 'La Theine Cabbage', 'Frost Turnip', 'Wild Onion', 'Eggplant', 'San d\'Orian Carrot', 'Bay Leaves', 'Rock Salt', 'Distilled Water' },
            hq1 = 'Vegetable Broth',
        },
        ['meat jerky'] = {
            name = 'Meat Jerky',
            skill = 'Cooking',
            level = 26,
            crystal = 'Ice Crystal',
            ingredients = { 'Giant Sheep Meat', 'Rock Salt', 'Dried Marjoram' },
            hq1 = 'Sheep Jerky',
        },
        ['vegetable gruel'] = {
            name = 'Vegetable Gruel',
            skill = 'Cooking',
            level = 26,
            crystal = 'Fire Crystal',
            ingredients = { 'San d\'Orian Flour', 'Chamomile', 'Frost Turnip', 'Rarab Tail', 'Beaugreens', 'Distilled Water' },
            hq1 = 'Medicinal Gruel',
        },
        ['boiled crab'] = {
            name = 'Boiled Crab',
            skill = 'Cooking',
            level = 27,
            crystal = 'Fire Crystal',
            ingredients = { 'Land Crab Meat', 'Bay Leaves', 'Rock Salt', 'Distilled Water' },
            hq1 = 'Steamed Crab',
        },
        ['meat broth'] = {
            name = 'Meat Broth',
            skill = 'Cooking',
            level = 28,
            crystal = 'Water Crystal',
            ingredients = { 'Hare Meat', 'Dhalmel Meat', 'Giant Sheep Meat', 'Gelatin' },
            hq1 = 'Warm Meat Broth',
        },
        ['pomodoro sauce'] = {
            name = 'Pomodoro Sauce',
            skill = 'Cooking',
            level = 28,
            crystal = 'Water Crystal',
            ingredients = { 'Bay Leaves', 'Black Pepper', 'Olive Oil', 'Rock Salt', 'Holy Basil', 'Wild Onion', 'Mithran Tomato', 'Misareaux Parsley' },
        },
        ['dhalmel steak'] = {
            name = 'Dhalmel Steak',
            skill = 'Cooking',
            level = 29,
            crystal = 'Fire Crystal',
            ingredients = { 'Dhalmel Meat', 'Olive Oil', 'Black Pepper' },
            hq1 = 'Wild Steak',
        },
        ['insect ball'] = {
            name = 'Insect Ball',
            skill = 'Cooking',
            level = 29,
            crystal = 'Earth Crystal',
            ingredients = { 'Millioncorn', 'Little Worm', 'Distilled Water' },
        },
        ['pet food gamma'] = {
            name = 'Pet Food Gamma',
            skill = 'Cooking',
            level = 29,
            crystal = 'Earth Crystal',
            ingredients = { 'Bird Egg', 'Dhalmel Meat', 'Distilled Water', 'Horo Flour' },
        },
        ['smoked salmon'] = {
            name = 'Smoked Salmon',
            skill = 'Cooking',
            level = 29,
            subcraft = { 'Woodworking (9)' },
            crystal = 'Fire Crystal',
            ingredients = { 'Cheval Salmon', 'Rock Salt', 'Walnut Log' },
        },
        ['pineapple juice'] = {
            name = 'Pineapple Juice',
            skill = 'Cooking',
            level = 30,
            crystal = 'Water Crystal',
            ingredients = { 'Kazham Pineapple x2' },
        },
        ['yayla corbasi'] = {
            name = 'Yayla Corbasi',
            skill = 'Cooking',
            level = 30,
            crystal = 'Fire Crystal',
            ingredients = { 'Apkallu Egg', 'Apple Mint', 'Distilled Water', 'Imperial Flour', 'Imperial Rice', 'Rock Salt', 'Selbina Butter', 'Yogurt' },
            hq1 = 'Yayla Corbasi +1',
        },

        -- Novice (31-40)
        ['rice ball'] = {
            name = 'Rice Ball',
            skill = 'Cooking',
            level = 31,
            crystal = 'Fire Crystal',
            ingredients = { 'Distilled Water', 'Pamtam Kelp', 'Rock Salt', 'Tarutaru Rice' },
            hq1 = 'Rogue Rice Ball',
        },
        ['salmon eggs'] = {
            name = 'Salmon Eggs',
            skill = 'Cooking',
            level = 31,
            crystal = 'Lightning Crystal',
            ingredients = { 'Cheval Salmon' },
        },
        ['sardine ball'] = {
            name = 'Sardine Ball',
            skill = 'Cooking',
            level = 31,
            crystal = 'Earth Crystal',
            ingredients = { 'Bastore Sardine', 'Horo Flour', 'Distilled Water' },
        },
        ['acorn cookie'] = {
            name = 'Acorn Cookie',
            skill = 'Cooking',
            level = 32,
            crystal = 'Fire Crystal',
            ingredients = { 'Crawler Egg', 'Honey', 'San d\'Orian Flour', 'Selbina Butter', 'Acorn x4' },
            hq1 = 'Wild Cookie',
        },
        ['roast trout'] = {
            name = 'Roast Trout',
            skill = 'Cooking',
            level = 32,
            crystal = 'Fire Crystal',
            ingredients = { 'Shining Trout', 'Rock Salt' },
            hq1 = 'Broiled Trout',
        },
        ['nebimonite bake'] = {
            name = 'Nebimonite Bake',
            skill = 'Cooking',
            level = 33,
            crystal = 'Fire Crystal',
            ingredients = { 'Nebimonite', 'Mhaura Garlic', 'Selbina Butter' },
            hq1 = 'Buttered Nebimonite',
        },
        ['trout ball'] = {
            name = 'Trout Ball',
            skill = 'Cooking',
            level = 33,
            crystal = 'Earth Crystal',
            ingredients = { 'Distilled Water', 'Rye Flour', 'Shining Trout' },
        },
        ['black bread'] = {
            name = 'Black Bread',
            skill = 'Cooking',
            level = 34,
            crystal = 'Fire Crystal',
            ingredients = { 'Rye Flour', 'Rock Salt', 'Distilled Water' },
            hq1 = 'Pumpernickel',
        },
        ['iron bread'] = {
            name = 'Iron Bread',
            skill = 'Cooking',
            level = 34,
            crystal = 'Fire Crystal',
            ingredients = { 'San d\'Orian Flour', 'Rock Salt', 'Distilled Water' },
            hq1 = 'Steel Bread',
        },
        ['meatball'] = {
            name = 'Meatball',
            skill = 'Cooking',
            level = 35,
            crystal = 'Earth Crystal',
            ingredients = { 'Distilled Water', 'Hare Meat', 'San d\'Orian Flour' },
        },
        ['mushroom soup'] = {
            name = 'Mushroom Soup',
            skill = 'Cooking',
            level = 35,
            crystal = 'Fire Crystal',
            ingredients = { 'Danceshroom', 'Scream Fungus', 'Coral Fungus', 'Rock Salt', 'Distilled Water' },
            hq1 = 'Witch Soup',
        },
        ['buffalo jerky'] = {
            name = 'Buffalo Jerky',
            skill = 'Cooking',
            level = 36,
            crystal = 'Ice Crystal',
            ingredients = { 'Buffalo Meat', 'Dried Marjoram', 'Rock Salt' },
            hq1 = 'Bison Jerky',
        },
        ['windurst salad'] = {
            name = 'Windurst Salad',
            skill = 'Cooking',
            level = 36,
            crystal = 'Wind Crystal',
            ingredients = { 'Rolanberry', 'La Theine Cabbage', 'San d\'Orian Carrot', 'Mithran Tomato', 'Kazham Pineapple', 'Yagudo Cherry', 'Pamamas', 'Apple Vinegar' },
            hq1 = 'Timbre Timbers Salad',
        },
        ['bloody chocolate'] = {
            name = 'Bloody Chocolate',
            skill = 'Cooking',
            level = 37,
            crystal = 'Fire Crystal',
            ingredients = { 'Flytrap Leaf', 'Kukuru Bean x4', 'Maple Sugar', 'Selbina Milk' },
            hq1 = 'Bloody Chocolate',
        },
        ['bubble chocolate'] = {
            name = 'Bubble Chocolate',
            skill = 'Cooking',
            level = 37,
            crystal = 'Fire Crystal',
            ingredients = { 'Kukuru Bean x4', 'Selbina Milk', 'Maple Sugar' },
            hq1 = 'Heart Chocolate',
        },
        ['fish broth'] = {
            name = 'Fish Broth',
            skill = 'Cooking',
            level = 37,
            crystal = 'Water Crystal',
            ingredients = { 'Bastore Sardine x4' },
            hq1 = 'Fish Oil Broth',
        },
        ['jack-o\'-lantern'] = {
            name = 'Jack-o\'-Lantern',
            skill = 'Cooking',
            level = 38,
            crystal = 'Fire Crystal',
            ingredients = { 'Ogre Pumpkin', 'Beeswax' },
        },
        ['meat mithkabob'] = {
            name = 'Meat Mithkabob',
            skill = 'Cooking',
            level = 38,
            crystal = 'Fire Crystal',
            ingredients = { 'Wild Onion', 'Cockatrice Meat', 'Kazham Peppers', 'Mhaura Garlic' },
            hq2 = 'Meat Chiefkabob',
        },
        ['balik sandvici'] = {
            name = 'Balik Sandvici',
            skill = 'Cooking',
            level = 39,
            crystal = 'Fire Crystal',
            ingredients = { 'Kitron', 'Mithran Tomato', 'Olive Oil', 'Rock Salt', 'Uskumru', 'White Bread', 'Wild Onion' },
            hq1 = 'Balik Sandvici +1',
        },
        ['cotton tofu'] = {
            name = 'Cotton Tofu',
            skill = 'Cooking',
            level = 39,
            subcraft = { 'Clothcraft (2)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Bittern', 'Cotton Cloth', 'Soy Milk' },
        },
        ['melanzane'] = {
            name = 'Melanzane',
            skill = 'Cooking',
            level = 40,
            crystal = 'Fire Crystal',
            ingredients = { 'Kazham Peppers', 'Mhaura Garlic', 'Olive Oil', 'Rock Salt', 'Spaghetti', 'Wild Onion', 'Eggplant', 'Pomodoro Sauce' },
            hq3 = 'Melanzane +1',
        },
        ['melon juice'] = {
            name = 'Melon Juice',
            skill = 'Cooking',
            level = 40,
            crystal = 'Water Crystal',
            ingredients = { 'Thundermelon', 'Watermelon' },
        },
        ['sutlac'] = {
            name = 'Sutlac',
            skill = 'Cooking',
            level = 40,
            crystal = 'Fire Crystal',
            ingredients = { 'Apkallu Egg', 'Cornstarch', 'Imperial Rice', 'Maple Sugar', 'Rock Salt', 'Selbina Milk' },
            hq1 = 'Sutlac +1',
        },

        -- Apprentice (41-50)
        ['apple vinegar'] = {
            name = 'Apple Vinegar',
            skill = 'Cooking',
            level = 41,
            crystal = 'Dark Crystal',
            ingredients = { 'Honey', 'Faerie Apple x3' },
        },
        ['salmon rice ball'] = {
            name = 'Salmon Rice Ball',
            skill = 'Cooking',
            level = 41,
            crystal = 'Fire Crystal',
            ingredients = { 'Smoked Salmon', 'Distilled Water', 'Tarutaru Rice', 'Pamtam Kelp', 'Rock Salt' },
            hq1 = 'Naval Rice Ball',
        },
        ['salmon roe'] = {
            name = 'Salmon Roe',
            skill = 'Cooking',
            level = 41,
            crystal = 'Dark Crystal',
            ingredients = { 'Rock Salt', 'Salmon Eggs' },
        },
        ['windurst taco'] = {
            name = 'Windurst Taco',
            skill = 'Cooking',
            level = 41,
            crystal = 'Fire Crystal',
            ingredients = { 'Hare Meat', 'Salsa', 'Stone Cheese', 'Tortilla x2', 'Wild Onion', 'Windurst Salad' },
            hq2 = 'Timbre Timbers Taco',
        },
        ['pie dough'] = {
            name = 'Pie Dough',
            skill = 'Cooking',
            level = 42,
            crystal = 'Water Crystal',
            ingredients = { 'Rock Salt', 'San d\'Orian Flour', 'Selbina Butter' },
        },
        ['tomato juice'] = {
            name = 'Tomato Juice',
            skill = 'Cooking',
            level = 43,
            crystal = 'Water Crystal',
            ingredients = { 'Rock Salt', 'Mithran Tomato x3' },
        },
        ['spaghetti'] = {
            name = 'Spaghetti',
            skill = 'Cooking',
            level = 44,
            crystal = 'Water Crystal',
            ingredients = { 'Rock Salt', 'Semolina' },
        },
        ['white bread'] = {
            name = 'White Bread',
            skill = 'Cooking',
            level = 44,
            crystal = 'Fire Crystal',
            ingredients = { 'Distilled Water', 'Honey', 'Rock Salt', 'San d\'Orian Flour', 'Selbina Butter' },
            hq1 = 'Pain de Neige',
        },
        ['menemen'] = {
            name = 'Menemen',
            skill = 'Cooking',
            level = 45,
            crystal = 'Fire Crystal',
            ingredients = { 'Black Pepper', 'Kazham Peppers', 'Mithran Tomato', 'Puk Egg x2', 'Rock Salt', 'Selbina Butter', 'Wild Onion' },
            hq1 = 'Menemen +1',
        },
        ['pickled herring'] = {
            name = 'Pickled Herring',
            skill = 'Cooking',
            level = 46,
            crystal = 'Ice Crystal',
            ingredients = { 'Nosteau Herring', 'Dried Marjoram', 'Rock Salt' },
            hq1 = 'Viking Herring',
        },
        ['vongole rosso'] = {
            name = 'Vongole Rosso',
            skill = 'Cooking',
            level = 46,
            crystal = 'Fire Crystal',
            ingredients = { 'Black Pepper', 'Kazham Peppers', 'Mhaura Garlic', 'Olive Oil', 'Pomodoro Sauce', 'Spaghetti', 'Vongola Clam', 'Wild Onion' },
            hq2 = 'Vongole Rosso +1',
        },
        ['cinna-cookie'] = {
            name = 'Cinna-cookie',
            skill = 'Cooking',
            level = 47,
            crystal = 'Fire Crystal',
            ingredients = { 'San d\'Orian Flour', 'Cinnamon', 'Selbina Butter', 'Lizard Egg', 'Maple Sugar', 'Distilled Water' },
            hq1 = 'Coin Cookie',
        },
        ['mont blanc'] = {
            name = 'Mont Blanc',
            skill = 'Cooking',
            level = 47,
            crystal = 'Fire Crystal',
            ingredients = { 'Bird Egg', 'Chestnut x2', 'Distilled Water', 'Maple Sugar', 'San d\'Orian Flour', 'Selbina Butter', 'Selbina Milk' },
            hq1 = 'Golden Royale',
        },
        ['apple pie'] = {
            name = 'Apple Pie',
            skill = 'Cooking',
            level = 48,
            crystal = 'Fire Crystal',
            ingredients = { 'Lizard Egg', 'Faerie Apple', 'Pie Dough', 'Maple Sugar', 'Cinnamon' },
            hq1 = 'Apple Pie +1',
        },
        ['fish mithkabob'] = {
            name = 'Fish Mithkabob',
            skill = 'Cooking',
            level = 49,
            crystal = 'Fire Crystal',
            ingredients = { 'Bastore Sardine', 'Bluetail', 'Nebimonite', 'Shall Shell x2' },
            hq2 = 'Fish Chiefkabob',
        },
        ['garlic cracker'] = {
            name = 'Garlic Cracker',
            skill = 'Cooking',
            level = 49,
            crystal = 'Fire Crystal',
            ingredients = { 'Tarutaru Rice', 'Mhaura Garlic', 'Rock Salt', 'Distilled Water' },
            hq1 = 'Garlic Cracker +1',
        },
        ['grape juice'] = {
            name = 'Grape Juice',
            skill = 'Cooking',
            level = 50,
            crystal = 'Dark Crystal',
            ingredients = { 'San d\'Orian Grape x4' },
        },

        -- Journeyman (51-60)
        ['bretzel'] = {
            name = 'Bretzel',
            skill = 'Cooking',
            level = 51,
            crystal = 'Fire Crystal',
            ingredients = { 'Distilled Water', 'Lizard Egg', 'San d\'Orian Flour', 'Selbina Butter', 'Rock Salt' },
            hq2 = 'Salty Bretzel',
        },
        ['orange au lait'] = {
            name = 'Orange au Lait',
            skill = 'Cooking',
            level = 51,
            crystal = 'Water Crystal',
            ingredients = { 'Saruta Orange x2', 'Honey', 'Selbina Milk' },
        },
        ['sis kebabi'] = {
            name = 'Sis Kebabi',
            skill = 'Cooking',
            level = 51,
            crystal = 'Fire Crystal',
            ingredients = { 'Wild Onion', 'Mithran Tomato', 'Karakul Meat', 'Mhaura Garlic', 'Black Pepper', 'Rock Salt' },
            hq1 = 'Sis Kebabi +1',
        },
        ['batagreen saute'] = {
            name = 'Batagreen Saute',
            skill = 'Cooking',
            level = 52,
            crystal = 'Fire Crystal',
            ingredients = { 'Batagreens', 'Selbina Butter' },
            hq1 = 'Vegan Saute',
        },
        ['crayfish ball'] = {
            name = 'Crayfish Ball',
            skill = 'Cooking',
            level = 52,
            crystal = 'Earth Crystal',
            ingredients = { 'Gold Lobster', 'San d\'Orian Flour', 'Distilled Water' },
        },
        ['grasshopper broth'] = {
            name = 'Grasshopper Broth',
            skill = 'Cooking',
            level = 52,
            crystal = 'Water Crystal',
            ingredients = { 'Gysahl Greens', 'King Locust', 'La Theine Cabbage', 'Mushroom Locust', 'Skull Locust x2' },
            hq1 = 'Noisy Grasshopper Broth',
        },
        ['mille-feuille'] = {
            name = 'Mille-Feuille',
            skill = 'Cooking',
            level = 52,
            crystal = 'Fire Crystal',
            ingredients = { 'Bird Egg', 'Distilled Water', 'Maple Sugar', 'Pie Dough x3', 'Rolanberry', 'Selbina Milk' },
            hq1 = 'Elysian Eclair',
        },
        ['eel kabob'] = {
            name = 'Eel Kabob',
            skill = 'Cooking',
            level = 53,
            crystal = 'Fire Crystal',
            ingredients = { 'Black Eel', 'Olive Oil' },
            hq1 = 'Broiled Eel',
        },
        ['carp sushi'] = {
            name = 'Carp Sushi',
            skill = 'Cooking',
            level = 54,
            crystal = 'Dark Crystal',
            ingredients = { 'Tarutaru Rice', 'Rock Salt', 'Moat Carp' },
            hq1 = 'Yahata Sushi',
        },
        ['icecap rolanberry'] = {
            name = 'Icecap Rolanberry',
            skill = 'Cooking',
            level = 54,
            crystal = 'Fire Crystal',
            ingredients = { 'Crawler Egg', 'Distilled Water', 'Gelatin', 'Maple Sugar', 'Rolanberry', 'Selbina Butter', 'Selbina Milk' },
            hq1 = 'Snowy Rolanberry',
        },
        ['beaugreen saute'] = {
            name = 'Beaugreen Saute',
            skill = 'Cooking',
            level = 55,
            crystal = 'Fire Crystal',
            ingredients = { 'Beaugreens', 'Selbina Butter' },
            hq1 = 'Monastic Saute',
        },
        ['orange tank'] = {
            name = 'Orange Tank',
            skill = 'Cooking',
            level = 55,
            subcraft = { 'Leathercraft (1)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Karakul Leather', 'Brass Tank', 'Orange au Lait x4' },
        },
        ['carbonara'] = {
            name = 'Carbonara',
            skill = 'Cooking',
            level = 56,
            crystal = 'Fire Crystal',
            ingredients = { 'Bird Egg', 'Black Pepper', 'Buffalo Jerky', 'Holy Basil', 'Mhaura Garlic', 'Selbina Milk', 'Spaghetti', 'Stone Cheese' },
            hq2 = 'Carbonara +1',
        },
        ['mulsum'] = {
            name = 'Mulsum',
            skill = 'Cooking',
            level = 56,
            crystal = 'Ice Crystal',
            ingredients = { 'Distilled Water', 'Grape Juice', 'Honey' },
        },
        ['pamama tart'] = {
            name = 'Pamama Tart',
            skill = 'Cooking',
            level = 56,
            crystal = 'Fire Crystal',
            ingredients = { 'Pamamas', 'Bubble Chocolate x2', 'Bird egg', 'San d\'Orian flour', 'Selbina Butter', 'Maple Sugar', 'Distilled Water' },
            hq1 = 'Opo-opo Tart',
        },
        ['chai'] = {
            name = 'Chai',
            skill = 'Cooking',
            level = 57,
            crystal = 'Fire Crystal',
            ingredients = { 'Maple Sugar', 'Imperial Tea Leaves', 'Distilled Water' },
            hq1 = 'Chai +1',
        },
        ['bataquiche'] = {
            name = 'Bataquiche',
            skill = 'Cooking',
            level = 58,
            crystal = 'Fire Crystal',
            ingredients = { 'Danceshroom', 'Selbina Milk', 'Stone Cheese', 'Batagreen Saute', 'Bird Egg', 'Pie Dough', 'Black Pepper', 'Rock Salt' },
            hq2 = 'Bataquiche +1',
        },
        ['ginger cookie'] = {
            name = 'Ginger Cookie',
            skill = 'Cooking',
            level = 58,
            crystal = 'Fire Crystal',
            ingredients = { 'San d\'Orian Flour', 'Ginger', 'Selbina Butter', 'Lizard Egg', 'Maple Sugar', 'Distilled Water' },
            hq1 = 'Wizard Cookie',
            hq2 = 'Wizard Cookie',
            hq3 = 'Wizard Cookie',
        },
        ['ic pilav'] = {
            name = 'Ic Pilav',
            skill = 'Cooking',
            level = 58,
            crystal = 'Fire Crystal',
            ingredients = { 'Black Pepper', 'Buburimu Grape', 'Distilled Water', 'Imperial Rice', 'Pine Nuts', 'Rock Salt', 'Selbina Butter', 'Ziz Meat' },
            hq1 = 'Ic Pilav +1',
        },
        ['mole broth'] = {
            name = 'Mole Broth',
            skill = 'Cooking',
            level = 58,
            crystal = 'Water Crystal',
            ingredients = { 'Helmet Mole', 'Loam', 'Lugworm', 'Shell Bug', 'Snapping Mole x2' },
            hq1 = 'Lively Mole Broth',
        },
        ['tentacle sushi'] = {
            name = 'Tentacle Sushi',
            skill = 'Cooking',
            level = 58,
            crystal = 'Earth Crystal',
            ingredients = { 'Ginger', 'Tarutaru Rice', 'Rice Vinegar', 'Distilled Water', 'Cone Calamary' },
            hq2 = 'Tentacle Sushi +1',
        },
        ['dried mugwort'] = {
            name = 'Dried Mugwort',
            skill = 'Cooking',
            level = 59,
            subcraft = { 'Alchemy (40)' },
            crystal = 'Ice Crystal',
            ingredients = { 'Fresh Mugwort x8' },
        },
        ['goblin mushpot'] = {
            name = 'Goblin Mushpot',
            skill = 'Cooking',
            level = 59,
            crystal = 'Fire Crystal',
            ingredients = { 'Danceshroom', 'Deathball', 'Distilled Water', 'Kazham Peppers', 'Rock Salt', 'Scream Fungus', 'Sleepshroom', 'Sobbing Fungus' },
        },
        ['pogaca'] = {
            name = 'Pogaca',
            skill = 'Cooking',
            level = 59,
            crystal = 'Fire Crystal',
            ingredients = { 'San d\'Orian Flour', 'Selbina Butter', 'Maple Sugar', 'Rock Salt', 'Stone Cheese', 'Distilled Water', 'Apkallu Egg', 'Yogurt' },
            hq1 = 'Pogaca +1',
        },
        ['spicy cracker'] = {
            name = 'Spicy Cracker',
            skill = 'Cooking',
            level = 59,
            crystal = 'Fire Crystal',
            ingredients = { 'Kazham Peppers', 'Tarutaru Rice', 'Rock Salt', 'Distilled Water' },
            hq1 = 'Red Hot Cracker',
        },
        ['green quiche'] = {
            name = 'Green Quiche',
            skill = 'Cooking',
            level = 60,
            crystal = 'Fire Crystal',
            ingredients = { 'Pie Dough', 'Rock Salt', 'Danceshroom', 'Selbina Milk', 'Stone Cheese', 'Bird Egg', 'Beaugreen Saute', 'Black Pepper' },
            hq2 = 'Emerald Quiche',
        },
        ['yagudo drink'] = {
            name = 'Yagudo Drink',
            skill = 'Cooking',
            level = 60,
            crystal = 'Dark Crystal',
            ingredients = { 'Yagudo Cherry', 'Buburimu Grape x3' },
        },

        -- Craftsman (61-70)
        ['goblin bread'] = {
            name = 'Goblin Bread',
            skill = 'Cooking',
            level = 61,
            crystal = 'Fire Crystal',
            ingredients = { 'Bone Chip', 'Crawler Egg', 'Distilled Water', 'Horo Flour', 'Poison Flour', 'Puffball', 'Rock Salt' },
            hq1 = 'Hobgoblin Bread',
        },
        ['seafood stewpot'] = {
            name = 'Seafood Stewpot',
            skill = 'Cooking',
            level = 61,
            crystal = 'Fire Crystal',
            ingredients = { 'Bastore Bream', 'Cibol', 'Cotton Tofu', 'Danceshroom', 'Distilled Water', 'Fish Stock', 'Gold Lobster', 'Napa' },
            hq1 = 'Prime Seafood Stewpot',
            hq2 = 'Prized Seafood Stewpot',
        },
        ['stone cheese'] = {
            name = 'Stone Cheese',
            skill = 'Cooking',
            level = 61,
            crystal = 'Dark Crystal',
            ingredients = { 'Selbina Milk', 'Rock Salt' },
            hq1 = 'Rock Cheese',
        },
        ['apple au lait'] = {
            name = 'Apple au Lait',
            skill = 'Cooking',
            level = 62,
            crystal = 'Water Crystal',
            ingredients = { 'Faerie Apple x2', 'Honey', 'Selbina Milk' },
        },
        ['melon pie'] = {
            name = 'Melon Pie',
            skill = 'Cooking',
            level = 62,
            crystal = 'Fire Crystal',
            ingredients = { 'Thundermelon', 'Cinnamon', 'Lizard Egg', 'Pie Dough', 'Maple Sugar' },
            hq1 = 'Melon Pie +1',
        },
        ['snoll gelato'] = {
            name = 'Snoll Gelato',
            skill = 'Cooking',
            level = 62,
            subcraft = { 'Alchemy (11)' },
            crystal = 'Ice Crystal',
            ingredients = { 'Bird Egg', 'Maple Sugar', 'Olive Oil', 'San d\'Orian Flour', 'Selbina Butter', 'Selbina Milk', 'Snoll Arm' },
            hq1 = 'Sub-Zero Gelato',
        },
        ['balik sis'] = {
            name = 'Balik Sis',
            skill = 'Cooking',
            level = 63,
            crystal = 'Fire Crystal',
            ingredients = { 'Black Pepper', 'Kazham Peppers', 'Kilicbaligi', 'Mhaura Garlic', 'Mithran Tomato', 'Rock Salt' },
            hq1 = 'Balik Sis +1',
        },
        ['blood broth'] = {
            name = 'Blood Broth',
            skill = 'Cooking',
            level = 63,
            crystal = 'Water Crystal',
            ingredients = { 'Beast Blood', 'Fiend Blood', 'Bird Blood', 'Leech Saliva', 'Lizard Blood' },
            hq1 = 'Clear Blood Broth',
        },
        ['sausage'] = {
            name = 'Sausage',
            skill = 'Cooking',
            level = 63,
            subcraft = { 'Woodworking (8)' },
            crystal = 'Fire Crystal',
            ingredients = { 'Black Pepper', 'Giant Sheep Meat', 'Maple Log', 'Rock Salt', 'Sage' },
        },
        ['blackened frog'] = {
            name = 'Blackened Frog',
            skill = 'Cooking',
            level = 64,
            crystal = 'Fire Crystal',
            ingredients = { 'Copper Frog', 'Dried Marjoram', 'Rock Salt' },
            hq1 = 'Frog Flambe',
        },
        ['bison steak'] = {
            name = 'Bison Steak',
            skill = 'Cooking',
            level = 65,
            crystal = 'Fire Crystal',
            ingredients = { 'Bay Leaves', 'Black Pepper', 'Olive Oil', 'Rock Salt', 'Rarab Tail', 'Buffalo Meat' },
            hq1 = 'Marbled Steak',
        },
        ['irmik helvasi'] = {
            name = 'Irmik Helvasi',
            skill = 'Cooking',
            level = 65,
            crystal = 'Fire Crystal',
            ingredients = { 'Selbina Milk', 'White Honey', 'Selbina Butter', 'Semolina', 'Pine Nuts' },
            hq1 = 'Irmik Helvasi +1',
        },
        ['pumpkin soup'] = {
            name = 'Pumpkin Soup',
            skill = 'Cooking',
            level = 65,
            crystal = 'Fire Crystal',
            ingredients = { 'Distilled Water', 'Ogre Pumpkin', 'Rock Salt', 'Sage', 'Selbina Milk' },
            hq1 = 'Jack-o\'-Soup',
        },
        ['apple tank'] = {
            name = 'Apple Tank',
            skill = 'Cooking',
            level = 66,
            subcraft = { 'Leathercraft (1)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Karakul Leather', 'Brass Tank', 'Apple au Lait x4' },
        },
        ['colored egg'] = {
            name = 'Colored Egg',
            skill = 'Cooking',
            level = 66,
            crystal = 'Fire Crystal',
            ingredients = { 'Lizard Egg', 'La Theine Cabbage', 'San d\'Orian Carrot', 'Distilled Water' },
            hq1 = 'Party Egg',
        },
        ['nero di seppia'] = {
            name = 'Nero di Seppia',
            skill = 'Cooking',
            level = 66,
            crystal = 'Fire Crystal',
            ingredients = { 'Black Pepper', 'Cone Calamary', 'Holy Basil', 'Mhaura Garlic', 'Mithran Tomato', 'Olive Oil', 'Spaghetti', 'Wild Onion' },
            hq2 = 'Nero di Seppia +1',
        },
        ['sausage roll'] = {
            name = 'Sausage Roll',
            skill = 'Cooking',
            level = 66,
            crystal = 'Fire Crystal',
            ingredients = { 'Distilled Water', 'Honey', 'Rock Salt', 'San d\'Orian Flour', 'Sausage', 'Selbina Butter' },
        },
        ['antica broth'] = {
            name = 'Antica Broth',
            skill = 'Cooking',
            level = 67,
            crystal = 'Water Crystal',
            ingredients = { 'Gelatin', 'Antican Pauldron', 'Antican Robe', 'Antican Acid' },
            hq1 = 'Fragrant Antica Broth',
        },
        ['ikra gunkan'] = {
            name = 'Ikra Gunkan',
            skill = 'Cooking',
            level = 67,
            crystal = 'Earth Crystal',
            ingredients = { 'Tarutaru Rice', 'Pamtam Kelp', 'Rice Vinegar', 'Distilled Water', 'Salmon Roe' },
            hq1 = 'Ikra Gunkan',
            hq2 = 'Ikra Gunkan +1',
        },
        ['raisin bread'] = {
            name = 'Raisin Bread',
            skill = 'Cooking',
            level = 67,
            crystal = 'Fire Crystal',
            ingredients = { 'San d\'Orian Grape', 'San d\'Orian Flour', 'Selbina Butter', 'Maple Sugar', 'Rock Salt', 'Distilled Water' },
        },
        ['herb quus'] = {
            name = 'Herb Quus',
            skill = 'Cooking',
            level = 68,
            crystal = 'Fire Crystal',
            ingredients = { 'Quus x3', 'Selbina Butter', 'Dried Marjoram', 'Bay Leaves', 'Black Pepper', 'Rock Salt' },
            hq1 = 'Medicinal Quus',
        },
        ['imperial coffee'] = {
            name = 'Imperial Coffee',
            skill = 'Cooking',
            level = 68,
            crystal = 'Fire Crystal',
            ingredients = { 'Coffee Powder', 'Maple Sugar', 'Distilled Water' },
            hq1 = '+1',
        },
        ['adamantoise soup'] = {
            name = 'Adamantoise Soup',
            skill = 'Cooking',
            level = 69,
            crystal = 'Dark Crystal',
            ingredients = { 'San d\'Orian Flour', 'Chicken Bone', 'Fiend Blood', 'Rock Salt', 'Wild Onion', 'Distilled Water', 'Tavnazian Ram Meat', 'Diatryma Meat' },
        },
        ['gateau aux fraises'] = {
            name = 'Gateau aux Fraises',
            skill = 'Cooking',
            level = 69,
            crystal = 'Fire Crystal',
            ingredients = { 'Bird Egg', 'Distilled Water', 'Maple Sugar', 'Rolanberry x2', 'San d\'Orian Flour', 'Selbina Butter', 'Selbina Milk' },
            hq1 = 'Midwinter Dream',
        },
        ['mutton tortilla'] = {
            name = 'Mutton Tortilla',
            skill = 'Cooking',
            level = 69,
            crystal = 'Fire Crystal',
            ingredients = { 'La Theine Cabbage', 'Giant Sheep Meat', 'Mithran Tomato', 'Tortilla', 'Tomato Juice', 'Stone Cheese', 'Kazham Peppers' },
            hq1 = 'Mutton Enchilada',
        },
        ['dhalmel stew'] = {
            name = 'Dhalmel Stew',
            skill = 'Cooking',
            level = 70,
            crystal = 'Fire Crystal',
            ingredients = { 'Dhalmel Meat', 'Wild Onion', 'Mithran Tomato', 'Distilled Water', 'San d\'Orian Flour', 'Popoto', 'Cinnamon', 'Rock Salt' },
            hq1 = 'Wild Stew',
        },
        ['san d\'orian tea'] = {
            name = 'San d\'Orian Tea',
            skill = 'Cooking',
            level = 70,
            crystal = 'Fire Crystal',
            ingredients = { 'Selbina Milk', 'Maple Sugar', 'Windurstian Tea Leaves', 'Sage', 'Distilled Water' },
            hq1 = 'Royal Tea',
        },
        ['squid sushi'] = {
            name = 'Squid Sushi',
            skill = 'Cooking',
            level = 70,
            crystal = 'Earth Crystal',
            ingredients = { 'Gigant Squid', 'Distilled Water', 'Ground Wasabi', 'Tarutaru Rice', 'Rice Vinegar' },
            hq1 = 'Squid Sushi +1',
        },

        -- Artisan (71-80)
        ['crab stewpot'] = {
            name = 'Crab Stewpot',
            skill = 'Cooking',
            level = 71,
            crystal = 'Fire Crystal',
            ingredients = { 'Cibol', 'Coral Fungus', 'Cotton Tofu', 'Distilled Water', 'Fish Stock', 'Land Crab Meat', 'Shungiku', 'Woozyshroom' },
            hq1 = 'Prime Crab Stewpot',
            hq2 = 'Prized Crab Stewpot',
        },
        ['eyeball soup'] = {
            name = 'Eyeball Soup',
            skill = 'Cooking',
            level = 71,
            crystal = 'Fire Crystal',
            ingredients = { 'Apple Vinegar', 'Beastman Blood', 'Distilled Water', 'Frost Turnip', 'Gelatin', 'Hecteyes Eye x3' },
            hq1 = 'Optical Soup',
        },
        ['turtle soup'] = {
            name = 'Turtle Soup',
            skill = 'Cooking',
            level = 71,
            crystal = 'Fire Crystal',
            ingredients = { 'Danceshroom', 'San d\'Orian Carrot', 'Red Terrapin', 'Ginger', 'Chicken Bone', 'Rock Salt', 'Acorn', 'Distilled Water' },
            hq1 = 'Stamina Soup',
        },
        ['boiled cockatrice'] = {
            name = 'Boiled Cockatrice',
            skill = 'Cooking',
            level = 72,
            crystal = 'Fire Crystal',
            ingredients = { 'San d\'Orian Carrot', 'Mithran Tomato', 'Cockatrice Meat', 'Coral Fungus', 'Mhaura Garlic', 'Ginger', 'Rock Salt', 'Distilled Water' },
        },
        ['bream sushi'] = {
            name = 'Bream Sushi',
            skill = 'Cooking',
            level = 72,
            crystal = 'Earth Crystal',
            ingredients = { 'Tarutaru Rice', 'Rice Vinegar', 'Distilled Water', 'Ground Wasabi', 'Bastore Bream' },
            hq2 = 'Bream Sushi +1',
        },
        ['pear au lait'] = {
            name = 'Pear au Lait',
            skill = 'Cooking',
            level = 72,
            crystal = 'Water Crystal',
            ingredients = { 'Derfland Pear x2', 'Honey', 'Selbina Milk' },
        },
        ['salmon meuniere'] = {
            name = 'Salmon Meuniere',
            skill = 'Cooking',
            level = 73,
            crystal = 'Fire Crystal',
            ingredients = { 'Cheval Salmon', 'San d\'Orian Flour', 'Selbina Butter', 'Black Pepper', 'Olive Oil', 'Rock Salt' },
            hq1 = 'Salmon Meuniere +1',
        },
        ['fish and chips'] = {
            name = 'Fish and Chips',
            skill = 'Cooking',
            level = 74,
            crystal = 'Fire Crystal',
            ingredients = { 'Apple Vinegar', 'Bird Egg', 'Movalpolos Water', 'Olive Oil', 'Popoto', 'San d\'Orian Flour', 'Blindfish' },
            hq1 = 'Friture Misareaux',
        },
        ['mushroom risotto'] = {
            name = 'Mushroom Risotto',
            skill = 'Cooking',
            level = 74,
            crystal = 'Fire Crystal',
            ingredients = { 'Distilled Water', 'Danceshroom', 'Olive Oil', 'Selbina Butter', 'Tarutaru Rice', 'Puffball', 'Black Pepper', 'Mhaura Garlic' },
            hq1 = 'Witch Risotto',
        },
        ['celerity salad'] = {
            name = 'Celerity Salad',
            skill = 'Cooking',
            level = 75,
            crystal = 'Wind Crystal',
            ingredients = { 'Gausebit Grass', 'Blue Peas', 'Cupid Worm', 'La Theine Millet', 'La Theine Cabbage', 'King Truffle', 'Shall Shell', 'Vomp Carrot' },
            hq1 = 'Tornado Salad',
        },
        ['dhalmel pie'] = {
            name = 'Dhalmel Pie',
            skill = 'Cooking',
            level = 75,
            crystal = 'Fire Crystal',
            ingredients = { 'Black Pepper', 'Coral Fungus', 'Dhalmel Meat', 'Pie Dough', 'Rock Salt', 'San d\'Orian Carrot', 'Selbina Butter', 'Wild Onion' },
            hq1 = 'Dhalmel Pie +1',
        },
        ['patlican salata'] = {
            name = 'Patlican Salata',
            skill = 'Cooking',
            level = 75,
            crystal = 'Fire Crystal',
            ingredients = { 'Eggplant x2', 'Yogurt', 'Mhaura Garlic', 'Selbina Butter', 'Black Pepper', 'Olive Oil', 'Rock Salt' },
            hq1 = 'Patlican Salata +1',
        },
        ['green curry'] = {
            name = 'Green Curry',
            skill = 'Cooking',
            level = 76,
            crystal = 'Fire Crystal',
            ingredients = { 'Blue Peas', 'Bay Leaves', 'Curry Powder', 'Holy Basil', 'Crayfish', 'Beaugreens', 'Distilled Water' },
        },
        ['pear tank'] = {
            name = 'Pear Tank',
            skill = 'Cooking',
            level = 76,
            subcraft = { 'Leathercraft (1)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Karakul Leather', 'Brass Tank', 'Pear au Lait x4' },
        },
        ['rarab meatball'] = {
            name = 'Rarab Meatball',
            skill = 'Cooking',
            level = 76,
            crystal = 'Fire Crystal',
            ingredients = { 'Hare Meat', 'Stone Cheese', 'Bird Egg', 'San d\'Orian Flour', 'Mhaura Garlic', 'Black Pepper', 'Rock Salt', 'Distilled Water' },
            hq1 = 'Bunny Ball',
        },
        ['navarin'] = {
            name = 'Navarin',
            skill = 'Cooking',
            level = 77,
            crystal = 'Fire Crystal',
            ingredients = { 'Black Pepper', 'Distilled Water', 'Giant Sheep Meat', 'Mithran Tomato', 'Olive Oil', 'Popoto', 'Rock Salt', 'Wild Onion' },
            hq1 = 'Tender Navarin',
        },
        ['sopa pez blanco'] = {
            name = 'Sopa Pez Blanco',
            skill = 'Cooking',
            level = 77,
            crystal = 'Fire Crystal',
            ingredients = { 'Black Pepper', 'Black Sole', 'Distilled Water', 'Popoto', 'Rock Salt', 'San d\'Orian Carrot', 'Selbina Milk', 'Wild Onion' },
        },
        ['tuna sushi'] = {
            name = 'Tuna Sushi',
            skill = 'Cooking',
            level = 77,
            crystal = 'Earth Crystal',
            ingredients = { 'Distilled Water', 'Ground Wasabi', 'Gugru Tuna', 'Rice Vinegar', 'Tarutaru Rice' },
            hq2 = 'Fatty Tuna Sushi',
        },
        ['whitefish stew'] = {
            name = 'Whitefish Stew',
            skill = 'Cooking',
            level = 77,
            crystal = 'Fire Crystal',
            ingredients = { 'Selbina Milk', 'Wild Onion', 'San d\'Orian Carrot', 'Bastore Bream', 'Popoto', 'Black Pepper', 'Rock Salt', 'Distilled Water' },
        },
        ['blackened newt'] = {
            name = 'Blackened Newt',
            skill = 'Cooking',
            level = 78,
            crystal = 'Fire Crystal',
            ingredients = { 'Elshimo Newt', 'Bay Leaves', 'Dried Marjoram', 'Rock Salt' },
            hq1 = 'Newt Flambe',
        },
        ['buche au chocolat'] = {
            name = 'Buche au Chocolat',
            skill = 'Cooking',
            level = 78,
            subcraft = { 'Woodworking (3)' },
            crystal = 'Fire Crystal',
            ingredients = { 'Bay Leaves', 'Bird Egg', 'Bubble Chocolate', 'Kukuru Bean', 'Maple Sugar', 'San d\'Orian Flour', 'Selbina Butter', 'Selbina Milk' },
            hq1 = 'Sylvan Excursion',
        },
        ['goblin pie'] = {
            name = 'Goblin Pie',
            skill = 'Cooking',
            level = 78,
            crystal = 'Fire Crystal',
            ingredients = { 'Black Pepper', 'Crawler Egg', 'Crayfish', 'Eggplant', 'Ginger', 'Honey', 'Pie Dough', 'Sunflower Seeds' },
            hq1 = 'Hobgoblin Pie',
        },
        ['chocomilk'] = {
            name = 'Chocomilk',
            skill = 'Cooking',
            level = 79,
            crystal = 'Fire Crystal',
            ingredients = { 'Honey', 'Selbina Milk', 'Maple Sugar', 'Kukuru Bean x4', 'Distilled Water' },
            hq1 = 'Choco-delight',
        },
        ['herb crawler eggs'] = {
            name = 'Herb Crawler Eggs',
            skill = 'Cooking',
            level = 79,
            crystal = 'Fire Crystal',
            ingredients = { 'Crawler Egg', 'Wild Onion', 'San d\'Orian Carrot', 'Distilled Water', 'Mhaura Garlic', 'Ginger', 'Maple Sugar', 'Olive Oil' },
        },
        ['orange kuchen'] = {
            name = 'Orange Kuchen',
            skill = 'Cooking',
            level = 80,
            crystal = 'Fire Crystal',
            ingredients = { 'San d\'Orian Flour', 'Selbina Butter', 'Maple Sugar', 'Saruta Orange x2', 'Bird Egg' },
            hq1 = 'Orange Kuchen +1',
        },
        ['shallops tropicale'] = {
            name = 'Shallops Tropicale',
            skill = 'Cooking',
            level = 80,
            crystal = 'Fire Crystal',
            ingredients = { 'Kazham Pineapple', 'Shall Shell x2', 'Selbina Butter', 'Bay Leaves', 'Rock Salt', 'Distilled Water' },
        },
        -- Adept (81-90)
        ['goblin drink'] = {
            name = 'Goblin Drink',
            skill = 'Cooking',
            level = 81,
            crystal = 'Water Crystal',
            ingredients = { 'La Theine Cabbage', 'Frost Turnip', 'Wild Onion', 'San d\'Orian Carrot', 'Watermelon', 'Gysahl Greens', 'Elshimo Newt', 'Distilled Water' },
        },
        ['karni yarik'] = {
            name = 'Karni Yarik',
            skill = 'Cooking',
            level = 81,
            crystal = 'Fire Crystal',
            ingredients = { 'Wild Onion', 'Eggplant', 'Mithran Tomato', 'Karakul Meat', 'Kazham Peppers', 'Black Pepper', 'Olive Oil', 'Rock Salt' },
            hq1 = 'Karni Yarik +1',
        },
        ['pamama au lait'] = {
            name = 'Pamama au Lait',
            skill = 'Cooking',
            level = 81,
            crystal = 'Water Crystal',
            ingredients = { 'Pamamas x2', 'Honey', 'Selbina Milk' },
        },
        ['shark fin soup'] = {
            name = 'Shark Fin Soup',
            skill = 'Cooking',
            level = 81,
            crystal = 'Fire Crystal',
            ingredients = { 'Bird Egg', 'Chicken Bone', 'Distilled Water', 'Ginger', 'Popoto', 'Rock Salt', 'Silver Shark', 'Sleepshroom' },
            hq1 = 'Ocean Soup',
        },
        ['tavnazian taco'] = {
            name = 'Tavnazian Taco',
            skill = 'Cooking',
            level = 81,
            crystal = 'Earth Crystal',
            ingredients = { 'Salsa', 'Tavnazian Salad', 'Tortilla x2' },
            hq2 = 'Leremieu Taco',
        },
        ['beef stewpot'] = {
            name = 'Beef Stewpot',
            skill = 'Cooking',
            level = 82,
            crystal = 'Fire Crystal',
            ingredients = { 'Bird Egg', 'Buffalo Meat', 'Cibol', 'Cotton Tofu', 'Distilled Water', 'Shungiku', 'Shirataki', 'Soy Stock' },
            hq1 = 'Prime Beef Stewpot',
            hq2 = 'Prized Beef Stewpot',
        },
        ['boiled tuna head'] = {
            name = 'Boiled Tuna Head',
            skill = 'Cooking',
            level = 82,
            crystal = 'Fire Crystal',
            ingredients = { 'Ginger', 'Maple Sugar', 'Rock Salt', 'Treant Bulb', 'Grape Juice', 'Gugru Tuna', 'Distilled Water', 'Beaugreens' },
        },
        ['emperor roe'] = {
            name = 'Emperor Roe',
            skill = 'Cooking',
            level = 82,
            crystal = 'Lightning Crystal',
            ingredients = { 'Emperor Fish' },
        },
        ['bass meuniere'] = {
            name = 'Bass Meuniere',
            skill = 'Cooking',
            level = 83,
            crystal = 'Fire Crystal',
            ingredients = { 'Saruta Orange', 'Dark Bass', 'San d\'Orian Flour', 'Selbina Butter', 'Black Pepper', 'Olive Oil', 'Rock Salt' },
            hq1 = 'Bass Meuniere +1',
        },
        ['chamomile tea'] = {
            name = 'Chamomile Tea',
            skill = 'Cooking',
            level = 83,
            crystal = 'Fire Crystal',
            ingredients = { 'Chamomile x2', 'Honey', 'Distilled Water' },
            hq1 = 'Healing Tea',
        },
        ['pescatora'] = {
            name = 'Pescatora',
            skill = 'Cooking',
            level = 83,
            crystal = 'Fire Crystal',
            ingredients = { 'Gold Lobster', 'Grimmonite', 'Mhaura Garlic', 'Pomodoro Sauce', 'Sandfish', 'Shall Shell', 'Spaghetti' },
            hq2 = 'Pescatora +1',
        },
        ['sole sushi'] = {
            name = 'Sole Sushi',
            skill = 'Cooking',
            level = 84,
            crystal = 'Earth Crystal',
            ingredients = { 'Black Sole', 'Ground Wasabi', 'Tarutaru Rice', 'Rice Vinegar', 'Distilled Water' },
            hq1 = 'Sole Sushi +1',
        },
        ['steamed catfish'] = {
            name = 'Steamed Catfish',
            skill = 'Cooking',
            level = 84,
            crystal = 'Fire Crystal',
            ingredients = { 'Grape Juice', 'Giant Catfish', 'Distilled Water', 'Gysahl Greens', 'Popoto', 'Dried Marjoram', 'Maple Sugar' },
        },
        ['pamama tank'] = {
            name = 'Pamama Tank',
            skill = 'Cooking',
            level = 85,
            subcraft = { 'Leathercraft (12)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Karakul Leather', 'Brass Tank', 'Pamama au Lait x4' },
        },
        ['pumpkin pie'] = {
            name = 'Pumpkin Pie',
            skill = 'Cooking',
            level = 85,
            crystal = 'Fire Crystal',
            ingredients = { 'Bird Egg', 'Cinnamon', 'Distilled Water', 'Maple Sugar', 'Ogre Pumpkin', 'Pie Dough', 'Selbina Butter', 'Selbina Milk' },
            hq1 = 'Pumpkin Pie +1',
        },
        ['yellow curry'] = {
            name = 'Yellow Curry',
            skill = 'Cooking',
            level = 85,
            crystal = 'Fire Crystal',
            ingredients = { 'Coeurl Meat', 'Curry Powder', 'Distilled Water', 'Popoto', 'Selbina Milk', 'Turmeric', 'Wild Onion' },
        },
        ['boscaiola'] = {
            name = 'Boscaiola',
            skill = 'Cooking',
            level = 86,
            crystal = 'Fire Crystal',
            ingredients = { 'Danceshroom', 'King Truffle', 'Mhaura Garlic', 'Olive Oil', 'Pomodoro Sauce', 'Scream Fungus', 'Spaghetti', 'Wild Onion' },
            hq2 = 'Boscaiola +1',
        },
        ['bream risotto'] = {
            name = 'Bream Risotto',
            skill = 'Cooking',
            level = 86,
            crystal = 'Fire Crystal',
            ingredients = { 'Bastore Bream', 'Distilled Water', 'Mhaura Garlic', 'Selbina Butter', 'Tarutaru Rice', 'Black Pepper', 'Olive Oil', 'Sage' },
            hq1 = 'Sea Spray Risotto',
        },
        ['marron glace'] = {
            name = 'Marron Glace',
            skill = 'Cooking',
            level = 86,
            crystal = 'Dark Crystal',
            ingredients = { 'Chestnut x2', 'Grape Juice', 'Maple Sugar' },
            hq1 = 'Bijou Glace',
        },
        ['seafood stew'] = {
            name = 'Seafood Stew',
            skill = 'Cooking',
            level = 87,
            crystal = 'Fire Crystal',
            ingredients = { 'Nebimonite', 'Gold Lobster', 'Shall Shell', 'Distilled Water', 'Gysahl Greens', 'Popoto', 'Black Pepper', 'Rock Salt' },
        },
        ['coeurl saute'] = {
            name = 'Coeurl Saute',
            skill = 'Cooking',
            level = 88,
            crystal = 'Fire Crystal',
            ingredients = { 'Honey', 'Coeurl Meat', 'Wild Onion', 'Grape Juice', 'Selbina Butter', 'Black Pepper', 'Olive Oil', 'Rock Salt' },
            hq1 = 'Royal Saute',
        },
        ['crimson jelly'] = {
            name = 'Crimson Jelly',
            skill = 'Cooking',
            level = 88,
            crystal = 'Earth Crystal',
            ingredients = { 'Maple Sugar', 'Gelatin', 'Apple Mint', 'Clot Plasma', 'San d\'Orian Grape', 'Distilled Water' },
            hq1 = 'Vermillion Jelly',
        },
        ['black pudding'] = {
            name = 'Black Pudding',
            skill = 'Cooking',
            level = 89,
            crystal = 'Fire Crystal',
            ingredients = { 'Bird Egg', 'Buburimu Grape', 'Cinnamon', 'Kitron', 'Royal Grape', 'San d\'Orian Flour', 'Saruta Orange', 'Selbina Butter' },
            hq1 = 'Dusky Indulgence',
        },
        ['royal omelette'] = {
            name = 'Royal Omelette',
            skill = 'Cooking',
            level = 89,
            crystal = 'Fire Crystal',
            ingredients = { 'King Truffle', 'Wild Onion', 'Cockatrice Meat', 'Bird Egg', 'Selbina Butter', 'Black Pepper', 'Olive Oil', 'Rock Salt' },
            hq1 = 'Imperial Omelette',
        },
        ['lebkuchen house'] = {
            name = 'Lebkuchen House',
            skill = 'Cooking',
            level = 90,
            crystal = 'Fire Crystal',
            ingredients = { 'Baking Soda', 'Bird Egg', 'Bubble Chocolate', 'Cinna-cookie', 'Distilled Water', 'Honey', 'San d\'Orian Flour', 'Selbina Butter' },
            hq1 = 'Lebkuchen Manse',
        },
        ['rolanberry pie'] = {
            name = 'Rolanberry Pie',
            skill = 'Cooking',
            level = 90,
            crystal = 'Fire Crystal',
            ingredients = { 'Bird Egg', 'Gelatin', 'Maple Sugar', 'Pie Dough', 'Rolanberry', 'San d\'Orian Flour', 'Selbina Milk' },
            hq1 = 'Rolanberry Pie +1',
        },
        ['vampire juice'] = {
            name = 'Vampire Juice',
            skill = 'Cooking',
            level = 90,
            crystal = 'Water Crystal',
            ingredients = { 'Mithran Tomato', 'Red Terrapin', 'Rolanberry', 'Faerie Apple' },
        },
        -- Veteran (91-100)
        ['persikos au lait'] = {
            name = 'Persikos au Lait',
            skill = 'Cooking',
            level = 91,
            crystal = 'Water Crystal',
            ingredients = { 'Persikos x2', 'Honey', 'Selbina Milk' },
        },
        ['salmon croute'] = {
            name = 'Salmon Croute',
            skill = 'Cooking',
            level = 91,
            crystal = 'Fire Crystal',
            ingredients = { 'Crawler Egg', 'Cheval Salmon', 'Grape Juice', 'Mhaura Garlic', 'Pie Dough', 'Sage', 'Rock Salt' },
        },
        ['flint caviar'] = {
            name = 'Flint Caviar',
            skill = 'Cooking',
            level = 92,
            crystal = 'Dark Crystal',
            ingredients = { 'Emperor Roe', 'Rock Salt' },
        },
        ['tavnazian salad'] = {
            name = 'Tavnazian Salad',
            skill = 'Cooking',
            level = 92,
            crystal = 'Wind Crystal',
            ingredients = { 'Apple Vinegar', 'Bastore Bream', 'Beaugreens', 'Flint Caviar', 'Frost Turnip', 'Grimmonite', 'Noble Lady', 'San d\'Orian Carrot' },
            hq1 = 'Leremieu Salad',
        },
        ['coeurl sub'] = {
            name = 'Coeurl Sub',
            skill = 'Cooking',
            level = 93,
            crystal = 'Earth Crystal',
            ingredients = { 'Selbina Butter', 'Crying Mustard', 'White Bread', 'La Theine Cabbage', 'Mithran Tomato', 'Coeurl Saute' },
            hq2 = 'Coeurl Sub +1',
        },
        ['dorado sushi'] = {
            name = 'Dorado Sushi',
            skill = 'Cooking',
            level = 93,
            crystal = 'Earth Crystal',
            ingredients = { 'Tarutaru Rice', 'Rice Vinegar', 'Noble Lady', 'Distilled Water', 'Ground Wasabi' },
            hq1 = 'Dorado Sushi +1',
        },
        ['flounder meuniere'] = {
            name = 'Flounder Meuniere',
            skill = 'Cooking',
            level = 93,
            crystal = 'Fire Crystal',
            ingredients = { 'Selbina Milk', 'Black Sole', 'San d\'Orian Flour', 'Selbina Butter', 'Black Pepper', 'Olive Oil', 'Rock Salt' },
            hq1 = 'Flounder Meuniere +1',
        },
        ['urchin sushi'] = {
            name = 'Urchin Sushi',
            skill = 'Cooking',
            level = 93,
            crystal = 'Earth Crystal',
            ingredients = { 'Bibiki Urchin', 'Distilled Water', 'Tarutaru Rice', 'Pamtam Kelp', 'Rice Vinegar' },
            hq1 = 'Urchin Sushi +1',
        },
        ['black curry'] = {
            name = 'Black Curry',
            skill = 'Cooking',
            level = 94,
            crystal = 'Fire Crystal',
            ingredients = { 'Nebimonite', 'Woozyshroom', 'Eggplant', 'Gugru Tuna', 'Distilled Water', 'Black Pepper', 'Curry Powder' },
        },
        ['hedgehog pie'] = {
            name = 'Hedgehog Pie',
            skill = 'Cooking',
            level = 94,
            crystal = 'Fire Crystal',
            ingredients = { 'Lizard Egg', 'King Truffle', 'San d\'Orian Carrot', 'Buffalo Meat', 'Selbina Butter', 'Pie Dough', 'Blue Peas', 'Rock Salt' },
            hq1 = 'Porcupine Pie',
        },
        ['tonosama rice ball'] = {
            name = 'Tonosama Rice Ball',
            skill = 'Cooking',
            level = 94,
            crystal = 'Fire Crystal',
            ingredients = { 'Distilled Water', 'Flint Caviar', 'Pamtam Kelp', 'Rock Salt', 'Tarutaru Rice' },
            hq1 = 'Shogun Rice Ball',
        },
        ['dragon steak'] = {
            name = 'Dragon Steak',
            skill = 'Cooking',
            level = 95,
            crystal = 'Fire Crystal',
            ingredients = { 'Bay Leaves', 'Black Pepper', 'Dragon Meat', 'Olive Oil', 'Popoto', 'Rarab Tail', 'Rock Salt', 'San d\'Orian Carrot' },
        },
        ['persikos tank'] = {
            name = 'Persikos Tank',
            skill = 'Cooking',
            level = 95,
            subcraft = { 'Leathercraft (1)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Karakul Leather', 'Brass Tank', 'Persikos au Lait x4' },
        },
        ['rice dumpling'] = {
            name = 'Rice Dumpling',
            skill = 'Cooking',
            level = 95,
            subcraft = { 'Woodworking (15)' },
            crystal = 'Fire Crystal',
            ingredients = { 'Dhalmel Meat', 'Coral Fungus', 'Maple Sugar', 'Bamboo Stick', 'Rock Salt', 'Sticky Rice', 'Distilled Water' },
        },
        ['arrabbiata'] = {
            name = 'Arrabbiata',
            skill = 'Cooking',
            level = 96,
            crystal = 'Fire Crystal',
            ingredients = { 'Dragon Meat', 'Holy Basil', 'Kazham Peppers', 'Mhaura Garlic', 'Olive Oil', 'Pomodoro Sauce', 'Rock Salt', 'Spaghetti' },
            hq2 = 'Arrabbiata +1',
        },
        ['brain stew'] = {
            name = 'Brain Stew',
            skill = 'Cooking',
            level = 96,
            crystal = 'Fire Crystal',
            ingredients = { 'Honey', 'King Truffle', 'Yellow Globe', 'San d\'Orian Flour', 'Crying Mustard', 'Apple Vinegar', 'Gelatin', 'Distilled Water' },
            hq1 = 'Sophic Stew',
        },
        ['sea bass croute'] = {
            name = 'Sea Bass Croute',
            skill = 'Cooking',
            level = 97,
            crystal = 'Fire Crystal',
            ingredients = { 'King Truffle', 'Grape Juice', 'Zafmlug Bass', 'Sage', 'Lizard Egg', 'Pie Dough', 'Mhaura Garlic', 'Rock Salt' },
        },
        ['dragon soup'] = {
            name = 'Dragon Soup',
            skill = 'Cooking',
            level = 98,
            crystal = 'Fire Crystal',
            ingredients = { 'Frost Turnip', 'Ginger', 'Black Pepper', 'Popoto', 'Mhaura Garlic', 'Wild Onion', 'Distilled Water', 'Dragon Meat' },
        },
        ['cursed beverage'] = {
            name = 'Cursed Beverage',
            skill = 'Cooking',
            level = 99,
            crystal = 'Dark Crystal',
            ingredients = { 'Distilled Water', 'Divine Sap', 'Kitron', 'Malboro Vine', 'Selbina Milk' },
        },
        ['sweet rice cake'] = {
            name = 'Sweet Rice Cake',
            skill = 'Cooking',
            level = 99,
            crystal = 'Fire Crystal',
            ingredients = { 'Distilled Water', 'Maple Sugar', 'Cinnamon', 'Sticky Rice', 'Gardenia Seed', 'Fresh Mugwort' },
        },
        ['cursed soup'] = {
            name = 'Cursed Soup',
            skill = 'Cooking',
            level = 100,
            crystal = 'Water Crystal',
            ingredients = { 'Kitron', 'Persikos', 'Royal Jelly', 'Distilled Water', 'Honey' },
        },
        ['red curry'] = {
            name = 'Red Curry',
            skill = 'Cooking',
            level = 101,
            crystal = 'Fire Crystal',
            ingredients = { 'Coriander', 'Curry Powder', 'Distilled Water', 'Dragon Meat', 'Kazham Peppers', 'Mithran Tomato', 'San d\'Orian Carrot' },
        },
    }
}

return cooking
