-- Amateur (1-10)
local leathercraft = {
    by_name = {
        ['coral cuisses'] = {
            name = 'Coral Cuisses',
            skill = 'Leathercraft',
            level = 1,
            subcraft = { 'Bonecraft (72)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Coral Fragment', 'Leather Trousers', 'Rainbow Thread' },
            hq1 = 'Coral Cuisses +1',
        },
        ['dragon cuisses'] = {
            name = 'Dragon Cuisses',
            skill = 'Leathercraft',
            level = 1,
            subcraft = { 'Bonecraft (82)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Leather Trousers', 'Silver Thread', 'Wyvern Scales x2' },
            hq1 = 'Dragon Cuisses +1',
        },
        ['gavial cuisses'] = {
            name = 'Gavial Cuisses',
            skill = 'Leathercraft',
            level = 1,
            subcraft = { 'Bonecraft (94)' },
            crystal = 'Earth Crystal',
            ingredients = { 'High-Quality Pugil Scales', 'Leather Trousers', 'Rainbow Thread', 'Titanictus Shell' },
            hq1 = 'Gavial Cuisses +1',
        },
        ['love chocolate'] = {
            name = 'Love Chocolate',
            skill = 'Leathercraft',
            level = 1,
            subcraft = { 'Clothcraft (1)', 'Cooking (1)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Heart Chocolate', 'Parchment', 'Scarlet Ribbon' },
            hq1 = 'Truelove Chocolate',
        },
        ['potion tank'] = {
            name = 'Potion Tank',
            skill = 'Leathercraft',
            level = 1,
            subcraft = { 'Alchemy (44)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Brass Tank', 'Potion x4', 'Sheep Leather' },
        },
        ['water tank'] = {
            name = 'Water Tank',
            skill = 'Leathercraft',
            level = 1,
            subcraft = { 'Alchemy (6)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Brass Tank', 'Karakul Leather', 'Water Cluster' },
        },
        ['water tank 2'] = {
            name = 'Water Tank',
            skill = 'Leathercraft',
            level = 1,
            subcraft = { 'Alchemy (6)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Brass Tank', 'Sheep Leather', 'Water Cluster' },
        },
        ['sheep leather'] = {
            name = 'Sheep Leather',
            skill = 'Leathercraft',
            level = 2,
            crystal = 'Dark Crystal',
            ingredients = { 'Distilled Water', 'Sheepskin', 'Willow Log' },
        },
        ['sheep leather 2'] = {
            name = 'Sheep Leather',
            skill = 'Leathercraft',
            level = 2,
            crystal = 'Dark Crystal',
            ingredients = { 'Distilled Water', 'Sheepskin', 'Windurstian Tea Leaves' },
        },
        ['sheep leather (tanning)'] = {
            name = 'Sheep Leather x3',
            skill = 'Leathercraft',
            level = 2,
            crystal = 'Dark Crystal',
            ingredients = { 'Distilled Water', 'Sheepskin x3', 'Tanning Vat', 'Windurstian Tea Leaves x3' },
            keyitem = 'Tanning',
        },
        ['smooth sheep leather'] = {
            name = 'Smooth Sheep Leather',
            skill = 'Leathercraft',
            level = 2,
            crystal = 'Dark Crystal',
            ingredients = { 'Distilled Water', 'Light Anima', 'Sheepskin', 'Willow Log', 'Wind Anima x2' },
            keyitem = 'Leather Purification',
        },
        ['smooth sheep leather 2'] = {
            name = 'Smooth Sheep Leather',
            skill = 'Leathercraft',
            level = 2,
            crystal = 'Dark Crystal',
            ingredients = { 'Distilled Water', 'Light Anima', 'Sheepskin', 'Wind Anima x2', 'Windurstian Tea Leaves' },
            keyitem = 'Leather Purification',
        },
        ['vivio sheep leather'] = {
            name = 'Vivio Sheep Leather',
            skill = 'Leathercraft',
            level = 2,
            crystal = 'Dark Crystal',
            ingredients = { 'Distilled Water', 'Light Anima', 'Sheepskin', 'Water Anima', 'Willow Log', 'Wind Anima' },
            keyitem = 'Leather Purification',
        },
        ['vivio sheep leather 2'] = {
            name = 'Vivio Sheep Leather',
            skill = 'Leathercraft',
            level = 2,
            crystal = 'Dark Crystal',
            ingredients = { 'Distilled Water', 'Light Anima', 'Sheepskin', 'Water Anima', 'Wind Anima', 'Windurstian Tea Leaves' },
            keyitem = 'Leather Purification',
        },
        ['bronze cap'] = {
            name = 'Bronze Cap',
            skill = 'Leathercraft',
            level = 3,
            subcraft = { 'Smithing (4)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Bronze Sheet', 'Sheep Leather x2' },
            hq1 = 'Bronze Cap +1',
        },
        ['bronze leggings'] = {
            name = 'Bronze Leggings',
            skill = 'Leathercraft',
            level = 3,
            subcraft = { 'Smithing (7)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Bronze Sheet x2', 'Sheep Leather x2' },
            hq1 = 'Bronze Leggings +1',
        },
        ['bronze mittens'] = {
            name = 'Bronze Mittens',
            skill = 'Leathercraft',
            level = 3,
            subcraft = { 'Smithing (5)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Bronze Sheet', 'Sheep Leather' },
            hq1 = 'Bronze Mittens +1',
        },
        ['bronze subligar'] = {
            name = 'Bronze Subligar',
            skill = 'Leathercraft',
            level = 3,
            subcraft = { 'Smithing (9)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Bronze Sheet', 'Grass Cloth', 'Sheep Leather' },
            hq1 = 'Bronze Subligar +1',
        },
        ['cesti'] = {
            name = 'Cesti',
            skill = 'Leathercraft',
            level = 3,
            subcraft = { 'Woodworking (1)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Ash Lumber', 'Sheep Leather x2' },
            hq1 = 'Cesti +1',
        },
        ['vagabond\'s gloves'] = {
            name = 'Vagabond\'s Gloves',
            skill = 'Leathercraft',
            level = 3,
            crystal = 'Earth Crystal',
            ingredients = { 'Cotton Cloth', 'Sheep Leather x2' },
            hq1 = 'Nomad\'s Gloves',
        },
        ['sheep wool'] = {
            name = 'Sheep Wool',
            skill = 'Leathercraft',
            level = 4,
            crystal = 'Wind Crystal',
            ingredients = { 'Sheepskin x2' },
        },
        ['bone leggings'] = {
            name = 'Bone Leggings',
            skill = 'Leathercraft',
            level = 5,
            subcraft = { 'Bonecraft (22)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Bone Chip', 'Giant Femur', 'Sheep Leather x2' },
            hq1 = 'Bone Leggings +1',
        },
        ['bone mittens'] = {
            name = 'Bone Mittens',
            skill = 'Leathercraft',
            level = 5,
            subcraft = { 'Bonecraft (20)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Bone Chip x2', 'Sheep Leather x2' },
            hq1 = 'Bone Mittens +1',
        },
        ['chain mittens'] = {
            name = 'Chain Mittens',
            skill = 'Leathercraft',
            level = 5,
            subcraft = { 'Smithing (31)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Iron Chain x2', 'Ram Leather' },
            hq1 = 'Chain Mittens +1',
        },
        ['iron cuisses'] = {
            name = 'Iron Cuisses',
            skill = 'Leathercraft',
            level = 5,
            subcraft = { 'Smithing (35)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Cotton Thread', 'Iron Scales x2', 'Leather Trousers' },
            hq1 = 'Iron Cuisses +1',
        },
        ['leather bandana'] = {
            name = 'Leather Bandana',
            skill = 'Leathercraft',
            level = 5,
            crystal = 'Wind Crystal',
            ingredients = { 'Sheep Leather' },
            hq1 = 'Leather Bandana +1',
        },
        ['scale cuisses'] = {
            name = 'Scale Cuisses',
            skill = 'Leathercraft',
            level = 5,
            subcraft = { 'Smithing (15)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Bronze Scales x2', 'Cotton Thread', 'Leather Trousers' },
            hq1 = 'Solid Cuisses',
        },
        ['steel cuisses'] = {
            name = 'Steel Cuisses',
            skill = 'Leathercraft',
            level = 5,
            subcraft = { 'Smithing (55)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Cotton Thread', 'Leather Trousers', 'Steel Scales x2' },
            hq1 = 'Steel Cuisses +1',
        },
        ['vagabond\'s boots'] = {
            name = 'Vagabond\'s Boots',
            skill = 'Leathercraft',
            level = 5,
            crystal = 'Earth Crystal',
            ingredients = { 'Bronze Scales', 'Grass Cloth', 'Sheep Leather x2' },
            hq1 = 'Nomad\'s Boots',
        },
        ['bone subligar'] = {
            name = 'Bone Subligar',
            skill = 'Leathercraft',
            level = 6,
            subcraft = { 'Bonecraft (24)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Bone Chip', 'Grass Cloth', 'Sheep Leather x2' },
            hq1 = 'Bone Subligar +1',
        },
        ['greaves'] = {
            name = 'Greaves',
            skill = 'Leathercraft',
            level = 6,
            subcraft = { 'Smithing (33)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Iron Chain', 'Iron Sheet', 'Ram Leather' },
            hq1 = 'Greaves +1',
        },
        ['leather highboots'] = {
            name = 'Leather Highboots',
            skill = 'Leathercraft',
            level = 6,
            crystal = 'Earth Crystal',
            ingredients = { 'Bronze Scales', 'Sheep Leather x3' },
            hq1 = 'Leather Highboots +1',
        },
        ['wrapped bow'] = {
            name = 'Wrapped Bow',
            skill = 'Leathercraft',
            level = 6,
            subcraft = { 'Woodworking (24)' },
            crystal = 'Wind Crystal',
            ingredients = { 'Sheep Leather', 'Wool Thread', 'Yew Lumber' },
            hq1 = 'Wrapped Bow +1',
        },
        ['bone harness'] = {
            name = 'Bone Harness',
            skill = 'Leathercraft',
            level = 7,
            subcraft = { 'Bonecraft (26)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Bone Chip', 'Giant Femur', 'Pugil Scales', 'Sheep Leather x2' },
            hq1 = 'Bone Harness +1',
        },
        ['chain hose'] = {
            name = 'Chain Hose',
            skill = 'Leathercraft',
            level = 7,
            subcraft = { 'Smithing (35)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Iron Chain x2', 'Linen Cloth', 'Ram Leather x2' },
            hq1 = 'Chain Hose +1',
        },
        ['rabbit mantle'] = {
            name = 'Rabbit Mantle',
            skill = 'Leathercraft',
            level = 7,
            crystal = 'Earth Crystal',
            ingredients = { 'Grass Thread', 'Rabbit Hide x5' },
            hq1 = 'Rabbit Mantle +1',
        },
        ['beetle leggings'] = {
            name = 'Beetle Leggings',
            skill = 'Leathercraft',
            level = 8,
            subcraft = { 'Bonecraft (32)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Beetle Jaw', 'Beetle Shell', 'Lizard Skin x2' },
            hq1 = 'Beetle Leggings +1',
        },
        ['beetle mittens'] = {
            name = 'Beetle Mittens',
            skill = 'Leathercraft',
            level = 8,
            subcraft = { 'Bonecraft (30)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Beetle Shell', 'Lizard Skin x2' },
            hq1 = 'Beetle Mittens +1',
        },
        ['leather gloves'] = {
            name = 'Leather Gloves',
            skill = 'Leathercraft',
            level = 8,
            crystal = 'Earth Crystal',
            ingredients = { 'Grass Cloth', 'Sheep Leather x2' },
            hq1 = 'Leather Gloves +1',
        },
        ['san d\'orian cesti'] = {
            name = 'San d\'orian Cesti',
            skill = 'Leathercraft',
            level = 8,
            crystal = 'Earth Crystal',
            ingredients = { 'Royal Archer\'s Cesti', 'Sheep Leather' },
            hq1 = 'Kingdom Cesti',
        },
        ['beetle harness'] = {
            name = 'Beetle Harness',
            skill = 'Leathercraft',
            level = 9,
            subcraft = { 'Bonecraft (36)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Beetle Shell x2', 'Lizard Skin x3' },
            hq1 = 'Beetle Harness +1',
        },
        ['beetle subligar'] = {
            name = 'Beetle Subligar',
            skill = 'Leathercraft',
            level = 9,
            subcraft = { 'Bonecraft (34)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Beetle Jaw', 'Cotton Cloth', 'Lizard Skin' },
            hq1 = 'Beetle Subligar +1',
        },
        ['breeches'] = {
            name = 'Breeches',
            skill = 'Leathercraft',
            level = 9,
            subcraft = { 'Goldsmithing (48)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Linen Cloth', 'Mythril Chain x2', 'Ram Leather x2' },
            hq1 = 'Breeches +1',
        },
        ['leather trousers'] = {
            name = 'Leather Trousers',
            skill = 'Leathercraft',
            level = 9,
            crystal = 'Earth Crystal',
            ingredients = { 'Grass Cloth x2', 'Sheep Leather x2' },
            hq1 = 'Leather Trousers +1',
        },
        ['padded cap'] = {
            name = 'Padded Cap',
            skill = 'Leathercraft',
            level = 9,
            subcraft = { 'Smithing (39)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Iron Sheet', 'Lizard Skin x2' },
            hq1 = 'Strong Cap',
        },
        ['trader\'s chapeau'] = {
            name = 'Trader\'s Chapeau',
            skill = 'Leathercraft',
            level = 9,
            subcraft = { 'Clothcraft (22)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Beeswax', 'Cotton Cloth', 'Red Grass Cloth x2', 'Red Grass Thread', 'Sheep Leather' },
            hq1 = 'Baron\'s Chapeau',
        },
        ['trader\'s cuffs'] = {
            name = 'Trader\'s Cuffs',
            skill = 'Leathercraft',
            level = 9,
            subcraft = { 'Clothcraft (23)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Cotton Cloth', 'Red Grass Cloth', 'Red Grass Thread', 'Sheep Leather x2' },
            hq1 = 'Baron\'s Cuffs',
        },
        ['trader\'s saio'] = {
            name = 'Trader\'s Saio',
            skill = 'Leathercraft',
            level = 9,
            subcraft = { 'Clothcraft (25)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Beeswax', 'Brass Chain', 'Cotton Cloth', 'Ram Leather', 'Red Grass Cloth x2', 'Red Grass Thread', 'Sheep Leather' },
            hq1 = 'Baron\'s Saio',
        },
        ['trader\'s slops'] = {
            name = 'Trader\'s Slops',
            skill = 'Leathercraft',
            level = 9,
            subcraft = { 'Clothcraft (24)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Cotton Cloth x2', 'Red Grass Cloth', 'Red Grass Thread', 'Sheep Leather' },
            hq1 = 'Baron\'s Slops',
        },
        ['brilliant snow'] = {
            name = 'Brilliant Snow x33',
            skill = 'Leathercraft',
            level = 10,
            subcraft = { 'Alchemy (70)' },
            crystal = 'Ice Crystal',
            ingredients = { 'Distilled Water', 'Glass Fiber', 'Holy Water', 'Rock Salt', 'Sheep Leather' },
            hq1 = 'Brilliant Snow x66',
            hq2 = 'Brilliant Snow x99',
        },
        ['iron mittens'] = {
            name = 'Iron Mittens',
            skill = 'Leathercraft',
            level = 10,
            subcraft = { 'Smithing (41)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Iron Sheet', 'Lizard Skin' },
            hq1 = 'Iron Mittens +1',
        },
        ['leather vest'] = {
            name = 'Leather Vest',
            skill = 'Leathercraft',
            level = 10,
            crystal = 'Earth Crystal',
            ingredients = { 'Lizard Skin', 'Sheep Leather x3' },
            hq1 = 'Leather Vest +1',
        },
        ['pellet belt'] = {
            name = 'Pellet Belt',
            skill = 'Leathercraft',
            level = 10,
            subcraft = { 'Smithing (21)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Igneous Rock x2', 'Leather Pouch', 'Sheep Leather' },
        },

        -- Recruit (11-20)
        ['leather pouch'] = {
            name = 'Leather Pouch',
            skill = 'Leathercraft',
            level = 11,
            subcraft = { 'Smithing (4)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Bronze Scales', 'Rabbit Hide', 'Sheep Leather x2' },
        },
        ['solea'] = {
            name = 'Solea',
            skill = 'Leathercraft',
            level = 11,
            crystal = 'Wind Crystal',
            ingredients = { 'Sheep Leather x2' },
            hq1 = 'Solea +1',
        },
        ['lizard belt'] = {
            name = 'Lizard Belt',
            skill = 'Leathercraft',
            level = 12,
            crystal = 'Wind Crystal',
            ingredients = { 'Iron Chain', 'Lizard Skin' },
            hq1 = 'Lizard Belt +1',
        },
        ['sturdy trousers'] = {
            name = 'Sturdy Trousers',
            skill = 'Leathercraft',
            level = 12,
            crystal = 'Earth Crystal',
            ingredients = { 'Lambent Earth Cell', 'Lambent Fire Cell', 'Leather Trousers' },
        },
        ['leather belt'] = {
            name = 'Leather Belt',
            skill = 'Leathercraft',
            level = 13,
            crystal = 'Wind Crystal',
            ingredients = { 'Iron Chain', 'Sheep Leather' },
            hq1 = 'Leather Belt +1',
        },
        ['fisherman\'s gloves'] = {
            name = 'Fisherman\'s Gloves',
            skill = 'Leathercraft',
            level = 14,
            crystal = 'Earth Crystal',
            ingredients = { 'Cotton Cloth', 'Lizard Skin x2' },
            hq1 = 'Angler\'s Gloves',
        },
        ['lizard mantle'] = {
            name = 'Lizard Mantle',
            skill = 'Leathercraft',
            level = 14,
            crystal = 'Earth Crystal',
            ingredients = { 'Grass Thread', 'Lizard Molt', 'Lizard Skin' },
            hq1 = 'Lizard Mantle +1',
        },
        ['lizard helm'] = {
            name = 'Lizard Helm',
            skill = 'Leathercraft',
            level = 15,
            crystal = 'Earth Crystal',
            ingredients = { 'Lizard Skin x2', 'Sheep Leather' },
            hq1 = 'Lizard Helm +1',
        },
        ['augmenting belt'] = {
            name = 'Augmenting Belt',
            skill = 'Leathercraft',
            level = 16,
            crystal = 'Wind Crystal',
            ingredients = { 'Lambent Earth Cell', 'Lambent Fire Cell', 'Leather Belt' },
        },
        ['lizard gloves'] = {
            name = 'Lizard Gloves',
            skill = 'Leathercraft',
            level = 16,
            crystal = 'Earth Crystal',
            ingredients = { 'Leather Gloves', 'Lizard Skin' },
            hq1 = 'Fine Gloves',
        },
        ['lizard cesti'] = {
            name = 'Lizard Cesti',
            skill = 'Leathercraft',
            level = 17,
            crystal = 'Earth Crystal',
            ingredients = { 'Cesti', 'Lizard Skin' },
            hq1 = 'Burning Cesti',
        },
        ['lizard ledelsens'] = {
            name = 'Lizard Ledelsens',
            skill = 'Leathercraft',
            level = 18,
            subcraft = { 'Goldsmithing (5)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Brass Sheet', 'Leather Highboots', 'Lizard Skin' },
            hq1 = 'Fine Ledelsens',
        },
        ['lizard trousers'] = {
            name = 'Lizard Trousers',
            skill = 'Leathercraft',
            level = 18,
            crystal = 'Earth Crystal',
            ingredients = { 'Leather Trousers', 'Lizard Skin x2' },
            hq1 = 'Fine Trousers',
        },
        ['lizard jerkin'] = {
            name = 'Lizard Jerkin',
            skill = 'Leathercraft',
            level = 19,
            crystal = 'Earth Crystal',
            ingredients = { 'Lizard Skin x3', 'Sheep Leather' },
            hq1 = 'Fine Jerkin',
        },
        ['wolf fur'] = {
            name = 'Wolf Fur',
            skill = 'Leathercraft',
            level = 19,
            crystal = 'Wind Crystal',
            ingredients = { 'Wolf Hide x3' },
        },
        ['fisherman\'s boots'] = {
            name = 'Fisherman\'s Boots',
            skill = 'Leathercraft',
            level = 20,
            crystal = 'Earth Crystal',
            ingredients = { 'Bronze Scales', 'Grass Cloth', 'Lizard Skin x2' },
            hq1 = 'Angler\'s Boots',
        },
        ['little worm belt'] = {
            name = 'Little Worm Belt',
            skill = 'Leathercraft',
            level = 20,
            crystal = 'Earth Crystal',
            ingredients = { 'Animal Glue', 'Leather Pouch', 'Sheep Leather', 'Worm Mulch' },
        },
        ['lugworm belt'] = {
            name = 'Lugworm Belt',
            skill = 'Leathercraft',
            level = 20,
            crystal = 'Earth Crystal',
            ingredients = { 'Animal Glue', 'Leather Pouch', 'Lugworm Sand', 'Sheep Leather' },
        },
        ['smash cesti'] = {
            name = 'Smash Cesti',
            skill = 'Leathercraft',
            level = 20,
            crystal = 'Earth Crystal',
            ingredients = { 'Lambent Earth Cell', 'Lambent Wind Cell', 'Lizard Cesti' },
        },

        -- Initiate (21-30)
        ['dhalmel leather'] = {
            name = 'Dhalmel Leather',
            skill = 'Leathercraft',
            level = 21,
            crystal = 'Dark Crystal',
            ingredients = { 'Dhalmel Hide', 'Distilled Water', 'Windurstian Tea Leaves' },
        },
        ['dhalmel leather 2'] = {
            name = 'Dhalmel Leather',
            skill = 'Leathercraft',
            level = 21,
            crystal = 'Dark Crystal',
            ingredients = { 'Dhalmel Hide', 'Distilled Water', 'Willow Log' },
        },
        ['dhalmel leather (tanning)'] = {
            name = 'Dhalmel Leather x3',
            skill = 'Leathercraft',
            level = 21,
            crystal = 'Dark Crystal',
            ingredients = { 'Dhalmel Hide x3', 'Distilled Water', 'Tanning Vat', 'Windurstian Tea Leaves x3' },
            keyitem = 'Tanning',
        },
        ['leather ring'] = {
            name = 'Leather Ring',
            skill = 'Leathercraft',
            level = 22,
            crystal = 'Wind Crystal',
            ingredients = { 'Dhalmel Leather' },
            hq1 = 'Armored Ring',
        },
        ['studded bandana'] = {
            name = 'Studded Bandana',
            skill = 'Leathercraft',
            level = 24,
            crystal = 'Earth Crystal',
            ingredients = { 'Iron Chain', 'Leather Bandana' },
            hq1 = 'Strong Bandana',
        },
        ['warrior\'s belt'] = {
            name = 'Warrior\'s Belt',
            skill = 'Leathercraft',
            level = 25,
            crystal = 'Wind Crystal',
            ingredients = { 'Dhalmel Leather', 'Iron Chain' },
            hq1 = 'Warrior\'s Belt +1',
        },
        ['studded gloves'] = {
            name = 'Studded Gloves',
            skill = 'Leathercraft',
            level = 26,
            crystal = 'Earth Crystal',
            ingredients = { 'Dhalmel Leather', 'Iron Chain', 'Leather Gloves' },
            hq1 = 'Strong Gloves',
        },
        ['studded boots'] = {
            name = 'Studded Boots',
            skill = 'Leathercraft',
            level = 28,
            crystal = 'Earth Crystal',
            ingredients = { 'Dhalmel Leather', 'Iron Chain', 'Leather Boots' },
            hq1 = 'Strong Boots',
        },
        ['sandals'] = {
            name = 'Sandals',
            skill = 'Leathercraft',
            level = 29,
            crystal = 'Wind Crystal',
            ingredients = { 'Dhalmel Leather', 'Sheep Leather' },
            hq1 = 'Mage\'s Sandals',
        },
        ['san d\'orian bandana'] = {
            name = 'San d\'orian Bandana',
            skill = 'Leathercraft',
            level = 29,
            crystal = 'Earth Crystal',
            ingredients = { 'Royal Footman\'s Bandana', 'Sheep Leather' },
            hq1 = 'Kingdom Bandana',
        },
        ['studded trousers'] = {
            name = 'Studded Trousers',
            skill = 'Leathercraft',
            level = 30,
            crystal = 'Earth Crystal',
            ingredients = { 'Dhalmel Leather', 'Iron Chain', 'Leather Trousers' },
            hq1 = 'Strong Trousers',
        },

        -- Novice (31-40)
        ['parchment'] = {
            name = 'Parchment',
            skill = 'Leathercraft',
            level = 31,
            crystal = 'Dark Crystal',
            ingredients = { 'Rolanberry', 'Sheep Leather' },
        },
        ['san d\'orian gloves'] = {
            name = 'San d\'orian Gloves',
            skill = 'Leathercraft',
            level = 31,
            crystal = 'Earth Crystal',
            ingredients = { 'Royal Footman\'s Gloves', 'Sheep Leather' },
            hq1 = 'Kingdom Gloves',
        },
        ['studded vest'] = {
            name = 'Studded Vest',
            skill = 'Leathercraft',
            level = 32,
            crystal = 'Earth Crystal',
            ingredients = { 'Dhalmel Leather', 'Iron Chain', 'Leather Vest', 'Ram Leather' },
            hq1 = 'Strong Vest',
        },
        ['field gloves'] = {
            name = 'Field Gloves',
            skill = 'Leathercraft',
            level = 33,
            crystal = 'Earth Crystal',
            ingredients = { 'Cotton Cloth', 'Dhalmel Leather', 'Ram Leather' },
            hq1 = 'Worker Gloves',
        },
        ['san d\'orian boots'] = {
            name = 'San d\'orian Boots',
            skill = 'Leathercraft',
            level = 33,
            crystal = 'Earth Crystal',
            ingredients = { 'Royal Footman\'s Boots', 'Sheep Leather' },
            hq1 = 'Kingdom Boots',
        },
        ['wolf mantle'] = {
            name = 'Wolf Mantle',
            skill = 'Leathercraft',
            level = 33,
            crystal = 'Ice Crystal',
            ingredients = { 'Wolf Hide', 'Wool Thread' },
            hq1 = 'Wolf Mantle +1',
        },
        ['shoes'] = {
            name = 'Shoes',
            skill = 'Leathercraft',
            level = 34,
            subcraft = { 'Clothcraft (8)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Cotton Cloth', 'Dhalmel Leather x2' },
            hq1 = 'Shoes +1',
        },
        ['healing vest'] = {
            name = 'Healing Vest',
            skill = 'Leathercraft',
            level = 35,
            crystal = 'Earth Crystal',
            ingredients = { 'Studded Vest', 'Vivio Sheep Leather' },
        },
        ['light ram leather'] = {
            name = 'Light Ram Leather',
            skill = 'Leathercraft',
            level = 35,
            crystal = 'Dark Crystal',
            ingredients = { 'Distilled Water', 'Ice Anima', 'Light Anima', 'Lightning Anima', 'Ram Skin', 'Windurstian Tea Leaves' },
        },
        ['ram leather'] = {
            name = 'Ram Leather',
            skill = 'Leathercraft',
            level = 35,
            crystal = 'Dark Crystal',
            ingredients = { 'Distilled Water', 'Ram Skin', 'Windurstian Tea Leaves' },
        },
        ['san d\'orian trousers'] = {
            name = 'San d\'orian Trousers',
            skill = 'Leathercraft',
            level = 35,
            crystal = 'Earth Crystal',
            ingredients = { 'Royal Footman\'s Trousers', 'Sheep Leather' },
            hq1 = 'Kingdom Trousers',
        },
        ['fragrant ram skin'] = {
            name = 'Fragrant Ram Skin',
            skill = 'Leathercraft',
            level = 36,
            crystal = 'Water Crystal',
            ingredients = { 'Dark Anima', 'Earth Anima', 'Ram Skin', 'Wind Anima' },
        },
        ['invisible mantle'] = {
            name = 'Invisible Mantle',
            skill = 'Leathercraft',
            level = 36,
            crystal = 'Ice Crystal',
            ingredients = { 'Caliginous Wolf Hide', 'Wolf Mantle' },
        },
        ['garish pumps'] = {
            name = 'Garish Pumps',
            skill = 'Leathercraft',
            level = 37,
            subcraft = { 'Clothcraft (28)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Bloodthread x2', 'Scarlet Linen x2', 'Sheep Leather' },
            hq1 = 'Rubious Pumps',
        },
        ['leather gorget'] = {
            name = 'Leather Gorget',
            skill = 'Leathercraft',
            level = 37,
            crystal = 'Earth Crystal',
            ingredients = { 'Grass Thread', 'Ram Leather' },
            hq1 = 'Leather Gorget +1',
        },
        ['magic belt'] = {
            name = 'Magic Belt',
            skill = 'Leathercraft',
            level = 37,
            crystal = 'Wind Crystal',
            ingredients = { 'Mercury', 'Ram Leather', 'Toad Oil' },
            hq1 = 'Magic Belt +1',
        },
        ['san d\'orian vest'] = {
            name = 'San d\'orian Vest',
            skill = 'Leathercraft',
            level = 37,
            crystal = 'Earth Crystal',
            ingredients = { 'Royal Footman\'s Vest', 'Sheep Leather' },
            hq1 = 'Kingdom Vest',
        },
        ['cuir bandana'] = {
            name = 'Cuir Bandana',
            skill = 'Leathercraft',
            level = 38,
            crystal = 'Water Crystal',
            ingredients = { 'Beeswax', 'Leather Bandana', 'Ram Leather' },
            hq1 = 'Cuir Bandana +1',
        },
        ['combat caster\'s shoes +1'] = {
            name = 'Combat Caster\'s Shoes +1',
            skill = 'Leathercraft',
            level = 39,
            crystal = 'Earth Crystal',
            ingredients = { 'Combat Caster\'s Shoes', 'Dhalmel Leather' },
            hq1 = 'Combat Caster\'s Shoes +2',
        },
        ['laminated ram leather'] = {
            name = 'Laminated Ram Leather',
            skill = 'Leathercraft',
            level = 39,
            subcraft = { 'Alchemy (10)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Animal Glue', 'Distilled Water', 'Ram Leather' },
        },
        ['wolf gorget'] = {
            name = 'Wolf Gorget',
            skill = 'Leathercraft',
            level = 39,
            crystal = 'Earth Crystal',
            ingredients = { 'Cotton Thread', 'Wolf Hide' },
            hq1 = 'Wolf Gorget +1',
        },
        ['cuir gloves'] = {
            name = 'Cuir Gloves',
            skill = 'Leathercraft',
            level = 40,
            crystal = 'Water Crystal',
            ingredients = { 'Beeswax', 'Leather Gloves', 'Ram Leather x2' },
            hq1 = 'Cuir Gloves +1',
        },
        ['field boots'] = {
            name = 'Field Boots',
            skill = 'Leathercraft',
            level = 40,
            crystal = 'Earth Crystal',
            ingredients = { 'Bronze Scales', 'Grass Cloth', 'Ram Leather x2' },
            hq1 = 'Worker Boots',
        },
        ['mist pumps'] = {
            name = 'Mist Pumps',
            skill = 'Leathercraft',
            level = 40,
            crystal = 'Earth Crystal',
            ingredients = { 'Garish Pumps', 'Smooth Sheep Leather' },
        },

        -- Apprentice (41-50)
        ['barbarian\'s belt'] = {
            name = 'Barbarian\'s Belt',
            skill = 'Leathercraft',
            level = 41,
            crystal = 'Water Crystal',
            ingredients = { 'Beastman Blood', 'Fiend Blood', 'Leather Belt' },
            hq1 = 'Brave Belt',
        },
        ['cuir highboots'] = {
            name = 'Cuir Highboots',
            skill = 'Leathercraft',
            level = 42,
            crystal = 'Water Crystal',
            ingredients = { 'Beeswax', 'Leather Highboots', 'Ram Leather x2' },
            hq1 = 'Cuir Highboots +1',
        },
        ['waistbelt'] = {
            name = 'Waistbelt',
            skill = 'Leathercraft',
            level = 43,
            crystal = 'Wind Crystal',
            ingredients = { 'Grass Thread', 'Ram Leather x2' },
            hq1 = 'Waistbelt +1',
        },
        ['acrobat\'s belt'] = {
            name = 'Acrobat\'s Belt',
            skill = 'Leathercraft',
            level = 44,
            crystal = 'Earth Crystal',
            ingredients = { 'Barbarian\'s Belt', 'Glossy Bugard Leather' },
        },
        ['cuir trousers'] = {
            name = 'Cuir Trousers',
            skill = 'Leathercraft',
            level = 44,
            crystal = 'Water Crystal',
            ingredients = { 'Beeswax', 'Leather Trousers', 'Ram Leather x2' },
            hq1 = 'Cuir Trousers +1',
        },
        ['runner\'s belt'] = {
            name = 'Runner\'s Belt',
            skill = 'Leathercraft',
            level = 44,
            crystal = 'Earth Crystal',
            ingredients = { 'Barbarian\'s Belt', 'Soft Bugard Leather' },
        },
        ['samsonian belt'] = {
            name = 'Samsonian Belt',
            skill = 'Leathercraft',
            level = 44,
            crystal = 'Earth Crystal',
            ingredients = { 'Barbarian\'s Belt', 'Rugged Bugard Leather' },
        },
        ['tough belt'] = {
            name = 'Tough Belt',
            skill = 'Leathercraft',
            level = 44,
            crystal = 'Earth Crystal',
            ingredients = { 'Barbarian\'s Belt', 'Tough Bugard Leather' },
        },
        ['chocobo jack coat'] = {
            name = 'Chocobo Jack Coat',
            skill = 'Leathercraft',
            level = 45,
            subcraft = { 'Clothcraft (27)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Linen Cloth', 'Ram Leather x2', 'Sheep Leather', 'Wool Cloth', 'Wool Thread' },
            hq1 = 'Rider\'s Jack Coat',
        },
        ['powder boots'] = {
            name = 'Powder Boots',
            skill = 'Leathercraft',
            level = 45,
            crystal = 'Earth Crystal',
            ingredients = { 'Cuir Highboots', 'Tough Dhalmel Leather' },
        },
        ['tarasque mitts'] = {
            name = 'Tarasque Mitts',
            skill = 'Leathercraft',
            level = 45,
            subcraft = { 'Clothcraft (4)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Grass Thread x2', 'Saruta Cotton', 'Tarasque Skin x2' },
            hq1 = 'Tarasque Mitts +1',
        },
        ['cuir bouilli'] = {
            name = 'Cuir Bouilli',
            skill = 'Leathercraft',
            level = 46,
            crystal = 'Water Crystal',
            ingredients = { 'Beeswax', 'Leather Vest', 'Ram Leather x2' },
            hq1 = 'Cuir Bouilli +1',
        },
        ['haste belt'] = {
            name = 'Haste Belt',
            skill = 'Leathercraft',
            level = 46,
            crystal = 'Earth Crystal',
            ingredients = { 'Light Ram Leather', 'Waistbelt' },
        },
        ['narasimha leather'] = {
            name = 'Narasimha Leather',
            skill = 'Leathercraft',
            level = 46,
            crystal = 'Dark Crystal',
            ingredients = { 'Distilled Water', 'Narasimha Hide', 'Windurstian Tea Leaves' },
        },
        ['corsette'] = {
            name = 'Corsette',
            skill = 'Leathercraft',
            level = 48,
            crystal = 'Earth Crystal',
            ingredients = { 'Coeurl Whisker', 'Dhalmel Leather', 'Scarlet Ribbon', 'Silk Cloth', 'Waistbelt' },
            hq1 = 'Corsette +1',
        },
        ['buffalo leather'] = {
            name = 'Buffalo Leather',
            skill = 'Leathercraft',
            level = 49,
            crystal = 'Dark Crystal',
            ingredients = { 'Buffalo Hide', 'Distilled Water', 'Windurstian Tea Leaves' },
        },
        ['ram mantle'] = {
            name = 'Ram Mantle',
            skill = 'Leathercraft',
            level = 49,
            crystal = 'Ice Crystal',
            ingredients = { 'Ram Skin', 'Wool Thread' },
            hq1 = 'Ram Mantle +1',
        },
        ['narasimha\'s cesti'] = {
            name = 'Narasimha\'s Cesti',
            skill = 'Leathercraft',
            level = 50,
            crystal = 'Earth Crystal',
            ingredients = { 'Cesti', 'Narasimha Leather' },
            hq1 = 'Vishnu\'s Cesti',
        },

        -- Journeyman (51-60)
        ['leather shield'] = {
            name = 'Leather Shield',
            skill = 'Leathercraft',
            level = 51,
            crystal = 'Earth Crystal',
            ingredients = { 'Lauan Shield', 'Ram Leather', 'Raptor Skin' },
            hq1 = 'Leather Shield +1',
        },
        ['high breath mantle'] = {
            name = 'High Breath Mantle',
            skill = 'Leathercraft',
            level = 52,
            crystal = 'Ice Crystal',
            ingredients = { 'Fragrant Ram Skin', 'Ram Mantle' },
        },
        ['himantes'] = {
            name = 'Himantes',
            skill = 'Leathercraft',
            level = 52,
            crystal = 'Earth Crystal',
            ingredients = { 'Lizard Cesti', 'Raptor Skin' },
            hq1 = 'Himantes +1',
        },
        ['moblin sheep leather'] = {
            name = 'Moblin Sheep Leather',
            skill = 'Leathercraft',
            level = 52,
            crystal = 'Dark Crystal',
            ingredients = { 'Distilled Water', 'Moblin Sheepskin', 'Windurstian Tea Leaves' },
        },
        ['royal knight\'s belt +1'] = {
            name = 'Royal Knight\'s Belt +1',
            skill = 'Leathercraft',
            level = 52,
            crystal = 'Earth Crystal',
            ingredients = { 'Ram Leather', 'Royal Knight\'s Belt' },
            hq1 = 'Royal Knight\'s Belt +2',
        },
        ['laminated buffalo leather'] = {
            name = 'Laminated Buffalo Leather',
            skill = 'Leathercraft',
            level = 53,
            subcraft = { 'Alchemy (10)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Animal Glue', 'Buffalo Leather', 'Distilled Water' },
        },
        ['raptor mantle'] = {
            name = 'Raptor Mantle',
            skill = 'Leathercraft',
            level = 53,
            crystal = 'Earth Crystal',
            ingredients = { 'Grass Thread', 'Raptor Skin x2' },
            hq1 = 'Dino Mantle',
        },
        ['moblin sheep wool'] = {
            name = 'Moblin Sheep Wool',
            skill = 'Leathercraft',
            level = 54,
            crystal = 'Wind Crystal',
            ingredients = { 'Moblin Sheepskin x2' },
        },
        ['raptor trousers'] = {
            name = 'Raptor Trousers',
            skill = 'Leathercraft',
            level = 54,
            crystal = 'Earth Crystal',
            ingredients = { 'Cuir Trousers', 'Raptor Skin x2' },
            hq1 = 'Dino Trousers',
        },
        ['raptor ledelsens'] = {
            name = 'Raptor Ledelsens',
            skill = 'Leathercraft',
            level = 55,
            subcraft = { 'Goldsmithing (28)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Cuir Highboots', 'Mythril Sheet', 'Raptor Skin' },
            hq1 = 'Dino Ledelsens',
        },
        ['crow gaiters'] = {
            name = 'Crow Gaiters',
            skill = 'Leathercraft',
            level = 56,
            subcraft = { 'Clothcraft (49)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Gold Thread', 'Ram Leather', 'Sheep Leather', 'Tiger Leather', 'Velvet Cloth x3' },
            hq1 = 'Raven Gaiters',
        },
        ['raptor helm'] = {
            name = 'Raptor Helm',
            skill = 'Leathercraft',
            level = 56,
            subcraft = { 'Smithing (28)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Iron Sheet', 'Raptor Skin x2', 'Sheep Leather' },
            hq1 = 'Dino Helm',
        },
        ['royal squire\'s shield +1'] = {
            name = 'Royal Squire\'s Shield +1',
            skill = 'Leathercraft',
            level = 56,
            crystal = 'Earth Crystal',
            ingredients = { 'Ram Leather', 'Royal Squire\'s Shield' },
            hq1 = 'Royal Squire\'s Shield +2',
        },
        ['brigandine'] = {
            name = 'Brigandine',
            skill = 'Leathercraft',
            level = 57,
            subcraft = { 'Goldsmithing (50)', 'Clothcraft (48)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Brass Scales', 'Gold Sheet', 'Lizard Jerkin', 'Mythril Sheet', 'Ram Leather', 'Velvet Cloth x2' },
            hq1 = 'Brigandine +1',
        },
        ['desert boots'] = {
            name = 'Desert Boots',
            skill = 'Leathercraft',
            level = 57,
            crystal = 'Earth Crystal',
            ingredients = { 'Bronze Scales', 'Sheep Leather x2', 'Yowie Skin' },
            hq1 = 'Desert Boots +1',
        },
        ['ice trousers'] = {
            name = 'Ice Trousers',
            skill = 'Leathercraft',
            level = 57,
            crystal = 'Earth Crystal',
            ingredients = { 'Frigid Skin', 'Raptor Trousers' },
        },
        ['raptor gloves'] = {
            name = 'Raptor Gloves',
            skill = 'Leathercraft',
            level = 57,
            crystal = 'Earth Crystal',
            ingredients = { 'Cuir Gloves', 'Raptor Skin' },
            hq1 = 'Dino Gloves',
        },
        ['catoblepas leather'] = {
            name = 'Catoblepas Leather',
            skill = 'Leathercraft',
            level = 58,
            crystal = 'Dark Crystal',
            ingredients = { 'Catoblepas Hide', 'Distilled Water', 'Windurstian Tea Leaves' },
        },
        ['raptor jerkin'] = {
            name = 'Raptor Jerkin',
            skill = 'Leathercraft',
            level = 58,
            crystal = 'Earth Crystal',
            ingredients = { 'Raptor Skin x2', 'Sheep Leather' },
            hq1 = 'Dino Jerkin',
        },
        ['moccasins'] = {
            name = 'Moccasins',
            skill = 'Leathercraft',
            level = 59,
            subcraft = { 'Clothcraft (8)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Dhalmel Leather', 'Linen Cloth', 'Raptor Skin' },
            hq1 = 'Moccasins +1',
        },
        ['amemet mantle'] = {
            name = 'Amemet Mantle',
            skill = 'Leathercraft',
            level = 60,
            crystal = 'Earth Crystal',
            ingredients = { 'Amemet Skin', 'Grass Thread', 'Lizard Molt' },
            hq1 = 'Amemet Mantle +1',
        },

        -- Craftsman (61-70)
        ['smilodon leather'] = {
            name = 'Smilodon Leather',
            skill = 'Leathercraft',
            level = 61,
            crystal = 'Dark Crystal',
            ingredients = { 'Distilled Water', 'Smilodon Hide', 'Windurstian Tea Leaves' },
        },
        ['tiger leather'] = {
            name = 'Tiger Leather',
            skill = 'Leathercraft',
            level = 61,
            crystal = 'Dark Crystal',
            ingredients = { 'Distilled Water', 'Tiger Hide', 'Windurstian Tea Leaves' },
        },
        ['hard leather ring'] = {
            name = 'Hard Leather Ring',
            skill = 'Leathercraft',
            level = 62,
            crystal = 'Wind Crystal',
            ingredients = { 'Tiger Leather' },
            hq1 = 'Tiger Ring',
        },
        ['premium bag'] = {
            name = 'Premium Bag',
            skill = 'Leathercraft',
            level = 62,
            subcraft = { 'Goldsmithing (54)', 'Clothcraft (57)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Bugard Leather', 'Gold Thread', 'Moblin Sheep Leather', 'Moblin Sheep Wool', 'Platinum Ingot', 'Rainbow Cloth', 'Rainbow Thread' },
        },
        ['beak mantle'] = {
            name = 'Beak Mantle',
            skill = 'Leathercraft',
            level = 63,
            crystal = 'Earth Crystal',
            ingredients = { 'Cockatrice Skin x2', 'Grass Thread' },
            hq1 = 'Beak Mantle +1',
        },
        ['crow hose'] = {
            name = 'Crow Hose',
            skill = 'Leathercraft',
            level = 63,
            subcraft = { 'Clothcraft (46)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Gold Thread', 'Sheep Leather', 'Tiger Leather x2', 'Velvet Cloth' },
            hq1 = 'Raven Hose',
        },
        ['beak trousers'] = {
            name = 'Beak Trousers',
            skill = 'Leathercraft',
            level = 64,
            crystal = 'Earth Crystal',
            ingredients = { 'Cockatrice Skin x2', 'Cuir Trousers' },
            hq1 = 'Beak Trousers +1',
        },
        ['jaridah khud'] = {
            name = 'Jaridah Khud',
            skill = 'Leathercraft',
            level = 64,
            subcraft = { 'Clothcraft (25)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Karakul Cloth', 'Karakul Leather', 'Marid Hair', 'Marid Leather' },
            hq1 = 'Akinji Khud',
        },
        ['beak ledelsens'] = {
            name = 'Beak Ledelsens',
            skill = 'Leathercraft',
            level = 65,
            subcraft = { 'Goldsmithing (28)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Cockatrice Skin', 'Cuir Highboots', 'Mythril Sheet' },
            hq1 = 'Beak Ledelsens +1',
        },
        ['sheep chammy'] = {
            name = 'Sheep Chammy',
            skill = 'Leathercraft',
            level = 65,
            subcraft = { 'Alchemy (43)' },
            crystal = 'Dark Crystal',
            ingredients = { 'Clot Plasma', 'Distilled Water', 'Sheepskin', 'Windurstian Tea Leaves' },
        },
        ['battle boots'] = {
            name = 'Battle Boots',
            skill = 'Leathercraft',
            level = 66,
            crystal = 'Earth Crystal',
            ingredients = { 'Iron Scales', 'Ram Leather x2', 'Tiger Leather' },
            hq1 = 'Battle Boots +1',
        },
        ['jaridah peti'] = {
            name = 'Jaridah Peti',
            skill = 'Leathercraft',
            level = 66,
            subcraft = { 'Smithing (43)', 'Clothcraft (39)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Brass Chain', 'Darksteel Chain', 'Karakul Cloth', 'Karakul Leather', 'Marid Leather', 'Steel Ingot', 'Steel Sheet', 'Velvet Cloth' },
            hq1 = 'Akinji Peti',
        },
        ['beak helm'] = {
            name = 'Beak Helm',
            skill = 'Leathercraft',
            level = 67,
            subcraft = { 'Smithing (28)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Cockatrice Skin x2', 'Iron Sheet', 'Sheep Leather' },
            hq1 = 'Beak Helm +1',
        },
        ['beak gloves'] = {
            name = 'Beak Gloves',
            skill = 'Leathercraft',
            level = 68,
            crystal = 'Earth Crystal',
            ingredients = { 'Cockatrice Skin', 'Cuir Gloves' },
            hq1 = 'Beak Gloves +1',
        },
        ['hoplon'] = {
            name = 'Hoplon',
            skill = 'Leathercraft',
            level = 68,
            subcraft = { 'Woodworking (53)', 'Smithing (9)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Bronze Sheet', 'Chestnut Lumber', 'Ram Leather', 'Walnut Lumber' },
            hq1 = 'Hoplon +1',
        },
        ['beak jerkin'] = {
            name = 'Beak Jerkin',
            skill = 'Leathercraft',
            level = 69,
            crystal = 'Earth Crystal',
            ingredients = { 'Cockatrice Skin x2', 'Sheep Leather' },
            hq1 = 'Beak Jerkin +1',
        },
        ['byrnie'] = {
            name = 'Byrnie',
            skill = 'Leathercraft',
            level = 69,
            subcraft = { 'Smithing (34)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Behemoth Leather', 'Darksteel Sheet', 'Dhalmel Leather', 'Ram Leather', 'Silver Mail', 'Tiger Leather' },
            hq1 = 'Byrnie +1',
        },
        ['tabin boots'] = {
            name = 'Tabin Boots',
            skill = 'Leathercraft',
            level = 69,
            crystal = 'Earth Crystal',
            ingredients = { 'Battle Boots', 'Marid Leather' },
            hq1 = 'Tabin Boots +1',
        },
        ['behemoth leather'] = {
            name = 'Behemoth Leather',
            skill = 'Leathercraft',
            level = 70,
            crystal = 'Dark Crystal',
            ingredients = { 'Behemoth Hide', 'Distilled Water', 'Windurstian Tea Leaves' },
        },
        ['behemoth mantle'] = {
            name = 'Behemoth Mantle',
            skill = 'Leathercraft',
            level = 70,
            crystal = 'Ice Crystal',
            ingredients = { 'Behemoth Hide', 'Wool Thread' },
            hq1 = 'Behemoth Mantle +1',
        },
        ['black cotehardie'] = {
            name = 'Black Cotehardie',
            skill = 'Leathercraft',
            level = 70,
            subcraft = { 'Alchemy (46)', 'Clothcraft (41)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Beak Jerkin', 'Black Ink', 'Fiend Blood', 'Malboro Fiber', 'Mistletoe', 'Ram Leather', 'Tiger Leather', 'Velvet Robe' },
            hq1 = 'Flora Cotehardie',
        },

        -- Artisan (71-80)
        ['coeurl leather'] = {
            name = 'Coeurl Leather',
            skill = 'Leathercraft',
            level = 71,
            crystal = 'Dark Crystal',
            ingredients = { 'Coeurl Hide', 'Distilled Water', 'Windurstian Tea Leaves' },
        },
        ['lynx leather'] = {
            name = 'Lynx Leather',
            skill = 'Leathercraft',
            level = 71,
            crystal = 'Dark Crystal',
            ingredients = { 'Distilled Water', 'Lynx Hide', 'Windurstian Tea Leaves' },
        },
        ['pigaches'] = {
            name = 'Pigaches',
            skill = 'Leathercraft',
            level = 71,
            subcraft = { 'Clothcraft (35)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Gold Thread', 'Raptor Skin', 'Silk Cloth', 'Tiger Leather x2' },
            hq1 = 'Pigaches +1',
        },
        ['silken pigaches'] = {
            name = 'Silken Pigaches',
            skill = 'Leathercraft',
            level = 71,
            subcraft = { 'Clothcraft (45)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Gold Thread', 'Imperial Silk Cloth', 'Raptor Skin', 'Tiger Leather x2' },
            hq1 = 'Magi Pigaches',
        },
        ['spartan hoplon'] = {
            name = 'Spartan Hoplon',
            skill = 'Leathercraft',
            level = 71,
            crystal = 'Earth Crystal',
            ingredients = { 'Bloody Ram Leather', 'Hoplon' },
        },
        ['coeurl cesti'] = {
            name = 'Coeurl Cesti',
            skill = 'Leathercraft',
            level = 72,
            crystal = 'Earth Crystal',
            ingredients = { 'Cesti', 'Coeurl Leather' },
            hq1 = 'Torama Cesti',
        },
        ['ovinnik leather'] = {
            name = 'Ovinnik Leather',
            skill = 'Leathercraft',
            level = 72,
            crystal = 'Dark Crystal',
            ingredients = { 'Distilled Water', 'Ovinnik Hide', 'Windurstian Tea Leaves' },
        },
        ['swordbelt'] = {
            name = 'Swordbelt',
            skill = 'Leathercraft',
            level = 72,
            crystal = 'Earth Crystal',
            ingredients = { 'Iron Chain', 'Tiger Leather x2' },
            hq1 = 'Swordbelt +1',
        },
        ['battle hose'] = {
            name = 'Battle Hose',
            skill = 'Leathercraft',
            level = 73,
            subcraft = { 'Clothcraft (41)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Gold Thread', 'Tiger Leather x2', 'Velvet Cloth' },
            hq1 = 'Battle Hose +1',
        },
        ['lamia mantle'] = {
            name = 'Lamia Mantle',
            skill = 'Leathercraft',
            level = 74,
            crystal = 'Earth Crystal',
            ingredients = { 'Lamia Skin', 'Manta Skin', 'Mohbwa Thread' },
            hq1 = 'Lamia Mantle +1',
        },
        ['orc helm'] = {
            name = 'Orc Helm',
            skill = 'Leathercraft',
            level = 74,
            subcraft = { 'Smithing (31)', 'Clothcraft (22)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Black Pearl x2', 'Iron Sheet', 'Linen Thread', 'Manticore Hair x2', 'Orc Cutting', 'Wool Thread' },
        },
        ['tiger trousers'] = {
            name = 'Tiger Trousers',
            skill = 'Leathercraft',
            level = 74,
            crystal = 'Earth Crystal',
            ingredients = { 'Cuir Trousers', 'Tiger Leather x2' },
            hq1 = 'Feral Trousers',
        },
        ['goblin coif'] = {
            name = 'Goblin Coif',
            skill = 'Leathercraft',
            level = 75,
            subcraft = { 'Smithing (38)', 'Clothcraft (27)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Artificial Lens x2', 'Goblin Cutting', 'Linen Cloth', 'Moblin Thread', 'Sheep Leather', 'Steel Sheet', 'Undead Skin' },
        },
        ['tiger ledelsens'] = {
            name = 'Tiger Ledelsens',
            skill = 'Leathercraft',
            level = 75,
            subcraft = { 'Goldsmithing (28)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Cuir Highboots', 'Mythril Sheet', 'Tiger Leather' },
            hq1 = 'Feral Ledelsens',
        },
        ['tiger mantle'] = {
            name = 'Tiger Mantle',
            skill = 'Leathercraft',
            level = 75,
            crystal = 'Ice Crystal',
            ingredients = { 'Tiger Hide', 'Wool Thread' },
            hq1 = 'Feral Mantle',
        },
        ['black adargas'] = {
            name = 'Black Adargas',
            skill = 'Leathercraft',
            level = 76,
            subcraft = { 'Smithing (41)', 'Goldsmithing (44)' },
            crystal = 'Fire Crystal',
            ingredients = { 'Darksteel Ingot x2', 'Gold Ingot', 'Oak Lumber', 'Ovinnik Leather' },
            hq1 = 'Black Adargas +1',
        },
        ['marid leather'] = {
            name = 'Marid Leather',
            skill = 'Leathercraft',
            level = 76,
            crystal = 'Dark Crystal',
            ingredients = { 'Distilled Water', 'Imperial Tea Leaves', 'Marid Hide' },
        },
        ['silk pumps'] = {
            name = 'Silk Pumps',
            skill = 'Leathercraft',
            level = 76,
            subcraft = { 'Clothcraft (47)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Gold Thread x2', 'Sheep Leather', 'Silk Cloth x2' },
            hq1 = 'Silk Pumps +1',
        },
        ['tabin hose'] = {
            name = 'Tabin Hose',
            skill = 'Leathercraft',
            level = 76,
            crystal = 'Earth Crystal',
            ingredients = { 'Battle Hose', 'Marid Leather' },
            hq1 = 'Tabin Hose +1',
        },
        ['tactician magician\'s pigaches +1'] = {
            name = 'Tactician Magician\'s Pigaches +1',
            skill = 'Leathercraft',
            level = 76,
            crystal = 'Earth Crystal',
            ingredients = { 'Tactician Magician\'s Pigaches', 'Tiger Leather' },
            hq1 = 'Tactician Magician\'s Pigaches +2',
        },
        ['adargas'] = {
            name = 'Adargas',
            skill = 'Leathercraft',
            level = 77,
            subcraft = { 'Goldsmithing (46)', 'Smithing (25)' },
            crystal = 'Fire Crystal',
            ingredients = { 'Gold Ingot', 'Oak Lumber', 'Rheiyoh Leather', 'Steel Ingot x2' },
            hq1 = 'Adargas +1',
        },
        ['tiger gloves'] = {
            name = 'Tiger Gloves',
            skill = 'Leathercraft',
            level = 77,
            crystal = 'Earth Crystal',
            ingredients = { 'Cuir Gloves', 'Tiger Leather' },
            hq1 = 'Feral Gloves',
        },
        ['black mantle'] = {
            name = 'Black Mantle',
            skill = 'Leathercraft',
            level = 78,
            crystal = 'Earth Crystal',
            ingredients = { 'Tiger Leather', 'Tiger Mantle', 'Wool Thread' },
            hq1 = 'Black Mantle +1',
        },
        ['tiger helm'] = {
            name = 'Tiger Helm',
            skill = 'Leathercraft',
            level = 78,
            subcraft = { 'Smithing (41)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Darksteel Sheet', 'Sheep Leather', 'Tiger Leather x2' },
            hq1 = 'Feral Helm',
        },
        ['yellow mouton'] = {
            name = 'Yellow Mouton',
            skill = 'Leathercraft',
            level = 78,
            subcraft = { 'Alchemy (35)' },
            crystal = 'Dark Crystal',
            ingredients = { 'Distilled Water', 'Orpiment x2', 'Ram Skin', 'Windurstian Tea Leaves' },
        },
        ['coeurl gorget'] = {
            name = 'Coeurl Gorget',
            skill = 'Leathercraft',
            level = 79,
            crystal = 'Earth Crystal',
            ingredients = { 'Coeurl Hide', 'Cotton Thread' },
            hq1 = 'Torama Gorget',
        },
        ['marid mantle'] = {
            name = 'Marid Mantle',
            skill = 'Leathercraft',
            level = 79,
            crystal = 'Ice Crystal',
            ingredients = { 'Karakul Thread', 'Marid Hide' },
            hq1 = 'Marid Mantle +1',
        },
        ['tiger jerkin'] = {
            name = 'Tiger Jerkin',
            skill = 'Leathercraft',
            level = 79,
            crystal = 'Earth Crystal',
            ingredients = { 'Sheep Leather', 'Tiger Leather x2' },
            hq1 = 'Feral Jerkin',
        },
        ['blue cotehardie'] = {
            name = 'Blue Cotehardie',
            skill = 'Leathercraft',
            level = 80,
            subcraft = { 'Alchemy (46)', 'Clothcraft (41)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Beak Jerkin', 'Beetle Blood', 'Fiend Blood', 'Malboro Fiber', 'Mistletoe', 'Ram Leather', 'Tiger Leather', 'Velvet Robe' },
            hq1 = 'Blue Cotehardie +1',
        },
        ['manticore leather'] = {
            name = 'Manticore Leather',
            skill = 'Leathercraft',
            level = 80,
            crystal = 'Dark Crystal',
            ingredients = { 'Distilled Water', 'Manticore Hide', 'Windurstian Tea Leaves' },
        },

        -- Adept (81-90)
        ['marid belt'] = {
            name = 'Marid Belt',
            skill = 'Leathercraft',
            level = 81,
            crystal = 'Earth Crystal',
            ingredients = { 'Darksteel Chain', 'Marid Leather x2' },
            hq1 = 'Marid Belt +1',
        },
        ['noble\'s pumps'] = {
            name = 'Noble\'s Pumps',
            skill = 'Leathercraft',
            level = 81,
            subcraft = { 'Clothcraft (57)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Gold Thread x2', 'Rainbow Cloth', 'Tiger Leather', 'Velvet Cloth' },
            hq1 = 'Aristocrat\'s Pumps',
        },
        ['tropical punches'] = {
            name = 'Tropical Punches',
            skill = 'Leathercraft',
            level = 81,
            crystal = 'Earth Crystal',
            ingredients = { 'Fruit Punches', 'Sheep Leather' },
            hq1 = 'Tropical Punches +1',
        },
        ['wivre shield'] = {
            name = 'Wivre Shield',
            skill = 'Leathercraft',
            level = 81,
            subcraft = { 'Smithing (58)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Ash Lumber', 'Darksteel Sheet x3', 'Wivre Hide x2' },
            hq1 = 'Wivre Shield +1',
        },
        ['behemoth cesti'] = {
            name = 'Behemoth Cesti',
            skill = 'Leathercraft',
            level = 82,
            crystal = 'Earth Crystal',
            ingredients = { 'Behemoth Leather', 'Cesti' },
            hq1 = 'Behemoth Cesti +1',
        },
        ['nomad\'s mantle'] = {
            name = 'Nomad\'s Mantle',
            skill = 'Leathercraft',
            level = 82,
            crystal = 'Earth Crystal',
            ingredients = { 'Rabbit Hide', 'Traveler\'s Mantle' },
            hq1 = 'Nomad\'s Mantle +1',
        },
        ['air solea'] = {
            name = 'Air Solea',
            skill = 'Leathercraft',
            level = 83,
            crystal = 'Wind Crystal',
            ingredients = { 'Light Soleas', 'Lizard Molt' },
            hq1 = 'Air Solea +1',
        },
        ['coeurl trousers'] = {
            name = 'Coeurl Trousers',
            skill = 'Leathercraft',
            level = 83,
            crystal = 'Earth Crystal',
            ingredients = { 'Coeurl Leather x2', 'Cuir Trousers' },
            hq1 = 'Torama Trousers',
        },
        ['war beret'] = {
            name = 'War Beret',
            skill = 'Leathercraft',
            level = 83,
            subcraft = { 'Clothcraft (55)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Giant Bird Plume', 'Gold Thread', 'Tiger Leather x2' },
            hq1 = 'War Beret +1',
        },
        ['coeurl ledelsens'] = {
            name = 'Coeurl Ledelsens',
            skill = 'Leathercraft',
            level = 84,
            subcraft = { 'Goldsmithing (28)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Coeurl Leather', 'Cuir Highboots', 'Mythril Sheet' },
            hq1 = 'Torama Ledelsens',
        },
        ['empowering mantle'] = {
            name = 'Empowering Mantle',
            skill = 'Leathercraft',
            level = 84,
            crystal = 'Earth Crystal',
            ingredients = { 'Enhancing Mantle', 'Lizard Skin' },
            hq1 = 'Empowering Mantle +1',
        },
        ['ogre trousers'] = {
            name = 'Ogre Trousers',
            skill = 'Leathercraft',
            level = 84,
            crystal = 'Earth Crystal',
            ingredients = { 'Coeurl Trousers', 'Manticore Leather' },
            hq1 = 'Ogre Trousers +1',
        },
        ['wise braconi'] = {
            name = 'Wise Braconi',
            skill = 'Leathercraft',
            level = 84,
            subcraft = { 'Clothcraft (37)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Eft Skin', 'Eltoro Leather', 'Silver Thread x2', 'Velvet Cloth x2' },
            hq1 = 'Wise Braconi +1',
        },
        ['wise pigaches'] = {
            name = 'Wise Pigaches',
            skill = 'Leathercraft',
            level = 85,
            subcraft = { 'Clothcraft (34)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Eltoro Leather', 'Gold Thread', 'Sheep Leather', 'Tiger Leather', 'Velvet Cloth' },
            hq1 = 'Wise Pigaches +1',
        },
        ['coeurl mantle'] = {
            name = 'Coeurl Mantle',
            skill = 'Leathercraft',
            level = 85,
            crystal = 'Ice Crystal',
            ingredients = { 'Coeurl Hide', 'Wool Thread' },
            hq1 = 'Torama Mantle',
        },
        ['northern jerkin'] = {
            name = 'Northern Jerkin',
            skill = 'Leathercraft',
            level = 85,
            crystal = 'Earth Crystal',
            ingredients = { 'Tiger Jerkin', 'Undead Skin' },
            hq1 = 'Tundra Jerkin',
        },
        ['ogre ledelsens'] = {
            name = 'Ogre Ledelsens',
            skill = 'Leathercraft',
            level = 85,
            crystal = 'Earth Crystal',
            ingredients = { 'Coeurl Ledelsens', 'Manticore Leather' },
            hq1 = 'Ogre Ledelsens +1',
        },
        ['war boots'] = {
            name = 'War Boots',
            skill = 'Leathercraft',
            level = 85,
            crystal = 'Earth Crystal',
            ingredients = { 'Coeurl Leather', 'Gold Chain', 'Tiger Leather x2' },
            hq1 = 'War Boots +1',
        },
        ['cavalier\'s mantle'] = {
            name = 'Cavalier\'s Mantle',
            skill = 'Leathercraft',
            level = 86,
            crystal = 'Ice Crystal',
            ingredients = { 'Sentinel\'s Mantle', 'Wolf Hide' },
            hq1 = 'Cavalier\'s Mantle +1',
        },
        ['shadow bow'] = {
            name = 'Shadow Bow',
            skill = 'Leathercraft',
            level = 86,
            crystal = 'Earth Crystal',
            ingredients = { 'Assassin\'s Bow', 'Ram Leather' },
            hq1 = 'Shadow Bow +1',
        },
        ['tariqah'] = {
            name = 'Tariqah',
            skill = 'Leathercraft',
            level = 86,
            crystal = 'Earth Crystal',
            ingredients = { 'Marid Hair', 'Marid Leather', 'Tariqah -1' },
            hq1 = 'Tariqah +1',
        },
        ['coeurl mask'] = {
            name = 'Coeurl Mask',
            skill = 'Leathercraft',
            level = 87,
            crystal = 'Earth Crystal',
            ingredients = { 'Coeurl Leather x2', 'Faceguard' },
            hq1 = 'Torama Mask',
        },
        ['gaia mantle'] = {
            name = 'Gaia Mantle',
            skill = 'Leathercraft',
            level = 87,
            crystal = 'Earth Crystal',
            ingredients = { 'Cockatrice Skin', 'Earth Mantle' },
            hq1 = 'Gaia Mantle +1',
        },
        ['wivre mask'] = {
            name = 'Wivre Mask',
            skill = 'Leathercraft',
            level = 87,
            crystal = 'Wind Crystal',
            ingredients = { 'Karakul Leather', 'Wivre Hide' },
            hq1 = 'Wivre Mask +1',
        },
        ['aurora mantle'] = {
            name = 'Aurora Mantle',
            skill = 'Leathercraft',
            level = 88,
            crystal = 'Ice Crystal',
            ingredients = { 'Tiger Hide', 'Tundra Mantle' },
            hq1 = 'Aurora Mantle +1',
        },
        ['coeurl gloves'] = {
            name = 'Coeurl Gloves',
            skill = 'Leathercraft',
            level = 88,
            crystal = 'Earth Crystal',
            ingredients = { 'Coeurl Leather', 'Cuir Gloves' },
            hq1 = 'Torama Gloves',
        },
        ['ogre mask'] = {
            name = 'Ogre Mask',
            skill = 'Leathercraft',
            level = 88,
            crystal = 'Earth Crystal',
            ingredients = { 'Coeurl Mask', 'Manticore Leather' },
            hq1 = 'Ogre Mask +1',
        },
        ['wise cap'] = {
            name = 'Wise Cap',
            skill = 'Leathercraft',
            level = 88,
            subcraft = { 'Clothcraft (40)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Eltoro Leather', 'Manticore Leather', 'Silk Cloth', 'Silver Thread', 'Velvet Cloth' },
            hq1 = 'Wise Cap +1',
        },
        ['coeurl jerkin'] = {
            name = 'Coeurl Jerkin',
            skill = 'Leathercraft',
            level = 89,
            crystal = 'Earth Crystal',
            ingredients = { 'Coeurl Leather x2', 'Sheep Leather' },
            hq1 = 'Torama Jerkin',
        },
        ['ogre gloves'] = {
            name = 'Ogre Gloves',
            skill = 'Leathercraft',
            level = 89,
            crystal = 'Earth Crystal',
            ingredients = { 'Coeurl Gloves', 'Manticore Leather' },
            hq1 = 'Ogre Gloves +1',
        },
        ['winged boots'] = {
            name = 'Winged Boots',
            skill = 'Leathercraft',
            level = 89,
            crystal = 'Earth Crystal',
            ingredients = { 'Leaping Boots', 'Lizard Skin' },
            hq1 = 'Winged Boots +1',
        },
        ['wise gloves'] = {
            name = 'Wise Gloves',
            skill = 'Leathercraft',
            level = 89,
            subcraft = { 'Clothcraft (32)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Eltoro Leather', 'Leather Gloves', 'Saruta Cotton x2', 'Silver Thread', 'Velvet Cloth' },
            hq1 = 'Wise Gloves +1',
        },
        ['barone cosciales'] = {
            name = 'Barone Cosciales',
            skill = 'Leathercraft',
            level = 90,
            subcraft = { 'Clothcraft (54)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Buffalo Leather x2', 'High-Quality Bugard Skin', 'Sarcenet Cloth', 'Silk Cloth' },
            hq1 = 'Conte Cosciales',
        },
        ['chasuble'] = {
            name = 'Chasuble',
            skill = 'Leathercraft',
            level = 90,
            subcraft = { 'Clothcraft (40)', 'Goldsmithing (44)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Eft Skin', 'Eltoro Leather x2', 'Manticore Leather', 'Platinum Ingot', 'Silver Thread', 'Velvet Cloth x2' },
            hq1 = 'Chasuble +1',
        },
        ['koenigs belt'] = {
            name = 'Koenigs Belt',
            skill = 'Leathercraft',
            level = 90,
            crystal = 'Earth Crystal',
            ingredients = { 'Gold Chain', 'Manticore Leather x2' },
            hq1 = 'Kaiser Belt',
        },
        ['ogre jerkin'] = {
            name = 'Ogre Jerkin',
            skill = 'Leathercraft',
            level = 90,
            crystal = 'Earth Crystal',
            ingredients = { 'Coeurl Jerkin', 'Manticore Leather', 'Undead Skin' },
            hq1 = 'Ogre Jerkin +1',
        },
        ['sniper\'s ring'] = {
            name = 'Sniper\'s Ring',
            skill = 'Leathercraft',
            level = 90,
            crystal = 'Earth Crystal',
            ingredients = { 'Archer\'s Ring', 'Tiger Leather' },
            hq1 = 'Sniper\'s Ring +1',
        },

        -- Veteran (91-100)
        ['bison wristbands'] = {
            name = 'Bison Wristbands',
            skill = 'Leathercraft',
            level = 91,
            subcraft = { 'Clothcraft (26)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Buffalo Leather', 'Manticore Hair x2', 'Manticore Leather x2' },
            hq1 = 'Brave\'s Wristbands',
        },
        ['errant pigaches'] = {
            name = 'Errant Pigaches',
            skill = 'Leathercraft',
            level = 91,
            subcraft = { 'Clothcraft (52)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Rainbow Thread', 'Ram Leather x2', 'Undead Skin', 'Velvet Cloth' },
            hq1 = 'Mahatma Pigaches',
        },
        ['khimaira wristbands'] = {
            name = 'Khimaira Wristbands',
            skill = 'Leathercraft',
            level = 91,
            crystal = 'Earth Crystal',
            ingredients = { 'Buffalo Leather', 'Khimaira Mane x2', 'Manticore Leather x2' },
            hq1 = 'Stout Wristbands',
        },
        ['sipahi jawshan'] = {
            name = 'Sipahi Jawshan',
            skill = 'Leathercraft',
            level = 91,
            subcraft = { 'Goldsmithing (51)', 'Clothcraft (49)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Gold Chain', 'Karakul Leather', 'Marid Leather x2', 'Mythril Sheet', 'Silk Cloth', 'Steel Sheet', 'Wamoura Cloth' },
            hq1 = 'Abtal Jawshan',
        },
        ['cursed pumps'] = {
            name = 'Cursed Pumps',
            skill = 'Leathercraft',
            level = 92,
            subcraft = { 'Clothcraft (59)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Gold Thread', 'Manticore Leather', 'Rainbow Cloth', 'Siren\'s Macrame', 'Velvet Cloth' },
            hq1 = 'Cursed Pumps -1',
        },
        ['czar\'s belt'] = {
            name = 'Czar\'s Belt',
            skill = 'Leathercraft',
            level = 92,
            crystal = 'Earth Crystal',
            ingredients = { 'Koenigs Belt', 'Tough Bugard Leather' },
        },
        ['desert mantle'] = {
            name = 'Desert Mantle',
            skill = 'Leathercraft',
            level = 92,
            crystal = 'Earth Crystal',
            ingredients = { 'Grass Thread', 'Yowie Skin x2' },
            hq1 = 'Desert Mantle +1',
        },
        ['leather pot'] = {
            name = 'Leather Pot',
            skill = 'Leathercraft',
            level = 92,
            subcraft = { 'Alchemy (47)', 'Woodworking (43)' },
            crystal = 'Fire Crystal',
            ingredients = { 'Hickory Lumber', 'Karakul Leather', 'Karakul Thread', 'Kaolin x2', 'Rheiyoh Leather' },
        },
        ['maharaja\'s belt'] = {
            name = 'Maharaja\'s Belt',
            skill = 'Leathercraft',
            level = 92,
            crystal = 'Earth Crystal',
            ingredients = { 'Glossy Bugard Leather', 'Koenigs Belt' },
        },
        ['pendragon\'s belt'] = {
            name = 'Pendragon\'s Belt',
            skill = 'Leathercraft',
            level = 92,
            crystal = 'Earth Crystal',
            ingredients = { 'Koenigs Belt', 'Soft Bugard Leather' },
        },
        ['sha\'ir crackows'] = {
            name = 'Sha\'ir Crackows',
            skill = 'Leathercraft',
            level = 92,
            subcraft = { 'Goldsmithing (60)', 'Clothcraft (38)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Buffalo Leather', 'Gold Thread', 'Orichalcum Ingot', 'Tiger Leather x2', 'Velvet Cloth' },
            hq1 = 'Sheikh Crackows',
        },
        ['sultan\'s belt'] = {
            name = 'Sultan\'s Belt',
            skill = 'Leathercraft',
            level = 92,
            crystal = 'Earth Crystal',
            ingredients = { 'Koenigs Belt', 'Rugged Bugard Leather' },
        },
        ['austere hat'] = {
            name = 'Austere Hat',
            skill = 'Leathercraft',
            level = 93,
            subcraft = { 'Clothcraft (7)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Rainbow Thread', 'Ram Leather', 'Sheep Leather', 'Velvet Hat', 'Yowie Skin' },
            hq1 = 'Penance Hat',
        },
        ['bison gamashes'] = {
            name = 'Bison Gamashes',
            skill = 'Leathercraft',
            level = 93,
            subcraft = { 'Clothcraft (29)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Buffalo Leather x2', 'Hippogryph Feather', 'Manticore Hair x2', 'Manticore Leather' },
            hq1 = 'Brave\'s Gamashes',
        },
        ['dusk trousers'] = {
            name = 'Dusk Trousers',
            skill = 'Leathercraft',
            level = 93,
            crystal = 'Earth Crystal',
            ingredients = { 'Behemoth Leather', 'Tiger Trousers' },
            hq1 = 'Dusk Trousers +1',
        },
        ['khimaira gamashes'] = {
            name = 'Khimaira Gamashes',
            skill = 'Leathercraft',
            level = 93,
            subcraft = { 'Clothcraft (29)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Buffalo Leather x2', 'Hippogryph Feather', 'Khimaira Mane x2', 'Manticore Leather' },
            hq1 = 'Stout Gamashes',
        },
        ['austere sabots'] = {
            name = 'Austere Sabots',
            skill = 'Leathercraft',
            level = 94,
            subcraft = { 'Clothcraft (8)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Ebony Sabots', 'Lindwurm Skin', 'Rainbow Thread', 'Ram Leather', 'Sheep Leather' },
            hq1 = 'Penance Sabots',
        },
        ['cardinal vest'] = {
            name = 'Cardinal Vest',
            skill = 'Leathercraft',
            level = 94,
            subcraft = { 'Smithing (31)', 'Clothcraft (25)' },
            crystal = 'Water Crystal',
            ingredients = { 'Beeswax', 'Gold Thread', 'Manticore Leather x2', 'Ram Leather', 'Steel Sheet', 'Tiger Leather x2' },
            hq1 = 'Bachelor Vest',
        },
        ['dusk ledelsens'] = {
            name = 'Dusk Ledelsens',
            skill = 'Leathercraft',
            level = 94,
            crystal = 'Earth Crystal',
            ingredients = { 'Behemoth Leather', 'Tiger Ledelsens' },
            hq1 = 'Dusk Ledelsens +1',
        },
        ['bison warbonnet'] = {
            name = 'Bison Warbonnet',
            skill = 'Leathercraft',
            level = 95,
            subcraft = { 'Clothcraft (33)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Buffalo Leather', 'Eft Skin', 'Hippogryph Feather x2', 'Manticore Hair x2', 'Manticore Leather' },
            hq1 = 'Brave\'s Warbonnet',
        },
        ['cerberus mantle'] = {
            name = 'Cerberus Mantle',
            skill = 'Leathercraft',
            level = 95,
            crystal = 'Ice Crystal',
            ingredients = { 'Cerberus Hide', 'Karakul Thread' },
            hq1 = 'Cerberus Mantle +1',
        },
        ['khimaira bonnet'] = {
            name = 'Khimaira Bonnet',
            skill = 'Leathercraft',
            level = 95,
            subcraft = { 'Clothcraft (33)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Buffalo Leather', 'Eft Skin', 'Hippogryph Feather x2', 'Khimaira Mane x2', 'Manticore Leather' },
            hq1 = 'Stout Bonnet',
        },
        ['tiger mask'] = {
            name = 'Tiger Mask',
            skill = 'Leathercraft',
            level = 95,
            crystal = 'Ice Crystal',
            ingredients = { 'Ram Leather', 'Tiger Hide x2', 'Wool Thread', 'Wyvern Skin' },
            hq1 = 'Feral Mask',
        },
        ['opaline boots'] = {
            name = 'Opaline Boots',
            skill = 'Leathercraft',
            level = 96,
            subcraft = { 'Clothcraft (42)' },
            crystal = 'Light Crystal',
            ingredients = { 'Manticore Leather', 'Rainbow Cloth', 'Rainbow Thread', 'Sheep Leather x2', 'Silk Cloth', 'Twinthread' },
            hq1 = 'Ceremonial Boots',
        },
        ['sha\'ir gages'] = {
            name = 'Sha\'ir Gages',
            skill = 'Leathercraft',
            level = 96,
            subcraft = { 'Goldsmithing (46)', 'Clothcraft (41)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Garnet', 'Gold Ingot', 'Gold Thread', 'High-Quality Bugard Skin', 'Tiger Leather', 'Velvet Cloth' },
            hq1 = 'Sheikh Gages',
        },
        ['austere cuffs'] = {
            name = 'Austere Cuffs',
            skill = 'Leathercraft',
            level = 97,
            subcraft = { 'Clothcraft (11)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Rainbow Thread', 'Tarasque Skin', 'Velvet Cuffs', 'Yowie Skin' },
            hq1 = 'Penance Cuffs',
        },
        ['bison kecks'] = {
            name = 'Bison Kecks',
            skill = 'Leathercraft',
            level = 97,
            subcraft = { 'Clothcraft (54)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Buffalo Leather x2', 'Manticore Hair x4', 'Manticore Leather', 'Tiger Leather' },
            hq1 = 'Brave\'s Kecks',
        },
        ['dusk mask'] = {
            name = 'Dusk Mask',
            skill = 'Leathercraft',
            level = 97,
            crystal = 'Earth Crystal',
            ingredients = { 'Behemoth Leather', 'Coeurl Mask' },
            hq1 = 'Dusk Mask +1',
        },
        ['griffon leather'] = {
            name = 'Griffon Leather',
            skill = 'Leathercraft',
            level = 97,
            crystal = 'Dark Crystal',
            ingredients = { 'Distilled Water', 'Griffon Hide', 'Windurstian Tea Leaves' },
        },
        ['khimaira kecks'] = {
            name = 'Khimaira Kecks',
            skill = 'Leathercraft',
            level = 97,
            subcraft = { 'Clothcraft (54)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Buffalo Leather x2', 'Khimaira Mane x4', 'Manticore Leather', 'Tiger Leather' },
            hq1 = 'Stout Kecks',
        },
        ['amaltheia leather'] = {
            name = 'Amaltheia Leather',
            skill = 'Leathercraft',
            level = 98,
            crystal = 'Dark Crystal',
            ingredients = { 'Amaltheia Hide', 'Distilled Water', 'Windurstian Tea Leaves' },
        },
        ['austere slops'] = {
            name = 'Austere Slops',
            skill = 'Leathercraft',
            level = 98,
            subcraft = { 'Clothcraft (11)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Lindwurm Skin', 'Rainbow Thread', 'Undead Skin', 'Velvet Slops', 'Wolf Hide' },
            hq1 = 'Penance Slops',
        },
        ['heroic boots'] = {
            name = 'Heroic Boots',
            skill = 'Leathercraft',
            level = 98,
            crystal = 'Earth Crystal',
            ingredients = { 'Iron Scales', 'Lindwurm Skin', 'Ram Leather x2' },
            hq1 = 'Heroic Boots +1',
        },
        ['bison jacket'] = {
            name = 'Bison Jacket',
            skill = 'Leathercraft',
            level = 99,
            subcraft = { 'Bonecraft (60)', 'Clothcraft (51)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Buffalo Horn', 'Buffalo Leather x2', 'Eft Skin', 'Manticore Hair x2', 'Manticore Leather x2' },
            hq1 = 'Brave\'s Jacket',
        },
        ['blessed pumps'] = {
            name = 'Blessed Pumps',
            skill = 'Leathercraft',
            level = 99,
            subcraft = { 'Clothcraft (56)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Eltoro Leather', 'Gold Thread', 'Manticore Hair', 'Tiger Leather', 'Velvet Cloth' },
            hq1 = 'Blessed Pumps +1',
        },
        ['dusk gloves'] = {
            name = 'Dusk Gloves',
            skill = 'Leathercraft',
            level = 99,
            crystal = 'Earth Crystal',
            ingredients = { 'Behemoth Leather', 'Tiger Gloves' },
            hq1 = 'Dusk Gloves +1',
        },
        ['khimaira jacket'] = {
            name = 'Khimaira Jacket',
            skill = 'Leathercraft',
            level = 99,
            subcraft = { 'Bonecraft (60)', 'Clothcraft (54)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Buffalo Horn', 'Buffalo Leather x2', 'Eft Skin', 'Khimaira Mane x2', 'Manticore Leather x2' },
            hq1 = 'Stout Jacket',
        },
        ['narasimha\'s vest'] = {
            name = 'Narasimha\'s Vest',
            skill = 'Leathercraft',
            level = 99,
            crystal = 'Water Crystal',
            ingredients = { 'Beeswax', 'Cardinal Vest', 'Manticore Leather', 'Narasimha Leather' },
            hq1 = 'Vishnu\'s Vest',
        },
        ['austere robe'] = {
            name = 'Austere Robe',
            skill = 'Leathercraft',
            level = 100,
            subcraft = { 'Clothcraft (37)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Rainbow Cloth', 'Rainbow Thread', 'Ram Leather', 'Tarasque Skin', 'Undead Skin', 'Velvet Robe', 'Wool Cloth', 'Yowie Skin' },
            hq1 = 'Penance Robe',
        },
        ['corselet'] = {
            name = 'Corselet',
            skill = 'Leathercraft',
            level = 100,
            subcraft = { 'Goldsmithing (<75)', 'Smithing (<66)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Adaman Sheet', 'Laminated Buffalo Leather', 'Marid Hair', 'Marid Leather', 'Mercury', 'Ovinnik Leather', 'Scintillant Ingot', 'Star Sapphire' },
            hq1 = 'Corselet +1',
        },
        ['dusk jerkin'] = {
            name = 'Dusk Jerkin',
            skill = 'Leathercraft',
            level = 100,
            subcraft = { 'Goldsmithing (41)' },
            crystal = 'Earth Crystal',
            ingredients = { 'Behemoth Leather', 'Gold Ingot', 'Northern Jerkin', 'Wyvern Skin' },
            hq1 = 'Dusk Jerkin +1',
        },
        ['phanter mask'] = {
            name = 'Phanter Mask',
            skill = 'Leathercraft',
            level = 102,
            crystal = 'Earth Crystal',
            ingredients = { 'High Quality Coeurl Hide x2', 'Ram Leather', 'Wool Thread', 'Wyvern Skin' },
            hq1 = 'Phanter Mask +1',
        },
    }
}

return leathercraft